;; Shared allocation, quota and metric semantics for both experimental and source ABIs.
(func $fail (param $code i32)
 (if (i32.eqz (global.get $failure)) (then (global.set $failure (local.get $code)))))
(func $quota (param $reason i32)
 (if (i32.eqz (global.get $failure)) (then
  (global.set $quota_reason (local.get $reason))
  (global.set $failure (i32.add (i32.const 1) (global.get $phase))))))
(func $live_bytes (result i32)
 (i32.mul (i32.sub (global.get $heap_cursor) (global.get $heap_baseline)) (i32.const 48)))
(func $runtime_tick (result i32)
 (if (global.get $failure) (then (return (i32.const 0))))
 (if (i32.ge_u (global.get $steps) (global.get $step_limit))
  (then (call $quota (i32.const 6)) (return (i32.const 0))))
 (global.set $steps (i32.add (global.get $steps) (i32.const 1)))
 (i32.const 1))
(func $reserve (result i32) (local $next i32) (local $bytes i32)
 (if (global.get $failure) (then (return (i32.const 0))))
 (local.set $next (i32.add (global.get $heap_cursor) (i32.const 1)))
 (local.set $bytes (i32.mul (i32.sub (local.get $next) (global.get $heap_baseline)) (i32.const 48)))
 (if (i32.or (i32.gt_u (local.get $next) (i32.const 4096))
             (i32.gt_u (local.get $bytes) (global.get $allocation_limit)))
  (then (call $quota (i32.const 1)) (return (i32.const 0))))
 (if (i32.eqz (call $storage_ensure (local.get $next)))
  (then (call $quota (i32.const 1)) (return (i32.const 0))))
 (global.set $heap_cursor (local.get $next))
 (global.set $allocated_total (i64.add (global.get $allocated_total) (i64.const 48)))
 (if (i32.gt_u (local.get $bytes) (global.get $allocation_peak))
  (then (global.set $allocation_peak (local.get $bytes))))
 (local.get $next))
(func $rollback (param $mark i32)
 (block $done (loop $next
  (br_if $done (i32.le_u (global.get $heap_cursor) (local.get $mark)))
  (call $storage_discard (global.get $heap_cursor))
  (global.set $heap_cursor (i32.sub (global.get $heap_cursor) (i32.const 1)))
  (global.set $released_total (i64.add (global.get $released_total) (i64.const 48)))
  (br $next))))
(func (export "metric") (param $key i32) (result i64)
 (if (i32.eq (local.get $key) (i32.const 0)) (then (return (i64.extend_i32_u (global.get $failure)))))
 (if (i32.eq (local.get $key) (i32.const 1)) (then (return (i64.extend_i32_u (global.get $quota_reason)))))
 (if (i32.eq (local.get $key) (i32.const 2)) (then (return (global.get $allocated_total))))
 (if (i32.eq (local.get $key) (i32.const 3)) (then (return (global.get $released_total))))
 (if (i32.eq (local.get $key) (i32.const 4)) (then (return (i64.extend_i32_u (call $live_bytes)))))
 (if (i32.eq (local.get $key) (i32.const 5)) (then (return (i64.extend_i32_u (global.get $allocation_peak)))))
 (if (i32.eq (local.get $key) (i32.const 6)) (then (return (i64.extend_i32_u (global.get $operand_peak)))))
 (if (i32.eq (local.get $key) (i32.const 7)) (then (return (i64.extend_i32_u (global.get $continuation_peak)))))
 (if (i32.eq (local.get $key) (i32.const 8)) (then (return (i64.extend_i32_u (global.get $steps)))))
 (if (i32.eq (local.get $key) (i32.const 9)) (then (return (i64.extend_i32_u (global.get $quote_invocations)))))
 (if (i32.eq (local.get $key) (i32.const 10)) (then (return (i64.extend_i32_u (i32.mul (memory.size) (i32.const 65536))))))
 (if (i32.eq (local.get $key) (i32.const 11)) (then (return (i64.extend_i32_u (i32.mul (global.get $heap_baseline) (i32.const 48))))))
 (if (i32.eq (local.get $key) (i32.const 12)) (then (return (i64.extend_i32_u (global.get $sp)))))
 (if (i32.eq (local.get $key) (i32.const 13)) (then (return (i64.extend_i32_u (global.get $reflection_steps)))))
 (i64.const -1))
