;; M3 runtime: no imports, resource-free values, bounded instance-owned region.
(type $entry (func (param i32)))
(memory (export "memory") 1 4)
(global $failure (mut i32) (i32.const 0))
(global $quota_reason (mut i32) (i32.const 0))
(global $phase (mut i32) (i32.const 0))
(global $heap_cursor (mut i32) (i32.const 0))
(global $heap_baseline (mut i32) (i32.const 0))
(global $allocation_limit (mut i32) (i32.const 65536))
(global $recipe_limit (mut i32) (i32.const 256))
(global $depth_limit (mut i32) (i32.const 256))
(global $operand_limit (mut i32) (i32.const 2048))
(global $continuation_limit (mut i32) (i32.const 4096))
(global $step_limit (mut i32) (i32.const 100000))
(global $allocated_total (mut i64) (i64.const 0))
(global $released_total (mut i64) (i64.const 0))
(global $allocation_peak (mut i32) (i32.const 0))
(global $operand_peak (mut i32) (i32.const 0))
(global $continuation_peak (mut i32) (i32.const 0))
(global $steps (mut i32) (i32.const 0))
(global $quote_invocations (mut i32) (i32.const 0))
(global $sp (mut i32) (i32.const 0))
(global $cp (mut i32) (i32.const 0))
(global $observed_program (mut i32) (i32.const 0))
(global $recipe_count (mut i32) (i32.const 0))
(global $reflection_steps (mut i32) (i32.const 0))

(func $fail (param $code i32)
 (if (i32.eqz (global.get $failure)) (then (global.set $failure (local.get $code)))))
(func $quota (param $reason i32)
 (if (i32.eqz (global.get $failure)) (then
  (global.set $quota_reason (local.get $reason))
  (global.set $failure (i32.add (i32.const 1) (global.get $phase))))))
(func $live_bytes (result i32)
 (i32.mul (i32.sub (global.get $heap_cursor) (global.get $heap_baseline)) (i32.const 48)))
(func $reserve (result i32) (local $next i32) (local $bytes i32)
 (if (global.get $failure) (then (return (i32.const 0))))
 (local.set $next (i32.add (global.get $heap_cursor) (i32.const 1)))
 (local.set $bytes (i32.mul (i32.sub (local.get $next) (global.get $heap_baseline)) (i32.const 48)))
 (if (i32.or (i32.gt_u (local.get $next) (i32.const 4096))
             (i32.gt_u (local.get $bytes) (global.get $allocation_limit)))
  (then (call $quota (i32.const 1)) (return (i32.const 0))))
 (if (i32.eqz (call $storage_ensure (local.get $next)))
  (then (call $quota (i32.const 1)) (return (i32.const 0))))
 (global.set $heap_cursor (local.get $next))
 (global.set $allocated_total (i64.add (global.get $allocated_total) (i64.const 48)))
 (if (i32.gt_u (local.get $bytes) (global.get $allocation_peak))
  (then (global.set $allocation_peak (local.get $bytes))))
 (local.get $next))
(func $rollback (param $mark i32)
 (block $done (loop $next
  (br_if $done (i32.le_u (global.get $heap_cursor) (local.get $mark)))
  (call $storage_discard (global.get $heap_cursor))
  (global.set $heap_cursor (i32.sub (global.get $heap_cursor) (i32.const 1)))
  (global.set $released_total (i64.add (global.get $released_total) (i64.const 48)))
  (br $next))))
(func $cleanup_internal (local $at i32)
 (global.set $sp (i32.const 0)) (global.set $cp (i32.const 0))
 (global.set $observed_program (i32.const 0)) (global.set $recipe_count (i32.const 0))
 ;; Registry starts at 61440 and contains permanent vocabulary handles only.
 (loop $clear
  (i64.store (local.get $at) (i64.const 0))
  (local.set $at (i32.add (local.get $at) (i32.const 8)))
  (br_if $clear (i32.lt_u (local.get $at) (i32.const 61440))))
 (call $rollback (global.get $heap_baseline)))
(func (export "cleanup") (result i32)
 (call $cleanup_internal) (call $live_bytes))
(func (export "begin")
 (param $allocation i32) (param $recipes i32) (param $depth i32)
 (param $operands i32) (param $continuations i32) (param $step_count i32) (result i32)
 (call $cleanup_internal)
 (global.set $failure (i32.const 0)) (global.set $quota_reason (i32.const 0))
 (global.set $phase (i32.const 0))
 (global.set $allocated_total (i64.const 0)) (global.set $released_total (i64.const 0))
 (global.set $allocation_peak (i32.const 0))
 (global.set $operand_peak (i32.const 0)) (global.set $continuation_peak (i32.const 0))
 (global.set $steps (i32.const 0)) (global.set $quote_invocations (i32.const 0))
 (global.set $reflection_steps (i32.const 0))
 (if (i32.or (i32.or (i32.gt_u (local.get $allocation) (i32.const 196608))
                     (i32.gt_u (local.get $recipes) (i32.const 256)))
              (i32.or (i32.gt_u (local.get $depth) (i32.const 256))
               (i32.or (i32.gt_u (local.get $operands) (i32.const 2048))
                (i32.or (i32.gt_u (local.get $continuations) (i32.const 4096))
                         (i32.gt_u (local.get $step_count) (i32.const 100000))))))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (global.set $allocation_limit (local.get $allocation))
 (global.set $recipe_limit (local.get $recipes)) (global.set $depth_limit (local.get $depth))
 (global.set $operand_limit (local.get $operands))
 (global.set $continuation_limit (local.get $continuations))
 (global.set $step_limit (local.get $step_count))
 (i32.const 0))
(func $vocab (param $index i32) (result i32)
 (if (i32.ge_u (local.get $index) (global.get $registry_count))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 (i32.load (i32.add (i32.const 61440) (i32.mul (local.get $index) (i32.const 4)))))
(func $module_init (local $at i32)
 (call $storage_init)
 (call $init_programs)
 (call $enqueue_program (global.get $p_root))
 (call $dispatch)
 (if (i32.or (global.get $failure) (i32.ne (global.get $sp) (global.get $registry_count)))
  (then unreachable))
 (block $done (loop $copy
  (br_if $done (i32.ge_u (local.get $at) (global.get $registry_count)))
  (if (i32.ne (call $slot_kind (local.get $at)) (i32.const 4)) (then unreachable))
  (i32.store (i32.add (i32.const 61440) (i32.mul (local.get $at) (i32.const 4)))
   (i32.wrap_i64 (call $slot_value (local.get $at))))
  (local.set $at (i32.add (local.get $at) (i32.const 1)))
  (br $copy)))
 (global.set $heap_baseline (global.get $heap_cursor))
 (call $cleanup_internal)
 (global.set $allocated_total (i64.const 0)) (global.set $released_total (i64.const 0))
 (global.set $allocation_peak (i32.const 0)))
(start $module_init)

;; Stable metric keys are part of the experimental driver protocol, not a public ABI.
(func (export "metric") (param $key i32) (result i64)
 (if (i32.eq (local.get $key) (i32.const 0)) (then (return (i64.extend_i32_u (global.get $failure)))))
 (if (i32.eq (local.get $key) (i32.const 1)) (then (return (i64.extend_i32_u (global.get $quota_reason)))))
 (if (i32.eq (local.get $key) (i32.const 2)) (then (return (global.get $allocated_total))))
 (if (i32.eq (local.get $key) (i32.const 3)) (then (return (global.get $released_total))))
 (if (i32.eq (local.get $key) (i32.const 4)) (then (return (i64.extend_i32_u (call $live_bytes)))))
 (if (i32.eq (local.get $key) (i32.const 5)) (then (return (i64.extend_i32_u (global.get $allocation_peak)))))
 (if (i32.eq (local.get $key) (i32.const 6)) (then (return (i64.extend_i32_u (global.get $operand_peak)))))
 (if (i32.eq (local.get $key) (i32.const 7)) (then (return (i64.extend_i32_u (global.get $continuation_peak)))))
 (if (i32.eq (local.get $key) (i32.const 8)) (then (return (i64.extend_i32_u (global.get $steps)))))
 (if (i32.eq (local.get $key) (i32.const 9)) (then (return (i64.extend_i32_u (global.get $quote_invocations)))))
 (if (i32.eq (local.get $key) (i32.const 10)) (then (return (i64.extend_i32_u (i32.mul (memory.size) (i32.const 65536))))))
 (if (i32.eq (local.get $key) (i32.const 11)) (then (return (i64.extend_i32_u (i32.mul (global.get $heap_baseline) (i32.const 48))))))
 (if (i32.eq (local.get $key) (i32.const 12)) (then (return (i64.extend_i32_u (global.get $sp)))))
 (if (i32.eq (local.get $key) (i32.const 13)) (then (return (i64.extend_i32_u (global.get $reflection_steps)))))
 (i64.const -1))
