;; M3 instance-local declarations and experimental lifetime; language operations are shared.
(type $entry (func (param i32)))
(memory (export "memory") 1 4)
(global $source_reflection i32 (i32.const 0))
(global $failure (mut i32) (i32.const 0))
(global $quota_reason (mut i32) (i32.const 0))
(global $phase (mut i32) (i32.const 0))
(global $heap_cursor (mut i32) (i32.const 0))
(global $heap_baseline (mut i32) (i32.const 0))
(global $allocation_limit (mut i32) (i32.const 65536))
(global $recipe_limit (mut i32) (i32.const 256))
(global $depth_limit (mut i32) (i32.const 256))
(global $operand_limit (mut i32) (i32.const 2048))
(global $continuation_limit (mut i32) (i32.const 4096))
(global $step_limit (mut i32) (i32.const 100000))
(global $allocated_total (mut i64) (i64.const 0))
(global $released_total (mut i64) (i64.const 0))
(global $allocation_peak (mut i32) (i32.const 0))
(global $operand_peak (mut i32) (i32.const 0))
(global $continuation_peak (mut i32) (i32.const 0))
(global $steps (mut i32) (i32.const 0))
(global $quote_invocations (mut i32) (i32.const 0))
(global $sp (mut i32) (i32.const 0))
(global $cp (mut i32) (i32.const 0))
(global $observed_program (mut i32) (i32.const 0))
(global $recipe_count (mut i32) (i32.const 0))
(global $reflection_steps (mut i32) (i32.const 0))
(global $rp (mut i32) (i32.const 0))
(func $cleanup_internal (local $at i32)
 (global.set $sp (i32.const 0)) (global.set $cp (i32.const 0))
 (global.set $observed_program (i32.const 0)) (global.set $recipe_count (i32.const 0))
 (loop $clear
  (i64.store (local.get $at) (i64.const 0))
  (local.set $at (i32.add (local.get $at) (i32.const 8)))
  (br_if $clear (i32.lt_u (local.get $at) (i32.const 61440))))
 (call $rollback (global.get $heap_baseline)))
(func (export "cleanup") (result i32)
 (call $cleanup_internal) (call $live_bytes))
(func (export "begin")
 (param $allocation i32) (param $recipes i32) (param $depth i32)
 (param $operands i32) (param $continuations i32) (param $step_count i32) (result i32)
 (call $cleanup_internal)
 (global.set $failure (i32.const 0)) (global.set $quota_reason (i32.const 0))
 (global.set $phase (i32.const 0))
 (global.set $allocated_total (i64.const 0)) (global.set $released_total (i64.const 0))
 (global.set $allocation_peak (i32.const 0))
 (global.set $operand_peak (i32.const 0)) (global.set $continuation_peak (i32.const 0))
 (global.set $steps (i32.const 0)) (global.set $quote_invocations (i32.const 0))
 (global.set $reflection_steps (i32.const 0))
 (if (i32.or (i32.or (i32.gt_u (local.get $allocation) (i32.const 196608))
                     (i32.gt_u (local.get $recipes) (i32.const 256)))
              (i32.or (i32.gt_u (local.get $depth) (i32.const 256))
               (i32.or (i32.gt_u (local.get $operands) (i32.const 2048))
                (i32.or (i32.gt_u (local.get $continuations) (i32.const 4096))
                         (i32.gt_u (local.get $step_count) (i32.const 100000))))))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (global.set $allocation_limit (local.get $allocation))
 (global.set $recipe_limit (local.get $recipes)) (global.set $depth_limit (local.get $depth))
 (global.set $operand_limit (local.get $operands))
 (global.set $continuation_limit (local.get $continuations))
 (global.set $step_limit (local.get $step_count))
 (i32.const 0))
(func $vocab (param $index i32) (result i32)
 (if (i32.ge_u (local.get $index) (global.get $registry_count))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 (i32.load (i32.add (i32.const 61440) (i32.mul (local.get $index) (i32.const 4)))))
(func $module_init (local $at i32)
 (call $storage_init)
 (call $init_programs)
 (call $enqueue_program (global.get $p_root))
 (call $dispatch)
 (if (i32.or (global.get $failure) (i32.ne (global.get $sp) (global.get $registry_count)))
  (then unreachable))
 (block $done (loop $copy
  (br_if $done (i32.ge_u (local.get $at) (global.get $registry_count)))
  (if (i32.ne (call $slot_kind (local.get $at)) (i32.const 4)) (then unreachable))
  (i32.store (i32.add (i32.const 61440) (i32.mul (local.get $at) (i32.const 4)))
   (i32.wrap_i64 (call $slot_value (local.get $at))))
  (local.set $at (i32.add (local.get $at) (i32.const 1)))
  (br $copy)))
 (global.set $heap_baseline (global.get $heap_cursor))
 (call $cleanup_internal)
 (global.set $allocated_total (i64.const 0)) (global.set $released_total (i64.const 0))
 (global.set $allocation_peak (i32.const 0)))
(start $module_init)
