;; Additional bootstrap data/control operations share the tagged stack and immutable cells.
(func $text (param $address i32) (param $length i32) (result i32)
 (call $new (i32.const 11) (i64.const 0) (i32.const 0) (i32.const 0) (i32.const 0)
  (local.get $address) (local.get $length) (i32.const 0) (i32.const 0) (i32.const 0)))
(func $op_inl (local $value i32)
 (local.set $value (call $pop_box))
 (call $push_ref (call $new (i32.const 12) (i64.const 0) (local.get $value)
  (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0))))
(func $op_inr (local $value i32)
 (local.set $value (call $pop_box))
 (call $push_ref (call $new (i32.const 13) (i64.const 0) (local.get $value)
  (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0))))
(func $op_case (local $right i32) (local $left i32) (local $sum i32) (local $tag i32)
 (local.set $right (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (local.set $left (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (if (i32.eqz (call $need (i32.const 1))) (then (return)))
 (local.set $tag (call $slot_kind (i32.sub (global.get $sp) (i32.const 1))))
 (if (i32.and (i32.ne (local.get $tag) (i32.const 12)) (i32.ne (local.get $tag) (i32.const 13)))
  (then (call $fail (i32.const 4)) (return)))
 (local.set $sum (i32.wrap_i64 (call $take)))
 (call $unbox (call $a (local.get $sum)))
 (if (i32.eq (local.get $tag) (i32.const 12))
  (then (call $enqueue_program (local.get $left)))
  (else (call $enqueue_program (local.get $right)))))
(func $restore_entry (type $entry) (param $value i32) (call $unbox (local.get $value)))
(func $op_dip (local $program i32) (local $value i32)
 (local.set $program (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (local.set $value (call $pop_box))
 (if (global.get $failure) (then (return)))
 (call $enqueue (i32.const 3) (local.get $value))
 (call $enqueue_program (local.get $program)))

;; Iterative size/depth accounting for an exact captured datum, before its recipe
;; or closure is allocated. Shared subgraphs count at each semantic occurrence.
(func $measure_data (param $value i32) (result i64)
 (local $todo i32) (local $h i32) (local $depth i32) (local $max_depth i32)
 (local $leaves i32) (local $tag i32) (local $address i32) (local $a i32) (local $b i32)
 (i32.store (i32.const 8192) (local.get $value)) (i32.store (i32.const 8196) (i32.const 1))
 (local.set $todo (i32.const 1))
 (block $done (loop $next
  (br_if $done (i32.or (global.get $failure) (i32.eqz (local.get $todo))))
  (if (i32.eqz (call $runtime_tick)) (then (br $done)))
  (local.set $todo (i32.sub (local.get $todo) (i32.const 1)))
  (local.set $address (i32.add (i32.const 8192) (i32.mul (local.get $todo) (i32.const 8))))
  (local.set $h (i32.load (local.get $address))) (local.set $depth (i32.load offset=4 (local.get $address)))
  (local.set $tag (call $kind (local.get $h)))
  (local.set $leaves (i32.add (local.get $leaves) (i32.const 1)))
  (if (i32.or (i32.eq (local.get $tag) (i32.const 4)) (i32.eq (local.get $tag) (i32.const 10))) (then
   (local.set $leaves (i32.add (local.get $leaves) (call $n (local.get $h))))
   (local.set $depth (i32.add (local.get $depth) (call $w (local.get $h))))))
  (if (i32.gt_u (local.get $depth) (local.get $max_depth)) (then (local.set $max_depth (local.get $depth))))
  (if (i32.gt_u (local.get $leaves) (global.get $recipe_limit)) (then (call $quota (i32.const 2)) (br $done)))
  (if (i32.gt_u (local.get $max_depth) (global.get $depth_limit)) (then (call $quota (i32.const 3)) (br $done)))
  (local.set $a (i32.const 0)) (local.set $b (i32.const 0))
  (if (i32.or (i32.eq (local.get $tag) (i32.const 5)) (i32.eq (local.get $tag) (i32.const 6)))
   (then (local.set $a (call $a (local.get $h))) (local.set $b (call $b (local.get $h)))))
  (if (i32.or (i32.eq (local.get $tag) (i32.const 12)) (i32.eq (local.get $tag) (i32.const 13)))
   (then (local.set $a (call $a (local.get $h)))))
  (if (i32.gt_u (local.get $todo) (i32.const 510)) (then (call $quota (i32.const 3)) (br $done)))
  (if (local.get $b) (then
   (local.set $address (i32.add (i32.const 8192) (i32.mul (local.get $todo) (i32.const 8))))
   (i32.store (local.get $address) (local.get $b))
   (i32.store offset=4 (local.get $address) (i32.add (local.get $depth) (i32.const 1)))
   (local.set $todo (i32.add (local.get $todo) (i32.const 1)))))
  (if (local.get $a) (then
   (local.set $address (i32.add (i32.const 8192) (i32.mul (local.get $todo) (i32.const 8))))
   (i32.store (local.get $address) (local.get $a))
   (i32.store offset=4 (local.get $address) (i32.add (local.get $depth) (i32.const 1)))
   (local.set $todo (i32.add (local.get $todo) (i32.const 1)))))
  (br $next)))
 (i64.or (i64.extend_i32_u (local.get $leaves)) (i64.shl (i64.extend_i32_u (local.get $max_depth)) (i64.const 32))))

(func $capture_recipe (param $value i32) (param $witness i32) (result i32) (local $tag i32)
 (local.set $tag (call $kind (local.get $value)))
 (if (i32.eq (local.get $tag) (i32.const 1))
  (then (return (call $atom (i32.const 1) (call $payload (local.get $value)) (i32.const 0)))))
 (if (i32.eq (local.get $tag) (i32.const 2))
  (then (return (call $atom (i32.const 4) (call $payload (local.get $value)) (i32.const 0)))))
 (if (i32.eq (local.get $tag) (i32.const 3))
  (then (return (call $atom (i32.const 5) (i64.const 0) (i32.const 0)))))
 (if (i32.eq (local.get $tag) (i32.const 4))
  (then (return (call $atom (i32.const 3) (i64.const 0) (local.get $value)))))
 ;; Complete type witness: both sum alternatives and nested Program interfaces.
 (call $new (i32.const 8) (i64.const 0) (local.get $value)
  (i32.const 0) (i32.const 0) (i32.const 8) (local.get $witness)
  (i32.const 0) (i32.const 0) (i32.const 0)))
(func $op_quote_typed (param $input i32) (param $output i32) (param $witness i32)
 (local $value i32) (local $recipe i32) (local $measure i64)
 (if (i32.eqz (global.get $recipe_limit)) (then (call $quota (i32.const 2)) (return)))
 (if (i32.eqz (global.get $depth_limit)) (then (call $quota (i32.const 3)) (return)))
 (local.set $value (call $pop_box))
 (if (global.get $failure) (then (return)))
 (local.set $measure (call $measure_data (local.get $value)))
 (if (global.get $failure) (then (return)))
 (local.set $recipe (call $capture_recipe (local.get $value) (local.get $witness)))
 (call $push_ref (call $program (i32.const 1) (local.get $input) (local.get $output)
  (local.get $recipe) (i64.const 0) (local.get $value) (i32.const 0)
  (i32.wrap_i64 (i64.shr_u (local.get $measure) (i64.const 32))) (i32.wrap_i64 (local.get $measure)))))
