;; Live-Slot-Design borrow bindings are invocation-frame inputs, never Data cells.
;; Slot-only shared memory extends beyond the bounded source image (1 MiB).
;; Continuation shadows [1048576,1050624) hold one frame pointer per slot.
;; Root bindings use [1050640,1051152), frames [1052672,1310720).
;; Each frame is parent:i32, selected target:i32, count:i32, host token:i32, then ordered
;; (logical input position:i32, root-issued ordinal:i32) pairs.
(func $live_frame_reset
 (i32.store (i32.const 1050624) (i32.const 0))
 (i32.store (i32.const 1050628) (i32.const 1052672))
 (i32.store (i32.const 1050632) (i32.const 0))
 (global.set $live_target (i32.const 0))
 (global.set $live_frame (i32.const 0)))
(func $live_root_bind (param $position i32) (param $ordinal i32)
 (local $count i32) (local $at i32) (local $address i32)
 (if (global.get $failure) (then (return)))
 (local.set $count (i32.load (i32.const 1050632)))
 (if (i32.or (i32.ge_u (local.get $position) (i32.const 64))
             (i32.ge_u (local.get $count) (i32.const 64)))
  (then (call $fail (i32.const 4)) (return)))
 (block $checked (loop $next
  (br_if $checked (i32.ge_u (local.get $at) (local.get $count)))
  (local.set $address (i32.add (i32.const 1050640) (i32.mul (local.get $at) (i32.const 8))))
  (if (i32.or (i32.eq (i32.load (local.get $address)) (local.get $position))
              (i32.eq (i32.load offset=4 (local.get $address)) (local.get $ordinal)))
   (then (call $fail (i32.const 4)) (return)))
  (local.set $at (i32.add (local.get $at) (i32.const 1)))
  (br $next)))
 (local.set $address (i32.add (i32.const 1050640) (i32.mul (local.get $count) (i32.const 8))))
 (i32.store (local.get $address) (local.get $position))
 (i32.store offset=4 (local.get $address) (local.get $ordinal))
 (i32.store (i32.const 1050632) (i32.add (local.get $count) (i32.const 1))))
(func $live_root_count (result i32) (i32.load (i32.const 1050632)))
(func $live_root_position (param $at i32) (result i32)
 (if (i32.ge_u (local.get $at) (call $live_root_count))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 (i32.load (i32.add (i32.const 1050640) (i32.mul (local.get $at) (i32.const 8)))))
(func $live_root_ordinal (param $at i32) (result i32)
 (if (i32.ge_u (local.get $at) (call $live_root_count))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 (i32.load offset=4 (i32.add (i32.const 1050640) (i32.mul (local.get $at) (i32.const 8)))))
(func $live_frame_new (param $count i32) (param $target i32) (result i32)
 (local $at i32) (local $bytes i32) (local $end i32)
 (if (global.get $failure) (then (return (i32.const 0))))
 (if (i32.gt_u (local.get $count) (i32.const 64))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 (local.set $bytes (i32.add (i32.const 16) (i32.mul (local.get $count) (i32.const 8))))
 (local.set $at (i32.load (i32.const 1050628)))
 (local.set $end (i32.add (local.get $at) (local.get $bytes)))
 (if (i32.gt_u (local.get $end) (i32.const 1310720))
  (then (call $quota (i32.const 5)) (return (i32.const 0))))
 (i32.store (local.get $at) (i32.load (i32.const 1050624)))
 (i32.store offset=4 (local.get $at) (local.get $target))
 (i32.store offset=8 (local.get $at) (local.get $count))
 (i32.store offset=12 (local.get $at) (i32.const 0))
 (i32.store (i32.const 1050628) (local.get $end))
 (local.get $at))
(func $live_frame_bind (param $frame i32) (param $at i32)
 (param $position i32) (param $ordinal i32)
 (local $address i32)
 (if (global.get $failure) (then (return)))
 (if (i32.or (i32.eqz (local.get $frame))
             (i32.or (i32.ge_u (local.get $at) (i32.load offset=8 (local.get $frame)))
                     (i32.ge_u (local.get $position) (i32.const 64))))
  (then (call $fail (i32.const 4)) (return)))
 (local.set $address (i32.add (i32.add (local.get $frame) (i32.const 16))
                             (i32.mul (local.get $at) (i32.const 8))))
 (i32.store (local.get $address) (local.get $position))
 (i32.store offset=4 (local.get $address) (local.get $ordinal)))
(func $live_frame_get (param $position i32) (result i32)
 (local $frame i32) (local $at i32) (local $count i32) (local $address i32)
 (local.set $frame (i32.load (i32.const 1050624)))
 (if (i32.eqz (local.get $frame))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 (local.set $count (i32.load offset=8 (local.get $frame)))
 (block $absent (loop $next
  (br_if $absent (i32.ge_u (local.get $at) (local.get $count)))
  (local.set $address (i32.add (i32.add (local.get $frame) (i32.const 16))
                              (i32.mul (local.get $at) (i32.const 8))))
  (if (i32.eq (i32.load (local.get $address)) (local.get $position))
   (then (return (i32.load offset=4 (local.get $address)))))
  (local.set $at (i32.add (local.get $at) (i32.const 1)))
  (br $next)))
 (call $fail (i32.const 4))
 (i32.const 0))
(func $live_frame_enter (param $frame i32)
 (if (global.get $failure) (then (return)))
 (if (i32.or (i32.lt_u (local.get $frame) (i32.const 1052672))
             (i32.ge_u (local.get $frame) (i32.load (i32.const 1050628))))
  (then (call $fail (i32.const 4)) (return)))
 (i32.store (i32.const 1050624) (local.get $frame))
 (global.set $live_target (i32.load offset=4 (local.get $frame)))
 (global.set $live_frame (i32.load offset=12 (local.get $frame))))
(func $live_frame_register (param $frame i32) (param $site i32)
 (local $token i32)
 (if (global.get $failure) (then (return)))
 (if (i32.or (i32.lt_u (local.get $frame) (i32.const 1052672))
             (i32.ge_u (local.get $frame) (i32.load (i32.const 1050628))))
  (then (call $fail (i32.const 4)) (return)))
 ;; A host exception leaves the provisional failure set. Zero is a refusal.
 (global.set $failure (i32.const 5))
 (local.set $token (call $host_live_frame_enter
  (local.get $site) (local.get $frame) (i32.load offset=4 (local.get $frame))))
 (if (i32.eqz (local.get $token))
  (then (global.set $failure (i32.const 4)) (return)))
 (global.set $failure (i32.const 0))
 (i32.store offset=12 (local.get $frame) (local.get $token))
 (call $live_frame_enter (local.get $frame)))
(func $live_frame_restore (param $next i32)
 (local $current i32) (local $walk i32) (local $end i32)
 (local.set $current (i32.load (i32.const 1050624)))
 (if (i32.eq (local.get $current) (local.get $next)) (then (return)))
 (local.set $walk (local.get $current))
 (block $left (loop $release
  (br_if $left (i32.eq (local.get $walk) (local.get $next)))
  (if (i32.eqz (local.get $walk))
   (then (call $fail (i32.const 4)) (return)))
  ;; The host closes each frame before this address is reusable; a throw
  ;; leaves failure terminal and the host root cleanup still owns the ledger.
  (if (i32.ne (call $host_live_frame_leave
                (i32.load offset=12 (local.get $walk))) (i32.const 0))
   (then (call $fail (i32.const 4)) (return)))
  (local.set $walk (i32.load (local.get $walk)))
  (br $release)))
 (if (i32.eqz (local.get $next))
  (then (i32.store (i32.const 1050628) (i32.const 1052672)))
  (else
   (local.set $end (i32.add (local.get $next)
    (i32.add (i32.const 16)
     (i32.mul (i32.load offset=8 (local.get $next)) (i32.const 8)))))
   (i32.store (i32.const 1050628) (local.get $end))))
 (i32.store (i32.const 1050624) (local.get $next))
 (global.set $live_target
  (if (result i32) (local.get $next)
   (then (i32.load offset=4 (local.get $next))) (else (i32.const 0))))
 (global.set $live_frame
  (if (result i32) (local.get $next)
   (then (i32.load offset=12 (local.get $next))) (else (i32.const 0)))))
