(func $op_dup (local $index i32)
 (if (i32.eqz (call $need (i32.const 1))) (then (return)))
 (local.set $index (i32.sub (global.get $sp) (i32.const 1)))
 (call $push_tag (call $slot_kind (local.get $index)) (call $slot_value (local.get $index))))
(func $op_drop (drop (call $take)))
(func $op_swap (local $left_kind i32) (local $right_kind i32) (local $left i64) (local $right i64)
 (if (i32.eqz (call $need (i32.const 2))) (then (return)))
 (local.set $right_kind (call $slot_kind (i32.sub (global.get $sp) (i32.const 1))))
 (local.set $right (call $take))
 (local.set $left_kind (call $slot_kind (i32.sub (global.get $sp) (i32.const 1))))
 (local.set $left (call $take))
 (call $push_tag (local.get $right_kind) (local.get $right))
 (call $push_tag (local.get $left_kind) (local.get $left)))
(func $op_add (local $right i64) (local $left i64)
 (local.set $right (call $pop_kind (i32.const 1)))
 (local.set $left (call $pop_kind (i32.const 1)))
 (call $push_i64 (i64.add (local.get $left) (local.get $right))))
(func $op_sub (local $right i64) (local $left i64)
 (local.set $right (call $pop_kind (i32.const 1)))
 (local.set $left (call $pop_kind (i32.const 1)))
 (call $push_i64 (i64.sub (local.get $left) (local.get $right))))
(func $op_mul (local $right i64) (local $left i64)
 (local.set $right (call $pop_kind (i32.const 1)))
 (local.set $left (call $pop_kind (i32.const 1)))
 (call $push_i64 (i64.mul (local.get $left) (local.get $right))))
(func $op_equals (local $kind i32) (local $right i64) (local $left i64)
 (if (i32.eqz (call $need (i32.const 2))) (then (return)))
 (local.set $kind (call $slot_kind (i32.sub (global.get $sp) (i32.const 1))))
 (if (i32.or (i32.gt_u (local.get $kind) (i32.const 3))
              (i32.ne (local.get $kind) (call $slot_kind (i32.sub (global.get $sp) (i32.const 2)))))
  (then (call $fail (i32.const 4)) (return)))
 (local.set $right (call $take)) (local.set $left (call $take))
 (call $push_bool (i64.eq (local.get $left) (local.get $right))))
(func $op_pair (local $right i32) (local $left i32)
 (local.set $right (call $pop_box)) (local.set $left (call $pop_box))
 (call $push_ref (call $new (i32.const 5) (i64.const 0) (local.get $left) (local.get $right)
  (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0))))
(func $op_unpair (local $pair i32)
 (local.set $pair (i32.wrap_i64 (call $pop_kind (i32.const 5))))
 (if (global.get $failure) (then (return)))
 (call $unbox (call $a (local.get $pair))) (call $unbox (call $b (local.get $pair))))
(func $op_nil
 (call $push_ref (call $new (i32.const 7) (i64.const 0)
  (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)
  (i32.const 0) (i32.const 0) (i32.const 0))))
(func $op_cons (local $tail i32) (local $head i32) (local $tag i32)
 (if (i32.eqz (call $need (i32.const 2))) (then (return)))
 (local.set $tag (call $slot_kind (i32.sub (global.get $sp) (i32.const 1))))
 (if (i32.and (i32.ne (local.get $tag) (i32.const 6)) (i32.ne (local.get $tag) (i32.const 7)))
  (then (call $fail (i32.const 4)) (return)))
 (local.set $tail (i32.wrap_i64 (call $take)))
 (local.set $head (call $pop_box))
 (call $push_ref (call $new (i32.const 6) (i64.const 0) (local.get $head) (local.get $tail)
  (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0))))
(func $op_list_case (local $cons_branch i32) (local $nil_branch i32) (local $list i32) (local $tag i32)
 (local.set $cons_branch (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (local.set $nil_branch (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (if (i32.eqz (call $need (i32.const 1))) (then (return)))
 (local.set $tag (call $slot_kind (i32.sub (global.get $sp) (i32.const 1))))
 (local.set $list (i32.wrap_i64 (call $take)))
 (if (i32.eq (local.get $tag) (i32.const 7))
  (then (call $enqueue_program (local.get $nil_branch)) (return)))
 (if (i32.ne (local.get $tag) (i32.const 6))
  (then (call $fail (i32.const 4)) (return)))
 (call $unbox (call $a (local.get $list)))
 (call $push_ref (call $b (local.get $list)))
 (call $enqueue_program (local.get $cons_branch)))
(func $op_if (local $otherwise i32) (local $then i32) (local $condition i32)
 (local.set $otherwise (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (local.set $then (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (local.set $condition (i32.wrap_i64 (call $pop_kind (i32.const 2))))
 (if (global.get $failure) (then (return)))
 (if (local.get $condition)
  (then (call $enqueue_program (local.get $then)))
  (else (call $enqueue_program (local.get $otherwise)))))
