(func $atom (param $kind i32) (param $value i64) (param $child i32) (result i32)
 (call $new (i32.const 8) (local.get $value) (local.get $child)
  (i32.const 0) (i32.const 0) (local.get $kind) (i32.const 0)
  (i32.const 0) (i32.const 0) (i32.const 0)))
(func $concat_recipe (param $left i32) (param $right i32) (result i32)
 (if (global.get $failure) (then (return (i32.const 0))))
 (if (i32.eqz (local.get $left)) (then (return (local.get $right))))
 (if (i32.eqz (local.get $right)) (then (return (local.get $left))))
 (call $new (i32.const 9) (i64.const 0) (local.get $left) (local.get $right)
  (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)))
(func $program (param $entry_index i32) (param $input i32) (param $output i32)
 (param $recipe i32) (param $capture i64) (param $left i32) (param $right i32)
 (param $depth i32) (param $leaves i32) (result i32)
 (if (global.get $failure) (then (return (i32.const 0))))
 (if (i32.gt_u (local.get $leaves) (global.get $recipe_limit))
  (then (call $quota (i32.const 2)) (return (i32.const 0))))
 (if (i32.gt_u (local.get $depth) (global.get $depth_limit))
  (then (call $quota (i32.const 3)) (return (i32.const 0))))
 (call $new (i32.const 4) (local.get $capture) (local.get $left) (local.get $right)
  (local.get $recipe) (local.get $entry_index) (local.get $input) (local.get $output)
  (local.get $depth) (local.get $leaves)))
(func $compose (param $left i32) (param $right i32) (result i32)
 (local $depth i32) (local $leaves i32) (local $recipe i32)
 (if (global.get $failure) (then (return (i32.const 0))))
 (if (i32.or (i32.ne (call $kind (local.get $left)) (i32.const 4))
             (i32.ne (call $kind (local.get $right)) (i32.const 4)))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 ;; Complete ordered signature IDs, not argument counts or suffix matches.
 (if (i32.ne (call $z (local.get $left)) (call $y (local.get $right)))
  (then (call $fail (i32.const 3)) (return (i32.const 0))))
 (local.set $leaves (i32.add (call $n (local.get $left)) (call $n (local.get $right))))
 (local.set $depth (call $w (local.get $left)))
 (if (i32.gt_u (call $w (local.get $right)) (local.get $depth))
  (then (local.set $depth (call $w (local.get $right)))))
 (local.set $depth (i32.add (local.get $depth) (i32.const 1)))
 ;; Check both bounds before allocating recipe metadata or the program cell.
 (if (i32.gt_u (local.get $leaves) (global.get $recipe_limit))
  (then (call $quota (i32.const 2)) (return (i32.const 0))))
 (if (i32.gt_u (local.get $depth) (global.get $depth_limit))
  (then (call $quota (i32.const 3)) (return (i32.const 0))))
 (local.set $recipe (call $concat_recipe (call $c (local.get $left)) (call $c (local.get $right))))
 (call $program (i32.const 2) (call $y (local.get $left)) (call $z (local.get $right))
  (local.get $recipe)
  (if (result i64) (global.get $source_reflection)
   (then (i64.or (call $payload (local.get $left)) (call $payload (local.get $right))))
   (else (i64.const 0)))
  (local.get $left) (local.get $right)
  (local.get $depth) (local.get $leaves)))
(func $empty_entry (type $entry) (param $environment i32))
(func $quote_entry (type $entry) (param $environment i32)
 (global.set $quote_invocations (i32.add (global.get $quote_invocations) (i32.const 1)))
 (if (call $a (local.get $environment))
  (then (call $unbox (call $a (local.get $environment))))
  (else (call $push_i64 (call $payload (local.get $environment))))))
(func $compose_entry (type $entry) (param $environment i32)
 ;; LIFO scheduling: left runs first; right is the pending continuation.
 (call $enqueue_program (call $b (local.get $environment)))
 (call $enqueue_program (call $a (local.get $environment))))
(func $op_quote (param $input i32) (param $output i32)
 (local $value i64) (local $recipe i32) (local $handle i32)
 (local.set $value (call $pop_kind (i32.const 1)))
 (if (global.get $failure) (then (return)))
 (local.set $recipe (call $atom (i32.const 1) (local.get $value) (i32.const 0)))
 (local.set $handle (call $program (i32.const 1) (local.get $input) (local.get $output)
  (local.get $recipe) (local.get $value) (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 1)))
 (call $push_ref (local.get $handle)))
(func $op_compose (local $right i32) (local $left i32)
 (local.set $right (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (local.set $left (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (if (global.get $failure) (then (return)))
 (call $push_ref (call $compose (local.get $left) (local.get $right))))
(func $op_run (local $program i32)
 (local.set $program (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (if (global.get $failure) (then (return)))
 (call $enqueue_program (local.get $program)))
(func $op_reflect (local $program i32) (local $recipe i32)
 (local.set $program (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (if (global.get $failure) (then (return)))
 (local.set $recipe (call $c (local.get $program)))
 ;; Box Syntax independently of its possibly empty recipe, so aggregates retain it.
 (call $push_ref (call $new (i32.const 10) (i64.const 0) (local.get $recipe)
  (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)
  (i32.const 0) (call $w (local.get $program)) (call $n (local.get $program)))))
