;; Observation walks immutable recipe data only. It never dispatches executable code.
(global $rp (mut i32) (i32.const 0))
(func $walk_push (param $recipe i32)
 (if (i32.or (global.get $failure) (i32.eqz (local.get $recipe))) (then (return)))
 (if (i32.ge_u (global.get $rp) (i32.const 2048))
  (then (call $quota (i32.const 7)) (return)))
 (i32.store (i32.add (i32.const 12288) (i32.mul (global.get $rp) (i32.const 4))) (local.get $recipe))
 (global.set $rp (i32.add (global.get $rp) (i32.const 1))))
(func $observe_atom (param $tag i32) (param $value i64) (local $address i32)
 (if (global.get $failure) (then (return)))
 (if (i32.ge_u (global.get $recipe_count) (i32.const 2048))
  (then (call $quota (i32.const 7)) (return)))
 (local.set $address (i32.add (i32.const 24576) (i32.mul (global.get $recipe_count) (i32.const 16))))
 (i32.store (local.get $address) (local.get $tag))
 (i64.store offset=8 (local.get $address) (local.get $value))
 (global.set $recipe_count (i32.add (global.get $recipe_count) (i32.const 1))))
(func (export "reflect") (result i32) (local $recipe i32) (local $tag i32) (local $address i32)
 (global.set $phase (i32.const 1))
 (global.set $recipe_count (i32.const 0)) (global.set $rp (i32.const 0))
 (global.set $reflection_steps (i32.const 0))
 (if (global.get $failure) (then (return (global.get $failure))))
 (if (i32.eqz (global.get $observed_program))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (call $walk_push (call $c (global.get $observed_program)))
 (block $done (loop $next
  (br_if $done (i32.or (global.get $failure) (i32.eqz (global.get $rp))))
  (if (i32.ge_u (global.get $reflection_steps) (global.get $step_limit))
   (then (call $quota (i32.const 7)) (br $done)))
  (global.set $reflection_steps (i32.add (global.get $reflection_steps) (i32.const 1)))
  (global.set $rp (i32.sub (global.get $rp) (i32.const 1)))
  (local.set $address (i32.add (i32.const 12288) (i32.mul (global.get $rp) (i32.const 4))))
  (local.set $recipe (i32.load (local.get $address)))
  (i32.store (local.get $address) (i32.const 0))
  (if (i32.eq (local.get $recipe) (i32.const -1))
   (then (call $observe_atom (i32.const 6) (i64.const 0)))
   (else
    (local.set $tag (call $kind (local.get $recipe)))
    (if (i32.eq (local.get $tag) (i32.const 9))
     (then
      (call $walk_push (call $b (local.get $recipe)))
      (call $walk_push (call $a (local.get $recipe))))
     (else
      (if (i32.ne (local.get $tag) (i32.const 8))
       (then (call $fail (i32.const 4)) (br $done)))
      (local.set $tag (call $x (local.get $recipe)))
      (if (i32.eq (local.get $tag) (i32.const 3))
       (then
        ;; Delimit nested Program literals by value; never expose a cell address.
        (call $observe_atom (i32.const 3) (i64.const 0))
        (call $walk_push (i32.const -1))
        (call $walk_push (call $c (call $a (local.get $recipe)))))
       (else (call $observe_atom (local.get $tag) (call $payload (local.get $recipe)))))))))
  (br $next)))
 (if (global.get $failure) (then (call $cleanup_internal)))
 (global.get $failure))
(func (export "recipe_length") (result i32) (global.get $recipe_count))
(func $recipe_address (param $index i32) (result i32)
 (if (i32.ge_u (local.get $index) (global.get $recipe_count))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 (i32.add (i32.const 24576) (i32.mul (local.get $index) (i32.const 16))))
(func (export "recipe_kind") (param $index i32) (result i32) (local $address i32)
 (local.set $address (call $recipe_address (local.get $index)))
 (if (global.get $failure) (then (return (i32.const 0))))
 (i32.load (local.get $address)))
(func (export "recipe_value") (param $index i32) (result i64) (local $address i32)
 (local.set $address (call $recipe_address (local.get $index)))
 (if (global.get $failure) (then (return (i64.const 0))))
 (i64.load offset=8 (local.get $address)))
