;; Observation walks immutable data only. It never invokes executable entries.
;; Positive work items are recipe nodes, negative items boxed data, MIN_INT ends a group.
(func $walk_push (param $recipe i32)
 (if (i32.or (global.get $failure) (i32.eqz (local.get $recipe))) (then (return)))
 (if (i32.ge_u (global.get $rp) (i32.const 2048))
  (then (call $quota (i32.const 7)) (return)))
 (i32.store (i32.add (i32.const 12288) (i32.mul (global.get $rp) (i32.const 4))) (local.get $recipe))
 (global.set $rp (i32.add (global.get $rp) (i32.const 1))))
(func $observation_tick (result i32)
 (if (global.get $failure) (then (return (i32.const 0))))
 (if (i32.ge_u (global.get $reflection_steps) (global.get $step_limit))
  (then (call $quota (i32.const 7)) (return (i32.const 0))))
 (global.set $reflection_steps (i32.add (global.get $reflection_steps) (i32.const 1)))
 (i32.const 1))
(func $observe_atom (param $tag i32) (param $value i64) (local $address i32)
 (if (global.get $failure) (then (return)))
 (if (i32.ge_u (global.get $recipe_count) (i32.const 2048))
  (then (call $quota (i32.const 7)) (return)))
 (local.set $address (i32.add (i32.const 24576) (i32.mul (global.get $recipe_count) (i32.const 16))))
 (i32.store (local.get $address) (local.get $tag))
 (i64.store offset=8 (local.get $address) (local.get $value))
 (global.set $recipe_count (i32.add (global.get $recipe_count) (i32.const 1))))
(func $observe_interface (param $program i32)
 (if (global.get $source_reflection) (then
  (call $observe_atom (i32.const 17) (i64.extend_i32_u (call $y (local.get $program))))
  (call $observe_atom (i32.const 18) (i64.extend_i32_u (call $z (local.get $program))))
  (call $observe_atom (i32.const 19) (call $payload (local.get $program))))))
(func $observe_data (param $value i32) (local $tag i32) (local $at i32) (local $length i32)
 (local.set $tag (call $kind (local.get $value)))
 (if (i32.eq (local.get $tag) (i32.const 1))
  (then (call $observe_atom (i32.const 1) (call $payload (local.get $value))) (return)))
 (if (i32.eq (local.get $tag) (i32.const 2))
  (then (call $observe_atom (i32.const 4) (call $payload (local.get $value))) (return)))
 (if (i32.eq (local.get $tag) (i32.const 3))
  (then (call $observe_atom (i32.const 5) (i64.const 0)) (return)))
 (call $walk_push (i32.const -2147483648))
 (if (i32.eq (local.get $tag) (i32.const 4)) (then
  (call $observe_atom (i32.const 14) (i64.const 0)) (call $observe_interface (local.get $value))
  (call $walk_push (call $c (local.get $value))) (return)))
 (if (i32.eq (local.get $tag) (i32.const 5)) (then
  (call $observe_atom (i32.const 9) (i64.const 0))
  (call $walk_push (i32.sub (i32.const 0) (call $b (local.get $value))))
  (call $walk_push (i32.sub (i32.const 0) (call $a (local.get $value)))) (return)))
 (if (i32.or (i32.eq (local.get $tag) (i32.const 6)) (i32.eq (local.get $tag) (i32.const 7))) (then
  (call $observe_atom (i32.const 10) (i64.const 0))
  (if (i32.eq (local.get $tag) (i32.const 6)) (then
   (call $walk_push (i32.sub (i32.const 0) (call $b (local.get $value))))
   (call $walk_push (i32.sub (i32.const 0) (call $a (local.get $value)))))) (return)))
 (if (i32.eq (local.get $tag) (i32.const 10)) (then
  (call $observe_atom (i32.const 13) (i64.const 0))
  (call $walk_push (call $a (local.get $value))) (return)))
 (if (i32.eq (local.get $tag) (i32.const 11)) (then
  (call $observe_atom (i32.const 8) (i64.const 0))
  (local.set $length (call $y (local.get $value)))
  (block $done (loop $byte
   (br_if $done (i32.or (global.get $failure) (i32.ge_u (local.get $at) (local.get $length))))
   (if (i32.eqz (call $observation_tick)) (then (br $done)))
   (call $observe_atom (i32.const 7) (i64.extend_i32_u (i32.load8_u (i32.add (call $x (local.get $value)) (local.get $at)))))
   (local.set $at (i32.add (local.get $at) (i32.const 1))) (br $byte))) (return)))
 (if (i32.or (i32.eq (local.get $tag) (i32.const 12)) (i32.eq (local.get $tag) (i32.const 13))) (then
  (call $observe_atom (i32.sub (local.get $tag) (i32.const 1)) (i64.const 0))
  (call $walk_push (i32.sub (i32.const 0) (call $a (local.get $value)))) (return)))
 (if (i32.eq (local.get $tag) (i32.const 14)) (then
  (call $observe_atom (i32.const 23) (i64.extend_i32_u (call $x (local.get $value)))) (return)))
 (if (i32.eq (local.get $tag) (i32.const 15)) (then
  (call $observe_atom (i32.const 24) (call $payload (local.get $value))) (return)))
 (if (i32.eq (local.get $tag) (i32.const 16)) (then
  (call $observe_atom (i32.const 23) (i64.extend_i32_u (call $x (call $b (local.get $value)))))
  (call $observe_atom (i32.const 24) (call $payload (call $c (local.get $value))))
  (call $observe_atom (i32.const 25) (call $payload (local.get $value)))
  (call $walk_push (i32.const -2147483648))
  (call $walk_push (i32.sub (i32.const 0) (call $a (local.get $value)))) (return)))
 (call $fail (i32.const 4)))
(func $observe_recipe (param $recipe i32) (local $tag i32)
 (local.set $tag (call $kind (local.get $recipe)))
 (if (i32.eq (local.get $tag) (i32.const 9)) (then
  (call $walk_push (call $b (local.get $recipe)))
  (call $walk_push (call $a (local.get $recipe))) (return)))
 (if (i32.ne (local.get $tag) (i32.const 8))
  (then (call $fail (i32.const 4)) (return)))
 (local.set $tag (call $x (local.get $recipe)))
 (if (i32.eq (local.get $tag) (i32.const 3)) (then
  (call $observe_atom (i32.const 3) (i64.const 0))
  (call $observe_interface (call $a (local.get $recipe)))
  (call $walk_push (i32.const -2147483648))
  (call $walk_push (call $c (call $a (local.get $recipe)))) (return)))
 (if (i32.eq (local.get $tag) (i32.const 8)) (then
  (if (i32.ne (call $kind (call $a (local.get $recipe))) (i32.const 11))
   (then (call $observe_atom (i32.const 16) (i64.extend_i32_u (call $y (local.get $recipe))))))
  (call $walk_push (i32.sub (i32.const 0) (call $a (local.get $recipe)))) (return)))
 (call $observe_atom (local.get $tag) (call $payload (local.get $recipe)))
 (if (i32.and (global.get $source_reflection)
       (i32.or (i32.eq (local.get $tag) (i32.const 2)) (i32.eq (local.get $tag) (i32.const 15)))) (then
  (call $observe_atom (i32.const 20) (i64.extend_i32_u (call $y (local.get $recipe))))
  (call $observe_atom (i32.const 21) (i64.extend_i32_u (call $z (local.get $recipe))))
  (call $observe_atom (i32.const 22) (i64.extend_i32_u (call $w (local.get $recipe)))))))
(func $reflect_internal (export "reflect") (result i32) (local $recipe i32) (local $address i32)
 (global.set $phase (i32.const 1))
 (global.set $recipe_count (i32.const 0)) (global.set $rp (i32.const 0))
 (global.set $reflection_steps (i32.const 0))
 (if (global.get $failure) (then (return (global.get $failure))))
 (if (i32.eqz (global.get $observed_program))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (if (i32.eq (call $kind (global.get $observed_program)) (i32.const 16))
  (then (call $observe_data (global.get $observed_program)))
  (else (if (i32.or (i32.eq (call $kind (global.get $observed_program)) (i32.const 14))
                    (i32.eq (call $kind (global.get $observed_program)) (i32.const 15)))
   (then (call $observe_data (global.get $observed_program)))
   (else (if (i32.eq (call $kind (global.get $observed_program)) (i32.const 10))
    (then (call $walk_push (call $a (global.get $observed_program))))
    (else (call $walk_push (call $c (global.get $observed_program)))))))))
 (block $done (loop $next
  (br_if $done (i32.or (global.get $failure) (i32.eqz (global.get $rp))))
  (if (i32.eqz (call $observation_tick)) (then (br $done)))
  (global.set $rp (i32.sub (global.get $rp) (i32.const 1)))
  (local.set $address (i32.add (i32.const 12288) (i32.mul (global.get $rp) (i32.const 4))))
  (local.set $recipe (i32.load (local.get $address)))
  (i32.store (local.get $address) (i32.const 0))
  (if (i32.eq (local.get $recipe) (i32.const -2147483648))
   (then (call $observe_atom (i32.const 6) (i64.const 0)))
   (else (if (i32.lt_s (local.get $recipe) (i32.const 0))
    (then (call $observe_data (i32.sub (i32.const 0) (local.get $recipe))))
    (else (call $observe_recipe (local.get $recipe))))))
  (br $next)))
 (if (global.get $failure) (then (call $cleanup_internal)))
 (global.get $failure))
(func (export "recipe_length") (result i32) (global.get $recipe_count))
(func $recipe_address (param $index i32) (result i32)
 (if (i32.ge_u (local.get $index) (global.get $recipe_count))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 (i32.add (i32.const 24576) (i32.mul (local.get $index) (i32.const 16))))
(func (export "recipe_kind") (param $index i32) (result i32) (local $address i32)
 (local.set $address (call $recipe_address (local.get $index)))
 (if (global.get $failure) (then (return (i32.const 0))))
 (i32.load (local.get $address)))
(func (export "recipe_value") (param $index i32) (result i64) (local $address i32)
 (local.set $address (call $recipe_address (local.get $index)))
 (if (global.get $failure) (then (return (i64.const 0))))
 (i64.load offset=8 (local.get $address)))
