;; Source ABI is distinct from the experiment's begin/build/invoke lifecycle.
;; Heap, operand stack and continuations are shared imported objects. Failure is
;; terminal: begin cannot clear it, old host requests are never rolled back.
(func $cleanup_internal (global.set $cp (i32.const 0)))
(func $is_live (param $handle i32) (result i32) (local $address i32)
 (if (i32.or (i32.eqz (local.get $handle)) (i32.gt_u (local.get $handle) (global.get $heap_cursor)))
  (then (return (i32.const 0))))
 (local.set $address (call $linear_address (local.get $handle)))
 (i32.and (i32.eq (i32.load offset=4 (local.get $address)) (local.get $handle))
  (i32.le_u (i32.sub (i32.load (local.get $address)) (i32.const 1)) (i32.const 15))))
(func $boxed_value (param $handle i32) (result i64)
 (if (result i64) (i32.lt_u (call $kind (local.get $handle)) (i32.const 4))
  (then (call $payload (local.get $handle)))
  (else (i64.extend_i32_u (local.get $handle)))))
(func (export "begin")
 (param $allocation i32) (param $recipes i32) (param $depth i32)
 (param $operands i32) (param $continuations i32) (param $step_count i32) (result i32)
 (if (global.get $failure) (then (return (global.get $failure))))
 (if (global.get $cp) (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (if (i32.or (i32.or (i32.gt_u (local.get $allocation) (i32.const 196608))
                     (i32.gt_u (local.get $recipes) (i32.const 256)))
              (i32.or (i32.gt_u (local.get $depth) (i32.const 256))
               (i32.or (i32.gt_u (local.get $operands) (i32.const 2048))
                (i32.or (i32.gt_u (local.get $continuations) (i32.const 4096))
                         (i32.gt_u (local.get $step_count) (i32.const 100000))))))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (global.set $heap_baseline (global.get $heap_cursor))
 (global.set $quota_reason (i32.const 0)) (global.set $phase (i32.const 0))
 (global.set $allocated_total (i64.const 0)) (global.set $released_total (i64.const 0))
 (global.set $allocation_peak (i32.const 0))
 (global.set $operand_peak (i32.const 0)) (global.set $continuation_peak (i32.const 0))
 (global.set $steps (i32.const 0)) (global.set $quote_invocations (i32.const 0))
 (global.set $reflection_steps (i32.const 0))
 (global.set $allocation_limit (local.get $allocation))
 (global.set $recipe_limit (local.get $recipes)) (global.set $depth_limit (local.get $depth))
 (global.set $operand_limit (local.get $operands))
 (global.set $continuation_limit (local.get $continuations))
 (global.set $step_limit (local.get $step_count))
 (if (i32.gt_u (i32.mul (global.get $sp) (i32.const 16)) (local.get $operands))
  (then (call $quota (i32.const 4))))
 (global.get $failure))
(func $op_emit (local $text i32)
 (local.set $text (i32.wrap_i64 (call $pop_kind (i32.const 11))))
 (if (global.get $failure) (then (return)))
 ;; A native host throw also leaves the session poisoned. Successful return is
 ;; the only place this provisional host-call failure may be cleared.
 (global.set $failure (i32.const 5))
 (if (i32.eqz (call $host_emit (call $x (local.get $text)) (call $y (local.get $text))))
  (then (global.set $failure (i32.const 0)))))
(func $op_abort
 (if (global.get $failure) (then (return)))
 (call $fail (i32.const 6))
 (drop (call $host_abort)))
(func (export "push_i64") (param $value i64) (result i32)
 (call $push_i64 (local.get $value)) (global.get $failure))
(func (export "push_bool") (param $value i32) (result i32)
 (if (i32.gt_u (local.get $value) (i32.const 1)) (then (call $fail (i32.const 4))))
 (call $push_bool (local.get $value)) (global.get $failure))
(func (export "push_unit") (result i32)
 (call $push_unit) (global.get $failure))
(func (export "push_program") (param $handle i32) (result i32)
 (if (global.get $failure) (then (return (global.get $failure))))
 (if (i32.eqz (call $is_live (local.get $handle)))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (if (i32.ne (call $kind (local.get $handle)) (i32.const 4))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (call $push_ref (local.get $handle)) (global.get $failure))
;; Host-only companion injection. No exported constructor can forge accepted
;; status: each cell only names indices the deterministic core already accepted,
;; and every push fails closed on a missing or mistyped cell.
(func (export "push_contract")
 (param $index i32) (param $statement i64) (param $claim_kind i32) (param $revision i32)
 (result i32)
 (if (global.get $failure) (then (return (global.get $failure))))
 (if (i32.gt_u (local.get $claim_kind) (i32.const 1))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (call $push_ref (call $new (i32.const 14) (local.get $statement)
  (i32.const 0) (i32.const 0) (i32.const 0)
  (local.get $index) (local.get $claim_kind) (local.get $revision)
  (i32.const 0) (i32.const 0))) (global.get $failure))
(func (export "push_evidence")
 (param $index i32) (param $class i32) (param $ruleset i32) (param $contract i32)
 (result i32)
 (if (global.get $failure) (then (return (global.get $failure))))
 (if (i32.eqz (call $is_live (local.get $contract)))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (if (i32.ne (call $kind (local.get $contract)) (i32.const 14))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (call $push_ref (call $new (i32.const 15) (i64.extend_i32_u (local.get $index))
  (local.get $contract) (i32.const 0) (i32.const 0)
  (local.get $class) (local.get $ruleset) (i32.const 0)
  (i32.const 0) (i32.const 0))) (global.get $failure))
(func (export "push_certified")
 (param $subject i32) (param $contract i32) (param $evidence i32) (param $identity i64)
 (result i32)
 (if (global.get $failure) (then (return (global.get $failure))))
 (if (i32.eqz (call $is_live (local.get $subject)))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (if (i32.ne (call $kind (local.get $subject)) (i32.const 4))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (if (i32.eqz (call $is_live (local.get $contract)))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (if (i32.ne (call $kind (local.get $contract)) (i32.const 14))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (if (i32.eqz (call $is_live (local.get $evidence)))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (if (i32.ne (call $kind (local.get $evidence)) (i32.const 15))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 ;; The evidence cell must reference exactly the supplied contract cell.
 (if (i32.ne (call $a (local.get $evidence)) (local.get $contract))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (call $push_ref (call $new (i32.const 16) (local.get $identity)
  (local.get $subject) (local.get $contract) (local.get $evidence)
  (call $y (local.get $subject)) (call $z (local.get $subject)) (i32.const 0)
  (call $w (local.get $subject)) (call $n (local.get $subject)))) (global.get $failure))
(func (export "certified_subject") (param $handle i32) (result i32)
 (if (global.get $failure) (then (return (i32.const 0))))
 (if (i32.eqz (call $is_live (local.get $handle)))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 (if (i32.ne (call $kind (local.get $handle)) (i32.const 16))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 (call $a (local.get $handle)))
(func (export "stack_length") (result i32) (global.get $sp))
(func (export "stack_kind") (param $index i32) (result i32) (call $slot_kind (local.get $index)))
(func (export "stack_value") (param $index i32) (result i64) (call $slot_value (local.get $index)))
(func (export "cell_kind") (param $h i32) (result i32) (call $kind (local.get $h)))
(func (export "cell_payload") (param $h i32) (result i64) (call $payload (local.get $h)))
(func (export "cell_a") (param $h i32) (result i32) (call $a (local.get $h)))
(func (export "cell_b") (param $h i32) (result i32) (call $b (local.get $h)))
(func (export "cell_c") (param $h i32) (result i32) (call $c (local.get $h)))
(func (export "cell_x") (param $h i32) (result i32) (call $x (local.get $h)))
(func (export "cell_y") (param $h i32) (result i32) (call $y (local.get $h)))
(func (export "cell_z") (param $h i32) (result i32) (call $z (local.get $h)))
(func (export "cell_w") (param $h i32) (result i32) (call $w (local.get $h)))
(func (export "cell_n") (param $h i32) (result i32) (call $n (local.get $h)))
(func (export "observe") (param $index i32) (result i32) (local $tag i32)
 (if (global.get $failure) (then (return (global.get $failure))))
 (local.set $tag (call $slot_kind (local.get $index)))
 (if (i32.eqz (i32.or (i32.eq (local.get $tag) (i32.const 4))
       (i32.or (i32.eq (local.get $tag) (i32.const 10))
        (i32.or (i32.eq (local.get $tag) (i32.const 14))
         (i32.or (i32.eq (local.get $tag) (i32.const 15)) (i32.eq (local.get $tag) (i32.const 16)))))))
  (then (call $fail (i32.const 4)) (return (global.get $failure))))
 (global.set $observed_program (i32.wrap_i64 (call $slot_value (local.get $index))))
 (call $reflect_internal))
