;; Operand slots: tag:i32, padding:i32, payload:i64; no heap allocation for arithmetic.
(func $need (param $count i32) (result i32)
 (if (global.get $failure) (then (return (i32.const 0))))
 (if (i32.lt_u (global.get $sp) (local.get $count))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 (i32.const 1))
(func $slot_kind (param $index i32) (result i32)
 (if (i32.ge_u (local.get $index) (global.get $sp))
  (then (call $fail (i32.const 4)) (return (i32.const 0))))
 (i32.load (i32.mul (local.get $index) (i32.const 16))))
(func $slot_value (param $index i32) (result i64)
 (if (i32.ge_u (local.get $index) (global.get $sp))
  (then (call $fail (i32.const 4)) (return (i64.const 0))))
 (i64.load offset=8 (i32.mul (local.get $index) (i32.const 16))))
(func $push_tag (param $kind i32) (param $value i64) (local $bytes i32) (local $address i32)
 (if (global.get $failure) (then (return)))
 (local.set $bytes (i32.mul (i32.add (global.get $sp) (i32.const 1)) (i32.const 16)))
 (if (i32.gt_u (local.get $bytes) (global.get $operand_limit))
  (then (call $quota (i32.const 4)) (return)))
 (local.set $address (i32.mul (global.get $sp) (i32.const 16)))
 (i32.store (local.get $address) (local.get $kind))
 (i64.store offset=8 (local.get $address) (local.get $value))
 (global.set $sp (i32.add (global.get $sp) (i32.const 1)))
 (if (i32.gt_u (local.get $bytes) (global.get $operand_peak))
  (then (global.set $operand_peak (local.get $bytes)))))
(func $push_i64 (param $value i64) (call $push_tag (i32.const 1) (local.get $value)))
(func $push_bool (param $value i32)
 (call $push_tag (i32.const 2) (i64.extend_i32_u (local.get $value))))
(func $push_unit (call $push_tag (i32.const 3) (i64.const 0)))
(func $push_ref (param $handle i32)
 (if (global.get $failure) (then (return)))
 (call $push_tag (call $kind (local.get $handle)) (i64.extend_i32_u (local.get $handle))))
(func $take (result i64) (local $address i32) (local $value i64)
 (if (i32.eqz (call $need (i32.const 1))) (then (return (i64.const 0))))
 (global.set $sp (i32.sub (global.get $sp) (i32.const 1)))
 (local.set $address (i32.mul (global.get $sp) (i32.const 16)))
 (local.set $value (i64.load offset=8 (local.get $address)))
 (i64.store (local.get $address) (i64.const 0))
 (i64.store offset=8 (local.get $address) (i64.const 0))
 (local.get $value))
(func $pop_kind (param $expected i32) (result i64)
 (if (i32.eqz (call $need (i32.const 1))) (then (return (i64.const 0))))
 (if (i32.ne (call $slot_kind (i32.sub (global.get $sp) (i32.const 1))) (local.get $expected))
  (then (call $fail (i32.const 4)) (return (i64.const 0))))
 (call $take))
(func $pop_box (result i32) (local $tag i32) (local $value i64)
 (if (i32.eqz (call $need (i32.const 1))) (then (return (i32.const 0))))
 (local.set $tag (call $slot_kind (i32.sub (global.get $sp) (i32.const 1))))
 (local.set $value (call $take))
 (if (i32.ge_u (local.get $tag) (i32.const 4)) (then (return (i32.wrap_i64 (local.get $value)))))
 (call $new (local.get $tag) (local.get $value)
  (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)
  (i32.const 0) (i32.const 0) (i32.const 0)))
(func $unbox (param $handle i32) (local $tag i32)
 (if (global.get $failure) (then (return)))
 (local.set $tag (call $kind (local.get $handle)))
 (if (i32.lt_u (local.get $tag) (i32.const 4))
  (then (call $push_tag (local.get $tag) (call $payload (local.get $handle))))
  (else (call $push_ref (local.get $handle)))))

;; Continuation slots occupy [4096,8192): index:i32, environment:i32.
(func $enqueue (param $index i32) (param $environment i32) (local $bytes i32) (local $address i32)
 (if (global.get $failure) (then (return)))
 (local.set $bytes (i32.mul (i32.add (global.get $cp) (i32.const 1)) (i32.const 8)))
 (if (i32.gt_u (local.get $bytes) (global.get $continuation_limit))
  (then (call $quota (i32.const 5)) (return)))
 (local.set $address (i32.add (i32.const 4096) (i32.mul (global.get $cp) (i32.const 8))))
 (i32.store (local.get $address) (local.get $index))
 (i32.store offset=4 (local.get $address) (local.get $environment))
 (global.set $cp (i32.add (global.get $cp) (i32.const 1)))
 (if (i32.gt_u (local.get $bytes) (global.get $continuation_peak))
  (then (global.set $continuation_peak (local.get $bytes)))))
(func $enqueue_program (param $program i32)
 (if (global.get $failure) (then (return)))
 (if (i32.ne (call $kind (local.get $program)) (i32.const 4))
  (then (call $fail (i32.const 4)) (return)))
 (call $enqueue (call $x (local.get $program)) (local.get $program)))
(func $dispatch (local $index i32) (local $environment i32) (local $address i32)
 (block $done (loop $next
  (br_if $done (i32.or (global.get $failure) (i32.eqz (global.get $cp))))
  (if (i32.ge_u (global.get $steps) (global.get $step_limit))
   (then (call $quota (i32.const 6)) (br $done)))
  (global.set $cp (i32.sub (global.get $cp) (i32.const 1)))
  (local.set $address (i32.add (i32.const 4096) (i32.mul (global.get $cp) (i32.const 8))))
  (local.set $index (i32.load (local.get $address)))
  (local.set $environment (i32.load offset=4 (local.get $address)))
  (i64.store (local.get $address) (i64.const 0))
  (global.set $steps (i32.add (global.get $steps) (i32.const 1)))
  (call_indirect (type $entry) (local.get $environment) (local.get $index))
  (br $next))))
