#!/usr/bin/env bash
# M2 proof-required gate (change m2-checker-feasibility, task 4.5).
#
# Positive baseline: every check below must pass on the repository's proofs/m2
# tree. Refusal controls: verification/m2-proof-gate-refusals.sh runs this gate
# against four mutated scratch copies; each mutation must fail hard.
#
#   PRF-MISSING  a required theorem deleted            -> REQUIRED-THEOREMS
#   PRF-HOLE     a `sorry` in any proof source         -> NO-SORRY (and
#                REQUIRED-THEOREMS: sorryAx is a forbidden axiom)
#   PRF-SUBJECT  refinement restated about a hand-     -> REFINEMENT-SUBJECT
#                written copy, not the generated       (import binding) and
#                NobleKernel module                    REQUIRED-THEOREMS
#                                                     (semantic subject
#                                                     binding)
#   unexplained  an external model left as a template  -> EXTERNAL-MODELS
#   external     axiom, or its implementation deleted  (axiom scan) or
#                so the generated module breaks        BUILD
#
# Usage (from any directory; the pinned Lean must be first on PATH):
#
#   PATH=/nix/store/hbxwgcbpkyqllqzq7cidhnvhgb60jb9q-noble-lean-release-4.31.0/bin:$PATH \
#     verification/m2-proof-gate.sh [PROOF_ROOT]
#
# PROOF_ROOT defaults to the repository's proofs/m2 and may be overridden with
# the first argument or M2_PROOF_ROOT (the refusal harness uses this to run
# mutated scratch copies). The root must carry the lake package cache
# (.lake/packages, populated once by `lake update` or the extraction toolrun);
# everything else is checked in. Exit 0 = all checks pass.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROOF_ROOT="${M2_PROOF_ROOT:-$REPO/proofs/m2}"
if [ $# -ge 1 ]; then PROOF_ROOT="$1"; fi
PROOF_ROOT="$(cd "$PROOF_ROOT" 2>/dev/null && pwd)" || {
  echo "[m2-gate] FAIL SETUP: proof root not found: $1" >&2; exit 1; }
[ -f "$PROOF_ROOT/lakefile.toml" ] || {
  echo "[m2-gate] FAIL SETUP: $PROOF_ROOT has no lakefile.toml" >&2; exit 1; }

GATE_A="$PROOF_ROOT/.m2-gate-a.lean"
GATE_B="$PROOF_ROOT/.m2-gate-b.lean"
cleanup() { rm -f "$GATE_A" "$GATE_B"; }
trap cleanup EXIT

fail() { echo "[m2-gate] FAIL $1: $2" >&2; exit 1; }
pass() { echo "[m2-gate] PASS $1"; }

# G0 TOOLCHAIN: the proof tree is bound to the pinned Lean revision.
lean --version 2>/dev/null | grep -q 'version 4\.31\.0' \
  || fail TOOLCHAIN "lean on PATH is not the pinned 4.31.0 release: $(lean --version 2>&1)"
pass "TOOLCHAIN (lean 4.31.0)"

# G1 BUILD: the reference root, the refinement module (not imported by the
# root module), and the generated kernel all compile.
build_log="$(cd "$PROOF_ROOT" && lake build NobleM2 NobleM2.Refinement NobleKernel 2>&1)"
build_rc=$?
if [ "$build_rc" -ne 0 ]; then
  printf '%s\n' "$build_log" | tail -25 >&2
  fail BUILD "lake build exited $build_rc (proof-required claims need a building target)"
fi
pass "BUILD (lake build NobleM2 NobleM2.Refinement NobleKernel)"

# G2 NO-SORRY: no proof hole in any checked-in proof source.
sorry_hits="$(grep -rnw --include='*.lean' --exclude-dir=.lake sorry "$PROOF_ROOT" || true)"
[ -z "$sorry_hits" ] || {
  printf '%s\n' "$sorry_hits" >&2
  fail NO-SORRY "proof sources contain 'sorry'"
}
pass "NO-SORRY (no 'sorry' outside .lake)"

# G3 GENERATED-KERNEL: the Aeneas-generated module is present, non-empty,
# imports its function half, and defines the extracted checker.
gen_header="$PROOF_ROOT/NobleKernel.lean"
gen_funs="$PROOF_ROOT/NobleKernel/Funs.lean"
[ -s "$gen_header" ] || fail GENERATED-KERNEL "missing or empty $gen_header"
grep -q 'AUTOMATICALLY GENERATED BY AENEAS' "$gen_header" \
  || fail GENERATED-KERNEL "$gen_header is not the generated library entry point"
grep -qx 'import NobleKernel.Funs' "$gen_header" \
  || fail GENERATED-KERNEL "$gen_header does not import NobleKernel.Funs"
[ -s "$gen_funs" ] || fail GENERATED-KERNEL "missing or empty $gen_funs"
grep -q '^def acceptance.check' "$gen_funs" \
  || fail GENERATED-KERNEL "generated Funs.lean does not define acceptance.check (missing function)"
pass "GENERATED-KERNEL (Aeneas entry point, Funs.lean, acceptance.check)"

# G4 REFINEMENT-SUBJECT: the refinement and the embedding import the
# generated module itself (`import NobleKernel` as a whole line), so the
# theorems cannot silently bind a same-named substitute module.
for mod in NobleM2/Refinement.lean NobleM2/Embed.lean; do
  grep -qx 'import NobleKernel' "$PROOF_ROOT/$mod" \
    || fail REFINEMENT-SUBJECT "$mod does not import the generated NobleKernel module (substituted subject)"
done
pass "REFINEMENT-SUBJECT (Refinement.lean and Embed.lean import NobleKernel)"

# G5 REQUIRED-THEOREMS: every milestone theorem exists, depends only on the
# permitted axioms, and — for the refinement family — is stated about the
# generated checker constant (semantic subject binding, so a rewrite that
# keeps the import but calls a hand-written copy still rejects).
#
# Axiom policy: the reference-model theorems and the generated checker may
# use only Lean's trifecta {propext, Classical.choice, Quot.sound}; the
# evaluation-closed theorems may additionally use the per-declaration
# native_decide axioms emitted by Lean 4.31 (name suffix
# "._native.native_decide.ax_1_1"). sorryAx and anything else reject.
cat > "$GATE_A" <<'LEAN_A'
import Lean.Elab.Command
import NobleM2

open Lean in
run_cmd do
  let strict : List Name := [``propext, ``Classical.choice, ``Quot.sound]
  let evalOk (n : Name) : Bool :=
    strict.contains n || n.toString.endsWith "._native.native_decide.ax_1_1"
  let okAxiom (isStrict : Bool) (a : Name) : Bool :=
    if isStrict then strict.contains a else evalOk a
  let strictRequired : List Name :=
    [``NobleM2.applyScheme_ok,
     ``NobleM2.check_soundness,
     ``NobleM2.check_total,
     ``NobleM2.foldBody_work_bounded]
  let evalRequired : List Name :=
    [``NobleM2.coverage_positive,
     ``NobleM2.Coverage.accepted,
     ``NobleM2.Coverage.derives,
     ``NobleM2.Regression.ce_accepted,
     ``NobleM2.Regression.ce_derives]
  let required :=
    strictRequired.map (fun n => (n, true)) ++ evalRequired.map (fun n => (n, false))
  for (n, isStrict) in required do
    match (← getEnv).find? n with
    | none => logError m!"m2-gate: required theorem missing: {n}"
    | some _ =>
      let axs ← Lean.collectAxioms n
      logInfo m!"m2-gate: axioms {n} {axs}"
      let bad := axs.filter (fun a => !(okAxiom isStrict a))
      if !bad.isEmpty then
        logError m!"m2-gate: forbidden axioms on {n}: {bad}"
LEAN_A
cat > "$GATE_B" <<'LEAN_B'
import Lean.Elab.Command
import NobleM2.Refinement

open Lean in
run_cmd do
  let gen := ``noble_kernel.acceptance.check
  let strict : List Name := [``propext, ``Classical.choice, ``Quot.sound]
  let evalOk (n : Name) : Bool :=
    strict.contains n || n.toString.endsWith "._native.native_decide.ax_1_1"
  let okAxiom (isStrict : Bool) (a : Name) : Bool :=
    if isStrict then strict.contains a else evalOk a
  let strictRequired : List Name :=
    [``noble_kernel.acceptance.check,
     ``NobleM2.Refinement.accepted_via_refinement]
  let evalRequired : List Name :=
    [``NobleM2.Refinement.refinement_sequence_and_literals_accept_arithmetic,
     ``NobleM2.Refinement.refinement_quotation_construction_checks_body_and_runs,
     ``NobleM2.Refinement.refinement_limits_nodes_exact,
     ``NobleM2.Refinement.refinement_limits_nodes_over,
     ``NobleM2.Refinement.refinement_limits_depth_deep,
     ``NobleM2.Refinement.refinement_limits_depth_shallow,
     ``NobleM2.Refinement.refinement_limits_work_eight,
     ``NobleM2.Refinement.refinement_limits_work_four,
     ``NobleM2.Refinement.refinement_hidden_emit_rejects_against_empty_bound,
     ``NobleM2.Refinement.refinement_diagnostics_report_order,
     ``NobleM2.Refinement.refinement_diagnostics_truncation,
     ``NobleM2.Refinement.refinement_resource_eligibility_rejects_duplication]
  let required :=
    strictRequired.map (fun n => (n, true)) ++ evalRequired.map (fun n => (n, false))
  for (n, isStrict) in required do
    match (← getEnv).find? n with
    | none => logError m!"m2-gate: required theorem missing: {n}"
    | some ci =>
      let axs ← Lean.collectAxioms n
      logInfo m!"m2-gate: axioms {n} {axs}"
      let bad := axs.filter (fun a => !(okAxiom isStrict a))
      if !bad.isEmpty then
        logError m!"m2-gate: forbidden axioms on {n}: {bad}"
      if n != gen then
        if ci.type.getUsedConstants.contains gen then
          logInfo m!"m2-gate: subject {n} binds {gen}"
        else
          logError m!"m2-gate: substituted subject: {n} is not stated about the generated {gen}"
LEAN_B
axioms_log="$(cd "$PROOF_ROOT" && lake env lean .m2-gate-a.lean 2>&1)"
axioms_rc=$?
if [ "$axioms_rc" -ne 0 ]; then
  printf '%s\n' "$axioms_log" | tail -30 >&2
  fail REQUIRED-THEOREMS "reference-model theorem inventory check exited $axioms_rc"
fi
printf '%s\n' "$axioms_log"
subject_log="$(cd "$PROOF_ROOT" && lake env lean .m2-gate-b.lean 2>&1)"
subject_rc=$?
if [ "$subject_rc" -ne 0 ]; then
  printf '%s\n' "$subject_log" | tail -30 >&2
  fail REQUIRED-THEOREMS "refinement theorem inventory / subject binding exited $subject_rc"
fi
printf '%s\n' "$subject_log"
pass "REQUIRED-THEOREMS (inventory, axiom policy, subject binding)"

# G6 EXTERNAL-MODELS: every external function routed by Aeneas to the
# split-file templates is implemented as a definition; the template's axiom
# form (an unexplained external model) rejects.
axiom_hits="$(grep -nE '^[[:space:]]*axiom[[:space:]]' \
  "$PROOF_ROOT/NobleKernel/FunsExternal.lean" "$PROOF_ROOT/NobleKernel/TypesExternal.lean" || true)"
[ -z "$axiom_hits" ] || {
  printf '%s\n' "$axiom_hits" >&2
  fail EXTERNAL-MODELS "external model left as a template axiom"
}
pass "EXTERNAL-MODELS (no template axioms in FunsExternal/TypesExternal)"

echo "[m2-gate] PASS (all checks) — proof root: $PROOF_ROOT"
exit 0
