;; Private Declared-Modules-v1 values reuse managed sum cell tags with a nonzero
;; nominal marker. Structural sums always have w=0. The exact resolved type
;; identity is stored in x/y/z; no string alias or adapter controls it.
(func $nominal_cell (param $handle i32) (param $module i64) (param $ordinal i32)
 (param $marker i32) (result i32)
 (if (i32.eqz (call $is_live (local.get $handle))) (then (return (i32.const 0))))
 (if (i32.or
   (i32.ne (call $x (local.get $handle)) (i32.wrap_i64 (local.get $module)))
   (i32.or
    (i32.ne (call $y (local.get $handle))
     (i32.wrap_i64 (i64.shr_u (local.get $module) (i64.const 32))))
    (i32.or (i32.ne (call $z (local.get $handle)) (local.get $ordinal))
     (i32.ne (call $w (local.get $handle)) (local.get $marker)))))
  (then (return (i32.const 0))))
 (i32.const 1))
(func $op_nominal_construct (param $module i64) (param $ordinal i32)
 (param $arm i32) (local $value i32) (local $kind i32) (local $marker i32)
 (local.set $value (call $pop_box))
 (if (global.get $failure) (then (return)))
 (local.set $kind (if (result i32) (i32.eq (local.get $arm) (i32.const 2))
  (then (i32.const 13)) (else (i32.const 12))))
 (local.set $marker (if (result i32) (i32.eqz (local.get $arm))
  (then (i32.const 1)) (else (i32.const 2))))
 (call $push_ref (call $new (local.get $kind) (i64.const 0) (local.get $value)
  (i32.const 0) (i32.const 0)
  (i32.wrap_i64 (local.get $module))
  (i32.wrap_i64 (i64.shr_u (local.get $module) (i64.const 32)))
  (local.get $ordinal) (local.get $marker) (i32.const 0))))
(func $op_nominal_into (param $module i64) (param $ordinal i32)
 (local $handle i32)
 (if (i32.eqz (call $need (i32.const 1))) (then (return)))
 (if (i32.ne (call $slot_kind (i32.sub (global.get $sp) (i32.const 1))) (i32.const 12))
  (then (call $fail (i32.const 4)) (return)))
 (local.set $handle (i32.wrap_i64 (call $slot_value (i32.sub (global.get $sp) (i32.const 1)))))
 (if (i32.eqz (call $nominal_cell (local.get $handle) (local.get $module)
      (local.get $ordinal) (i32.const 1)))
  (then (call $fail (i32.const 4)) (return)))
 (drop (call $take))
 (call $unbox (call $a (local.get $handle))))
(func $op_nominal_match (param $module i64) (param $ordinal i32)
 (local $right i32) (local $left i32) (local $value i32) (local $tag i32)
 (local.set $right (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (local.set $left (i32.wrap_i64 (call $pop_kind (i32.const 4))))
 (if (i32.eqz (call $need (i32.const 1))) (then (return)))
 (local.set $tag (call $slot_kind (i32.sub (global.get $sp) (i32.const 1))))
 (if (i32.and (i32.ne (local.get $tag) (i32.const 12))
              (i32.ne (local.get $tag) (i32.const 13)))
  (then (call $fail (i32.const 4)) (return)))
 (local.set $value (i32.wrap_i64 (call $slot_value (i32.sub (global.get $sp) (i32.const 1)))))
 (if (i32.eqz (call $nominal_cell (local.get $value) (local.get $module)
      (local.get $ordinal) (i32.const 2)))
  (then (call $fail (i32.const 4)) (return)))
 (drop (call $take))
 (call $unbox (call $a (local.get $value)))
 (if (i32.eq (local.get $tag) (i32.const 12))
  (then (call $enqueue_program (local.get $left)))
  (else (call $enqueue_program (local.get $right)))))
