(component
  (import "wasi:clocks/monotonic-clock@0.3.0-rc-2025-09-16" (instance $clock
    (export "wait-for" (func async (param "how-long" u64)))))
  (core module $memory (memory (export "memory") 1 1))
  (core instance $m (instantiate $memory))
  (alias export $clock "wait-for" (func $wait-for))
  (core func $wait-for-lowered (canon lower (func $wait-for) async))
  (core func $new (canon waitable-set.new))
  (core func $join (canon waitable.join))
  (core func $wait (canon waitable-set.wait (memory $m "memory")))
  (core func $drop (canon waitable-set.drop))
  (core func $subdrop (canon subtask.drop))
  (core func $return (canon task.return))
  (core module $guest
    (import "" "memory" (memory 1 1))
    (import "" "wait-for" (func $clock (param i64) (result i32)))
    (import "" "new" (func $new (result i32)))
    (import "" "join" (func $join (param i32 i32)))
    (import "" "wait" (func $wait (param i32 i32) (result i32)))
    (import "" "drop" (func $drop (param i32)))
    (import "" "subdrop" (func $subdrop (param i32)))
    (import "" "return" (func $return))
    (func (export "run") (local $packed i32) (local $handle i32) (local $set i32) (local $n i32)
      (local.set $packed (call $clock (i64.const 1000000)))
      (if (i32.ne (i32.and (local.get $packed) (i32.const 15)) (i32.const 2)) (then
        (local.set $handle (i32.shr_u (local.get $packed) (i32.const 4)))
        (local.set $set (call $new))
        (call $join (local.get $handle) (local.get $set))
        (loop $again
          (if (i32.ge_u (local.get $n) (i32.const 2)) (then unreachable))
          (local.set $n (i32.add (local.get $n) (i32.const 1)))
          (if (i32.ne (call $wait (local.get $set) (i32.const 0)) (i32.const 1)) (then unreachable))
          (if (i32.ne (i32.load (i32.const 0)) (local.get $handle)) (then unreachable))
          (br_if $again (i32.ne (i32.load (i32.const 4)) (i32.const 2))))
        (call $join (local.get $handle) (i32.const 0))
        (call $subdrop (local.get $handle))
        (call $drop (local.get $set))))
      (call $return)))
  (core instance $g (instantiate $guest (with "" (instance
    (export "memory" (memory $m "memory"))
    (export "wait-for" (func $wait-for-lowered)) (export "new" (func $new))
    (export "join" (func $join)) (export "wait" (func $wait)) (export "drop" (func $drop))
    (export "subdrop" (func $subdrop)) (export "return" (func $return))))))
  (func (export "run") async (canon lift (core func $g "run") async)))
