-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [noble_kernel]: external functions.
-- This is the template file "FunsExternal_Template.lean" generated by Aeneas
-- (with `-split-files`), renamed to "FunsExternal.lean", in which we replaced
-- every axiom with a faithful, total Lean implementation.
--
-- Every definition below mirrors the Rust std semantics on the reachable
-- domain:
--   * functions which are total in Rust are total here;
--   * fallible conversions return `.Ok`/`.Err` like `core::convert::TryFrom`;
--   * the formatting helpers follow the Aeneas model of the formatting
--     machinery (`core.fmt.Formatter` is an opaque type and `write_str`/
--     `write_fmt` return the formatter unchanged), so a formatting step has
--     no observable effect;
--   * `types.impls.clone_stack`/`shapes.impls.clone_parts` are the crate's
--     `#[charon::opaque]` copy loops. Their Rust bodies deep-copy the slice
--     elements one at a time; in the functional model the (terminating)
--     extracted `Clone` impls compute values equal to their inputs, so
--     returning the input list is the same observable value. Implementing
--     them here (instead of removing `#[charon::opaque]` in the Rust crate)
--     keeps the extraction reproducible: Aeneas cannot functionalize those
--     loops inside the trait-instance mutual block, which is why the
--     attributes exist.
--
-- Note: the declarations live in the `noble_kernel` namespace (like they did
-- in the previous monolithic extraction) so that all the fully qualified
-- names (e.g. `noble_kernel.alloc.vec.Vec.pop`) are unchanged.
import Aeneas
import NobleKernel.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace noble_kernel

/-! ## core::cmp -/

/-- [core::cmp::impls::{impl core::cmp::PartialEq<bool> for bool}::ne]:
    `ne` is the negation of `eq`. -/
@[rust_fun "core::cmp::impls::{core::cmp::PartialEq<bool, bool>}::ne"]
def Bool.Insts.CoreCmpPartialEqBool.ne (x y : Bool) : Result Bool := do
  let b ← core.cmp.impls.PartialEqBool.eq x y
  ok (!b)

/-! ## core::convert -/

/-- [core::convert::num::ptr_try_from_impls::{impl
    core::convert::TryFrom<u32, core::num::error::TryFromIntError> for usize}::try_from]:
    `u32` always fits in `usize` on the extraction target (64-bit), and the
    guarded `tryFromUScalar` gives exactly the platform-independent std
    semantics (`Ok` on fit, `Err TryFromIntError` otherwise). -/
@[rust_fun
  "core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<usize, u32, core::num::error::TryFromIntError>}::try_from"]
def Usize.Insts.CoreConvertTryFromU32TryFromIntError.try_from (x : U32) :
  Result (core.result.Result Usize core.num.error.TryFromIntError) :=
  core.num.tryFromUScalar .Usize x

/-- [core::convert::num::ptr_try_from_impls::{impl
    core::convert::TryFrom<u64, core::num::error::TryFromIntError> for usize}::try_from]:
    `Ok` when the value fits, `Err TryFromIntError` when it does not. -/
@[rust_fun
  "core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<u64, usize, core::num::error::TryFromIntError>}::try_from"]
def U64.Insts.CoreConvertTryFromUsizeTryFromIntError.try_from (x : Usize) :
  Result (core.result.Result U64 core.num.error.TryFromIntError) :=
  core.num.tryFromUScalar .U64 x

/-! ## core::fmt -/

/-- The formatting machinery is a pass-through in the Aeneas model: a
    successful write returns `Ok (())` and the formatter unchanged. -/
@[rust_fun
  "core::fmt::{core::fmt::Formatter<'a>}::debug_c_like_enum_write_str"]
def core.fmt.Formatter.debug_c_like_enum_write_str (f : core.fmt.Formatter)
  (_ : Str) (_ : Slice Usize) (_ : Usize) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter) :=
  ok (.Ok (), f)

/-- [core::option::{impl core::fmt::Debug for core::option::Option<T>}::fmt]:
    `None` writes `"None"`; `Some(v)` writes `"Some("`, formats `v` and
    writes `")"`, propagating a formatting error out of `v` like the `?`
    in the std expansion does. The written text itself is not observable in
    the formatter model. -/
@[rust_fun "core::option::{core::fmt::Debug<core::option::Option<@T>>}::fmt"]
def core.option.Option.Insts.CoreFmtDebug.fmt {T : Type} (fmtDebugInst :
  core.fmt.Debug T) :
  Option T → core.fmt.Formatter →
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter) :=
  fun x f =>
    match x with
    | none => core.fmt.Formatter.write_str f (toStr "None")
    | some v => do
      let (r, f1) ← core.fmt.Formatter.write_str f (toStr "Some(")
      match r with
      | .Ok () =>
        let (r1, f2) ← fmtDebugInst.fmt v f1
        match r1 with
        | .Ok () => core.fmt.Formatter.write_str f2 (toStr ")")
        | .Err e => ok (.Err e, f2)
      | .Err e => ok (.Err e, f1)

/-! ## core::num -/

/-- [core::num::{usize}::saturating_mul]: the product, clamped to
    `usize::MAX`. Mirrors `UScalar.saturating_add` in the standard library
    model (Lean `Nat` does not overflow, so clamping the exact product is the
    saturating semantics). -/
@[rust_fun "core::num::{usize}::saturating_mul"]
def core.num.Usize.saturating_mul (x y : Usize) : Result Usize :=
  ok ⟨ BitVec.ofNat _ (Min.min (UScalar.max UScalarTy.Usize) (x.val * y.val)) ⟩

/-! ## core::option -/

/-- [core::option::{core::option::Option<T>}::map]:
    `None` stays `None`, `Some(v)` becomes `Some(f(v))`. -/
@[rust_fun "core::option::{core::option::Option<@T>}::map"]
def core.option.Option.map
  {T : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  Option T → F → Result (Option U) :=
  fun x f =>
    match x with
    | none => ok none
    | some v => do
      let u ← opsfunctionFnOnceFTupleTUInst.call_once f v
      ok (some u)

/-- [core::option::{core::option::Option<&'_0 T>}::copied]:
    copying through a share is the identity in the extracted model
    (`&T` is represented by `T` itself and `T : Copy`). -/
@[rust_fun "core::option::{core::option::Option<&'0 @T>}::copied"]
def core.option.OptionShared0T.copied
  {T : Type} (markerCopyInst : core.marker.Copy T) :
  Option T → Result (Option T) :=
  fun x => ok x

/-- [core::option::{impl core::clone::Clone for core::option::Option<T>}::clone]:
    `None` clones to `None`, `Some(v)` clones `v`. -/
@[rust_fun "core::option::{impl core::clone::Clone for core::option::Option<@T>}::clone"]
def core.option.Option.Insts.CoreCloneClone.clone
  {T : Type} (cloneCloneInst : core.clone.Clone T) :
  Option T → Result (Option T) :=
  fun x =>
    match x with
    | none => ok none
    | some v => do
      let v1 ← cloneCloneInst.clone v
      ok (some v1)

/-! ## core::result -/

/-- [core::result::{core::result::Result<T, E>}::is_err]. -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::is_err"]
def core.result.Result.is_err
  {T : Type} {E : Type} : core.result.Result T E → Result Bool :=
  fun r =>
    match r with
    -- `pure`, not `ok`: inside this namespace a bare `ok` resolves to the
    -- sibling `core.result.Result.ok` defined below.
    | .Ok _ => pure false
    | .Err _ => pure true

/-- [core::result::{core::result::Result<T, E>}::ok]. -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::ok"]
def core.result.Result.ok
  {T : Type} {E : Type} : core.result.Result T E → Result (Option T) :=
  fun r =>
    match r with
    | .Ok v => pure (some v)
    | .Err _ => pure none

/-- [core::result::{core::result::Result<T, E>}::unwrap_or]. -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::unwrap_or"]
def core.result.Result.unwrap_or
  {T : Type} {E : Type} : core.result.Result T E → T → Result T :=
  fun r default =>
    match r with
    | .Ok v => pure v
    | .Err _ => pure default

/-! ## alloc::vec -/

/-- [alloc::vec::{alloc::vec::Vec<T>}::truncate]:
    keeps the first `min(len, self.len())` elements. -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::truncate"]
def alloc.vec.Vec.truncate
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Usize → Result (alloc.vec.Vec T) :=
  fun v len =>
    ok (.from (List.take len.val v.val)
      (by
        have h2 := v.property
        simp only [List.length_take]
        omega))

/-- [alloc::vec::{alloc::vec::Vec<T>}::as_slice]. -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::as_slice"]
def alloc.vec.Vec.as_slice
  {T : Type} (A : Type) : alloc.vec.Vec T → Result (Slice T) :=
  fun v => ok v.slice

/-- [alloc::vec::{alloc::vec::Vec<T>}::pop]:
    `None` when empty, else the last element and the vector without it. -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::pop"]
def alloc.vec.Vec.pop
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Result ((Option T) × (alloc.vec.Vec T)) :=
  fun v =>
    match v.val with
    | [] => ok (none, v)
    | _ =>
      ok (v.val.getLast?,
        .from (List.take (v.val.length - 1) v.val)
          (by
            have h2 := v.property
            simp only [List.length_take]
            omega))

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]. -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
def alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool :=
  fun v => ok (v.val.isEmpty)

/- [alloc::vec::{impl core::iter::traits::collect::Extend<T> for
    alloc::vec::Vec<T>}::extend]:
    drains the iterator and appends every item, failing only if the
    concatenated length would exceed `usize::MAX` (the capacity-overflow
    abort in Rust). The `set_option` below disables the Aeneas custom `do`
    elaborator for this one definition: it does not support
    `if h : ... then ... else ...` (a decidable dependent if) as a `do`
    element, while Lean's standard `do` notation does. -/
set_option Aeneas.customDoElab false in
@[rust_fun
  "alloc::vec::{core::iter::traits::collect::Extend<alloc::vec::Vec<@T>, @T>}::extend"]
def alloc.vec.Vec.Insts.CoreIterTraitsCollectExtend.extend
  {T : Type} (A : Type) {I : Type} {Clause0_IntoIter : Type}
  (coreitertraitscollectIntoIteratorInst :
  core.iter.traits.collect.IntoIterator I T Clause0_IntoIter) :
  alloc.vec.Vec T → I → Result (alloc.vec.Vec T) :=
  fun v input => do
    let iter ← coreitertraitscollectIntoIteratorInst.into_iter input
    let l ← alloc.vec.FromIteratorVec.iterToList
      coreitertraitscollectIntoIteratorInst.iteratorInst iter []
    if h : (v.val ++ l).length ≤ Usize.max then ok (.from _ h)
    else fail .panic

/-! ## noble_kernel opaque helpers

These are the crate's `#[charon::opaque]` copy loops (see the header comment).
They are routed here by `-split-files`, so option (a) of the feasibility plan
applies: implement them in this file; the Rust crate is left untouched. -/

/-- [noble_kernel::types::impls::clone_stack]:
    deep-copy one type stack. The loop clones the slice elements one at a
    time; since the extracted `Clone` impl for `Ty` computes a value equal to
    its input, the copied vector is the vector of the same elements, which
    `Vec.from` builds directly from the slice contents. -/
def types.impls.clone_stack
  : Slice types.Ty → Result (alloc.vec.Vec types.Ty) :=
  fun s => ok (.from s.val s.property)

/-- [noble_kernel::shapes::impls::clone_parts]:
    deep-copy one pattern stack; same reasoning as `clone_stack`. -/
def shapes.impls.clone_parts
  : Slice shapes.Pattern → Result (alloc.vec.Vec shapes.Pattern) :=
  fun s => ok (.from s.val s.property)

/-- [noble_kernel::shapes::impls::debug_slots]:
    formats a slice of `EffectSlot`. The written text is not observable in
    the formatter model (see above), so the body returns a successful,
    formatter-preserving step. -/
def shapes.impls.debug_slots
  :
  Slice shapes.EffectSlot → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter) :=
  fun _ f => ok (.Ok (), f)

/-- [noble_kernel::shapes::impls::debug_parts]:
    formats a slice of `Pattern`; same formatter-model reasoning. -/
def shapes.impls.debug_parts
  :
  Slice shapes.Pattern → core.fmt.Formatter → Result ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter) :=
  fun _ f => ok (.Ok (), f)

/-- [noble_kernel::types::impls::debug_stack]:
    formats a slice of `Ty`; same formatter-model reasoning. -/
def types.impls.debug_stack
  :
  Slice types.Ty → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter) :=
  fun _ f => ok (.Ok (), f)

end noble_kernel
