-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [noble_kernel]: external types.
-- This is the template file "TypesExternal_Template.lean" generated by Aeneas
-- (with `-split-files`), renamed to "TypesExternal.lean", in which we replaced
-- the axiom with a definition.
--
-- `core::mem::maybe_uninit::MaybeUninit` is not referenced by any of the
-- extracted type or function definitions of this crate (the extraction of the
-- reachable code never mentions it); we still give it a faithful model: a
-- value which is either uninitialized or holds a `T`.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace noble_kernel

/-- [core::mem::maybe_uninit::MaybeUninit]:
    Source: '/rustc/library/core/src/mem/maybe_uninit.rs', lines 355:0-355:24
    Name pattern: [core::mem::maybe_uninit::MaybeUninit]
    Visibility: public -/
@[rust_type "core::mem::maybe_uninit::MaybeUninit"]
def core.mem.maybe_uninit.MaybeUninit (T : Type) : Type := Option T

end noble_kernel
