-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [noble_contracts]: type definitions
import Aeneas
import NobleContractImpl.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace noble_contracts

/-- Trait declaration: [core::str::traits::FromStr]
    Source: '/rustc/library/core/src/str/traits.rs', lines 868:0-868:30
    Name pattern: [core::str::traits::FromStr]
    Visibility: public -/
@[rust_trait "core::str::traits::FromStr"]
structure core.str.traits.FromStr (Self : Type) (Self_Err : Type) where
  from_str : Str → Result (core.result.Result Self Self_Err)

/-- [noble_kernel::untrusted::NodeId]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 18:0-18:17
    Name pattern: [noble_kernel::untrusted::NodeId]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::untrusted::NodeId"]
def noble_kernel.untrusted.NodeId := Std.U32

/-- [noble_kernel::types::ResourceKind]
    Source: 'crates/noble-kernel/src/types.rs', lines 15:0-15:23
    Name pattern: [noble_kernel::types::ResourceKind]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::types::ResourceKind"]
def noble_kernel.types.ResourceKind := Std.U32

/-- [noble_kernel::types::Ty]
    Source: 'crates/noble-kernel/src/types.rs', lines 157:0-157:11
    Name pattern: [noble_kernel::types::Ty]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::types::Ty"]
inductive noble_kernel.types.Ty where
| UnitType : noble_kernel.types.Ty
| BoolType : noble_kernel.types.Ty
| I64Type : noble_kernel.types.Ty
| TextType : noble_kernel.types.Ty
| SyntaxType : noble_kernel.types.Ty
| ContractType : noble_kernel.types.Ty
| EvidenceType : noble_kernel.types.Ty
| CertifiedType : noble_kernel.types.Ty
| PairType :
  noble_kernel.types.Ty →
  noble_kernel.types.Ty →
  noble_kernel.types.Ty
| SumType :
  noble_kernel.types.Ty →
  noble_kernel.types.Ty →
  noble_kernel.types.Ty
| ListType : noble_kernel.types.Ty → noble_kernel.types.Ty
| ProgramType :
  alloc.vec.Vec noble_kernel.types.Ty →
  alloc.vec.Vec noble_kernel.types.Ty →
  noble_kernel.types.EffSet →
  noble_kernel.types.Ty
| ResourceType : noble_kernel.types.ResourceKind → noble_kernel.types.Ty

/-- [noble_kernel::types::EffId]
    Source: 'crates/noble-kernel/src/types.rs', lines 26:0-26:16
    Name pattern: [noble_kernel::types::EffId]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::types::EffId"]
def noble_kernel.types.EffId := Std.U32

/-- [noble_kernel::contracts::Definition]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 11:0-11:21
    Name pattern: [noble_kernel::contracts::Definition]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::contracts::Definition"]
def noble_kernel.contracts.Definition := Std.U32

/-- [noble_kernel::untrusted::Constraint]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 206:0-206:19
    Name pattern: [noble_kernel::untrusted::Constraint]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Constraint"]
inductive noble_kernel.untrusted.Constraint where
| StackJoin : noble_kernel.untrusted.Constraint
| StackOrder : noble_kernel.untrusted.Constraint
| EffectInclusion :
  noble_kernel.types.EffId →
  noble_kernel.untrusted.Constraint
| Eligibility : noble_kernel.types.Ty → noble_kernel.untrusted.Constraint
| UnknownEffect :
  noble_kernel.types.EffId →
  noble_kernel.untrusted.Constraint
| InstantiationKind : noble_kernel.untrusted.Constraint
| InstantiationArity : noble_kernel.untrusted.Constraint
| MalformedReference :
  noble_kernel.untrusted.NodeId →
  noble_kernel.untrusted.Constraint
| UnknownDefinition :
  noble_kernel.contracts.Definition →
  noble_kernel.untrusted.Constraint
| CyclicWitness : noble_kernel.untrusted.Constraint

/-- [noble_kernel::untrusted::Diagnostic]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 232:0-232:21
    Name pattern: [noble_kernel::untrusted::Diagnostic]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Diagnostic"]
structure noble_kernel.untrusted.Diagnostic where
  node : Option noble_kernel.untrusted.NodeId
  «def» : Option noble_kernel.contracts.Definition
  expected : alloc.vec.Vec noble_kernel.types.Ty
  actual : alloc.vec.Vec noble_kernel.types.Ty
  constraint : noble_kernel.untrusted.Constraint
  provenance_available : Bool
  truncated : Bool

/-- [noble_kernel::contracts::SchemaId]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 21:0-21:19
    Name pattern: [noble_kernel::contracts::SchemaId]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::contracts::SchemaId"]
def noble_kernel.contracts.SchemaId := Std.U32

/-- [noble_kernel::untrusted::UnsupportedKind]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 187:0-187:24
    Name pattern: [noble_kernel::untrusted::UnsupportedKind]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::UnsupportedKind"]
inductive noble_kernel.untrusted.UnsupportedKind where
| FormatRevision : noble_kernel.untrusted.UnsupportedKind
| NodeForm : noble_kernel.untrusted.UnsupportedKind
| SchemeForm : noble_kernel.untrusted.UnsupportedKind
| RecursiveDependency :
  noble_kernel.contracts.Definition →
  noble_kernel.untrusted.UnsupportedKind
| RecursiveSchema :
  noble_kernel.contracts.SchemaId →
  noble_kernel.untrusted.UnsupportedKind

/-- [noble_kernel::untrusted::LimitKind]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 168:0-168:18
    Name pattern: [noble_kernel::untrusted::LimitKind]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::LimitKind"]
inductive noble_kernel.untrusted.LimitKind where
| Bytes : noble_kernel.untrusted.LimitKind
| Nodes : noble_kernel.untrusted.LimitKind
| Depth : noble_kernel.untrusted.LimitKind
| TypeSize : noble_kernel.untrusted.LimitKind
| StackHeight : noble_kernel.untrusted.LimitKind
| Work : noble_kernel.untrusted.LimitKind
| Diagnostics : noble_kernel.untrusted.LimitKind

/-- [noble_kernel::untrusted::Interface]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 139:0-139:20
    Name pattern: [noble_kernel::untrusted::Interface]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Interface"]
structure noble_kernel.untrusted.Interface where
  stack_in : alloc.vec.Vec noble_kernel.types.Ty
  stack_out : alloc.vec.Vec noble_kernel.types.Ty
  effects : noble_kernel.types.EffSet

/-- [noble_kernel::untrusted::Derivation]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 150:0-150:21
    Name pattern: [noble_kernel::untrusted::Derivation]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Derivation"]
structure noble_kernel.untrusted.Derivation where
  node : noble_kernel.untrusted.NodeId
  interface : noble_kernel.untrusted.Interface

/-- [noble_kernel::untrusted::Checked]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 159:0-159:18
    Name pattern: [noble_kernel::untrusted::Checked]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Checked"]
structure noble_kernel.untrusted.Checked where
  interface : noble_kernel.untrusted.Interface
  derivations : alloc.vec.Vec noble_kernel.untrusted.Derivation

/-- [noble_kernel::untrusted::Outcome]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 251:0-251:16
    Name pattern: [noble_kernel::untrusted::Outcome]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Outcome"]
inductive noble_kernel.untrusted.Outcome where
| Accepted : noble_kernel.untrusted.Checked → noble_kernel.untrusted.Outcome
| Invalid :
  noble_kernel.untrusted.Diagnostic →
  noble_kernel.untrusted.Outcome
| Unsupported :
  noble_kernel.untrusted.UnsupportedKind →
  noble_kernel.untrusted.Outcome
| Exhausted :
  noble_kernel.untrusted.LimitKind →
  noble_kernel.untrusted.Outcome
| InternalFailure : noble_kernel.untrusted.Outcome

/-- [noble_kernel::untrusted::Limits]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 104:0-104:17
    Name pattern: [noble_kernel::untrusted::Limits]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Limits"]
structure noble_kernel.untrusted.Limits where
  bytes : Std.U32
  nodes : Std.U32
  depth : Std.U32
  type_size : Std.U32
  stack_height : Std.U32
  work : Std.U32
  diagnostics : Std.U32

/-- [noble_kernel::untrusted::Expected]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 93:0-93:19
    Name pattern: [noble_kernel::untrusted::Expected]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Expected"]
structure noble_kernel.untrusted.Expected where
  stack_in : alloc.vec.Vec noble_kernel.types.Ty
  stack_out : alloc.vec.Vec noble_kernel.types.Ty
  allowed_effects : noble_kernel.types.EffSet

/-- [noble_kernel::untrusted::Request]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 127:0-127:18
    Name pattern: [noble_kernel::untrusted::Request]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Request"]
structure noble_kernel.untrusted.Request where
  input_bytes : Std.U32
  expected : noble_kernel.untrusted.Expected
  limits : noble_kernel.untrusted.Limits

/-- [noble_kernel::words::Variable]
    Source: 'crates/noble-kernel/src/words.rs', lines 18:0-18:19
    Name pattern: [noble_kernel::words::Variable]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::words::Variable"]
def noble_kernel.words.Variable := Std.U32

/-- [noble_kernel::words::Binding]
    Source: 'crates/noble-kernel/src/words.rs', lines 48:0-48:16
    Name pattern: [noble_kernel::words::Binding]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::words::Binding"]
inductive noble_kernel.words.Binding where
| Stack : alloc.vec.Vec noble_kernel.types.Ty → noble_kernel.words.Binding
| Value : noble_kernel.types.Ty → noble_kernel.words.Binding
| Effect : noble_kernel.types.EffSet → noble_kernel.words.Binding
| Ref : noble_kernel.words.Variable → noble_kernel.words.Binding

/-- [noble_kernel::words::Inst]
    Source: 'crates/noble-kernel/src/words.rs', lines 64:0-64:15
    Name pattern: [noble_kernel::words::Inst]
    Visibility: public -/
@[rust_type "noble_kernel::words::Inst"]
structure noble_kernel.words.Inst where
  bindings : alloc.vec.Vec noble_kernel.words.Binding

/-- [noble_kernel::untrusted::Lit]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 27:0-27:12
    Name pattern: [noble_kernel::untrusted::Lit]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Lit"]
inductive noble_kernel.untrusted.Lit where
| I64Lit : Std.I64 → noble_kernel.untrusted.Lit
| BoolLit : Bool → noble_kernel.untrusted.Lit
| TextLit : noble_kernel.untrusted.Lit
| UnitLit : noble_kernel.untrusted.Lit

/-- [noble_kernel::untrusted::Node]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 53:0-53:13
    Name pattern: [noble_kernel::untrusted::Node]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Node"]
inductive noble_kernel.untrusted.Node where
| Literal :
  noble_kernel.untrusted.Lit →
  noble_kernel.words.Inst →
  noble_kernel.untrusted.Node
| Invocation :
  noble_kernel.contracts.Definition →
  noble_kernel.words.Inst →
  noble_kernel.untrusted.Node
| Quotation :
  alloc.vec.Vec noble_kernel.untrusted.NodeId →
  noble_kernel.words.Inst →
  noble_kernel.untrusted.Node

/-- [noble_kernel::untrusted::Candidate]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 80:0-80:20
    Name pattern: [noble_kernel::untrusted::Candidate]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Candidate"]
structure noble_kernel.untrusted.Candidate where
  format : Std.U32
  revision : Std.U32
  nodes : alloc.vec.Vec noble_kernel.untrusted.Node
  body : alloc.vec.Vec noble_kernel.untrusted.NodeId

/-- [noble_kernel::words::VariableKind]
    Source: 'crates/noble-kernel/src/words.rs', lines 22:0-22:21
    Name pattern: [noble_kernel::words::VariableKind]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::words::VariableKind"]
inductive noble_kernel.words.VariableKind where
| Stack : noble_kernel.words.VariableKind
| Value : noble_kernel.words.VariableKind
| Effect : noble_kernel.words.VariableKind

/-- [noble_kernel::shapes::EffectSlot]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 80:0-80:19
    Name pattern: [noble_kernel::shapes::EffectSlot]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::shapes::EffectSlot"]
inductive noble_kernel.shapes.EffectSlot where
| Effect : noble_kernel.types.EffId → noble_kernel.shapes.EffectSlot
| Var : noble_kernel.words.Variable → noble_kernel.shapes.EffectSlot

/-- [noble_kernel::shapes::Pattern]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 26:0-26:16
    Name pattern: [noble_kernel::shapes::Pattern]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::shapes::Pattern"]
inductive noble_kernel.shapes.Pattern where
| UnitPattern : noble_kernel.shapes.Pattern
| BoolPattern : noble_kernel.shapes.Pattern
| I64Pattern : noble_kernel.shapes.Pattern
| TextPattern : noble_kernel.shapes.Pattern
| SyntaxPattern : noble_kernel.shapes.Pattern
| ContractPattern : noble_kernel.shapes.Pattern
| EvidencePattern : noble_kernel.shapes.Pattern
| CertifiedPattern : noble_kernel.shapes.Pattern
| PairPattern :
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern
| SumPattern :
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern
| ListPattern : noble_kernel.shapes.Pattern → noble_kernel.shapes.Pattern
| ProgramPattern :
  alloc.vec.Vec noble_kernel.shapes.Pattern →
  alloc.vec.Vec noble_kernel.shapes.Pattern →
  alloc.vec.Vec noble_kernel.shapes.EffectSlot →
  noble_kernel.shapes.Pattern
| ResourcePattern :
  noble_kernel.types.ResourceKind →
  noble_kernel.shapes.Pattern
| VarPattern : noble_kernel.words.Variable → noble_kernel.shapes.Pattern
| StackVarPattern : noble_kernel.words.Variable → noble_kernel.shapes.Pattern

/-- [noble_kernel::words::Scheme]
    Source: 'crates/noble-kernel/src/words.rs', lines 34:0-34:17
    Name pattern: [noble_kernel::words::Scheme]
    Visibility: public -/
@[rust_type "noble_kernel::words::Scheme"]
structure noble_kernel.words.Scheme where
  var_kinds : alloc.vec.Vec noble_kernel.words.VariableKind
  stack_in : alloc.vec.Vec noble_kernel.shapes.Pattern
  stack_out : alloc.vec.Vec noble_kernel.shapes.Pattern
  effects : alloc.vec.Vec noble_kernel.shapes.EffectSlot

/-- [noble_kernel::contracts::SchemaDecl]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 83:0-83:21
    Name pattern: [noble_kernel::contracts::SchemaDecl]
    Visibility: public -/
@[rust_type "noble_kernel::contracts::SchemaDecl"]
structure noble_kernel.contracts.SchemaDecl where
  id : noble_kernel.contracts.SchemaId
  scheme : noble_kernel.words.Scheme
  recursive : Bool

/-- [noble_kernel::contracts::Behavior]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 30:0-30:17
    Name pattern: [noble_kernel::contracts::Behavior]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::contracts::Behavior"]
inductive noble_kernel.contracts.Behavior where
| DupBehavior : noble_kernel.contracts.Behavior
| DropBehavior : noble_kernel.contracts.Behavior
| SwapBehavior : noble_kernel.contracts.Behavior
| DipBehavior : noble_kernel.contracts.Behavior
| ArithBehavior : noble_kernel.contracts.Behavior
| EqualsBehavior : noble_kernel.contracts.Behavior
| QuoteBehavior : noble_kernel.contracts.Behavior
| ComposeBehavior : noble_kernel.contracts.Behavior
| RunBehavior : noble_kernel.contracts.Behavior
| ReflectBehavior : noble_kernel.contracts.Behavior
| UnitBehavior : noble_kernel.contracts.Behavior
| PairBehavior : noble_kernel.contracts.Behavior
| UnpairBehavior : noble_kernel.contracts.Behavior
| InlBehavior : noble_kernel.contracts.Behavior
| InrBehavior : noble_kernel.contracts.Behavior
| CaseBehavior : noble_kernel.contracts.Behavior
| IfBehavior : noble_kernel.contracts.Behavior
| NilBehavior : noble_kernel.contracts.Behavior
| ConsBehavior : noble_kernel.contracts.Behavior
| ListCaseBehavior : noble_kernel.contracts.Behavior
| TestEmitBehavior : noble_kernel.contracts.Behavior
| NamedBehavior : noble_kernel.contracts.Behavior

/-- [noble_kernel::contracts::Env]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 94:0-94:14
    Name pattern: [noble_kernel::contracts::Env]
    Visibility: public -/
@[rust_type "noble_kernel::contracts::Env"]
structure noble_kernel.contracts.Env where
  defs : alloc.vec.Vec noble_kernel.words.Scheme
  kinds : alloc.vec.Vec noble_kernel.contracts.Behavior
  deps : alloc.vec.Vec (alloc.vec.Vec noble_kernel.contracts.Definition)
  schemas : alloc.vec.Vec noble_kernel.contracts.SchemaDecl
  effects : alloc.vec.Vec noble_kernel.types.EffId

/-- [noble_kernel::shapes::Defect]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 89:0-89:15
    Name pattern: [noble_kernel::shapes::Defect]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::shapes::Defect"]
inductive noble_kernel.shapes.Defect where
| UnknownVariable : noble_kernel.shapes.Defect
| KindMismatch : noble_kernel.shapes.Defect

/-- [noble_kernel::execution::TextLiteral]
    Source: 'crates/noble-kernel/src/execution/mod.rs', lines 9:0-9:22
    Name pattern: [noble_kernel::execution::TextLiteral]
    Visibility: public -/
@[rust_type "noble_kernel::execution::TextLiteral"]
structure noble_kernel.execution.TextLiteral where
  node : noble_kernel.untrusted.NodeId
  bytes : alloc.vec.Vec Std.U8

/-- [noble_kernel::execution::Body]
    Source: 'crates/noble-kernel/src/execution/mod.rs', lines 16:0-16:15
    Name pattern: [noble_kernel::execution::Body]
    Visibility: public -/
@[rust_type "noble_kernel::execution::Body"]
structure noble_kernel.execution.Body where
  candidate : noble_kernel.untrusted.Candidate
  texts : alloc.vec.Vec noble_kernel.execution.TextLiteral

/-- [noble_kernel::execution::Definition]
    Source: 'crates/noble-kernel/src/execution/mod.rs', lines 23:0-23:21
    Name pattern: [noble_kernel::execution::Definition]
    Visibility: public -/
@[rust_type "noble_kernel::execution::Definition"]
structure noble_kernel.execution.Definition where
  definition : noble_kernel.contracts.Definition
  identity : Std.U64
  body : noble_kernel.execution.Body
  expected : noble_kernel.untrusted.Expected

/-- [noble_kernel::execution::Submission]
    Source: 'crates/noble-kernel/src/execution/mod.rs', lines 37:0-37:21
    Name pattern: [noble_kernel::execution::Submission]
    Visibility: public -/
@[rust_type "noble_kernel::execution::Submission"]
structure noble_kernel.execution.Submission where
  environment : noble_kernel.contracts.Env
  definitions : alloc.vec.Vec noble_kernel.execution.Definition
  body : noble_kernel.execution.Body
  request : noble_kernel.untrusted.Request

/-- [noble_kernel::words::InstError]
    Source: 'crates/noble-kernel/src/words.rs', lines 71:0-71:18
    Name pattern: [noble_kernel::words::InstError]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::words::InstError"]
inductive noble_kernel.words.InstError where
| KindMismatch : noble_kernel.words.InstError
| UnknownVariable : noble_kernel.words.InstError
| ArityMismatch : noble_kernel.words.InstError
| OversizedStack : noble_kernel.words.InstError
| OversizedType : noble_kernel.words.InstError
| OversizedEffects : noble_kernel.words.InstError
| CyclicWitness : noble_kernel.words.InstError
| WalkExhausted : noble_kernel.words.InstError

/-- [noble_contracts::companion::admit::EvidencePayload]
    Source: 'crates/noble-contracts/src/companion/admit/mod.rs', lines 118:0-122:1
    Visibility: public -/
@[discriminant isize]
inductive companion.admit.EvidencePayload where
| Declaration : alloc.vec.Vec Std.U8 → companion.admit.EvidencePayload
| Resource : Std.U64 → companion.admit.EvidencePayload
| ServiceCapability : Std.U64 → companion.admit.EvidencePayload

/-- [noble_contracts::companion::registry::EvidenceClass]
    Source: 'crates/noble-contracts/src/companion/registry/mod.rs', lines 7:0-16:1
    Visibility: public -/
@[discriminant isize]
inductive companion.registry.EvidenceClass where
| LeanExact : companion.registry.EvidenceClass
| LeanRefutation : companion.registry.EvidenceClass
| Replay : companion.registry.EvidenceClass
| Assumption : companion.registry.EvidenceClass

/-- [noble_contracts::companion::admit::EvidenceOffer]
    Source: 'crates/noble-contracts/src/companion/admit/mod.rs', lines 108:0-112:1
    Visibility: public -/
structure companion.admit.EvidenceOffer where
  «class» : companion.registry.EvidenceClass
  refutation : Bool
  payload : companion.admit.EvidencePayload

/-- [noble_contracts::ExprKind]
    Source: 'crates/noble-contracts/src/lib.rs', lines 131:0-164:1
    Visibility: public -/
@[discriminant isize]
inductive ExprKind where
| I64Expr : Std.I64 → ExprKind
| BoolExpr : Bool → ExprKind
| UnitExpr : ExprKind
| InputExpr : Std.U32 → ExprKind
| OutputExpr : Std.U32 → ExprKind
| ParamExpr : Std.U32 → ExprKind
| DefinitionExpr : Std.U32 → ExprKind
| NotExpr : Std.U32 → ExprKind
| AndExpr : Std.U32 → Std.U32 → ExprKind
| OrExpr : Std.U32 → Std.U32 → ExprKind
| ImpliesExpr : Std.U32 → Std.U32 → ExprKind
| EqExpr : Std.U32 → Std.U32 → ExprKind
| LtExpr : Std.U32 → Std.U32 → ExprKind
| LeExpr : Std.U32 → Std.U32 → ExprKind
| AddExpr : Std.U32 → Std.U32 → ExprKind
| SubExpr : Std.U32 → Std.U32 → ExprKind
| MulExpr : Std.U32 → Std.U32 → ExprKind
| PairExpr : Std.U32 → Std.U32 → ExprKind
| FirstExpr : Std.U32 → ExprKind
| SecondExpr : Std.U32 → ExprKind
| InlExpr : Std.U32 → ExprKind
| InrExpr : Std.U32 → ExprKind
| IsLeftExpr : Std.U32 → ExprKind
| LeftExpr : Std.U32 → ExprKind
| RightExpr : Std.U32 → ExprKind
| NilExpr : ExprKind
| ConsExpr : Std.U32 → Std.U32 → ExprKind
| IsNilExpr : Std.U32 → ExprKind
| HeadExpr : Std.U32 → ExprKind
| TailExpr : Std.U32 → ExprKind
| LengthExpr : Std.U32 → ExprKind
| MapsExpr : Std.U32 → Std.U32 → Std.U32 → ExprKind

/-- [noble_contracts::Span]
    Source: 'crates/noble-contracts/src/lib.rs', lines 54:0-57:1
    Visibility: public -/
structure Span where
  start : Std.U32
  «end» : Std.U32

/-- [noble_contracts::Expr]
    Source: 'crates/noble-contracts/src/lib.rs', lines 109:0-115:1
    Visibility: public -/
structure Expr where
  kind : ExprKind
  ty : noble_kernel.types.Ty
  span : Span
  total : Bool
  uses_output : Bool

/-- [noble_contracts::LogicDef]
    Source: 'crates/noble-contracts/src/lib.rs', lines 102:0-106:1
    Visibility: public -/
structure LogicDef where
  «name» : String
  ty : noble_kernel.types.Ty
  body : Std.U32

/-- [noble_contracts::NamedType]
    Source: 'crates/noble-contracts/src/lib.rs', lines 96:0-99:1
    Visibility: public -/
structure NamedType where
  «name» : String
  ty : noble_kernel.types.Ty

/-- [noble_contracts::Prepared]
    Source: 'crates/noble-contracts/src/lib.rs', lines 168:0-180:1
    Visibility: public -/
structure Prepared where
  «name» : String
  inputs : alloc.vec.Vec NamedType
  outputs : alloc.vec.Vec NamedType
  params : alloc.vec.Vec NamedType
  definitions : alloc.vec.Vec LogicDef
  expressions : alloc.vec.Vec Expr
  requires : Std.U32
  ensures : Std.U32
  candidate : noble_kernel.untrusted.Candidate
  request : noble_kernel.untrusted.Request
  checked : noble_kernel.untrusted.Checked

/-- [noble_contracts::Limits]
    Source: 'crates/noble-contracts/src/lib.rs', lines 35:0-40:1
    Visibility: public -/
structure Limits where
  bytes : Std.U32
  nodes : Std.U32
  depth : Std.U32
  work : Std.U32

/-- [noble_contracts::companion::SubjectDigest]
    Source: 'crates/noble-contracts/src/companion/mod.rs', lines 229:0-229:34
    Visibility: public -/
@[reducible]
def companion.SubjectDigest := Std.U64

/-- [noble_contracts::companion::registry::Observation]
    Source: 'crates/noble-contracts/src/companion/registry/mod.rs', lines 96:0-99:1 -/
structure companion.registry.Observation where
  subject : companion.SubjectDigest
  events : alloc.vec.Vec (Std.U32 × Std.U64)

/-- [noble_contracts::companion::rules::RuleId]
    Source: 'crates/noble-contracts/src/companion/rules/mod.rs', lines 15:0-22:1
    Visibility: public -/
@[discriminant isize [1,2,3,4,5,6]]
inductive companion.rules.RuleId where
| AdmitLeanV1 : companion.rules.RuleId
| ComposeV1 : companion.rules.RuleId
| InstantiateV1 : companion.rules.RuleId
| GuardV1 : companion.rules.RuleId
| ProjectV1 : companion.rules.RuleId
| InvokeV1 : companion.rules.RuleId

/-- [noble_contracts::companion::registry::EvidenceId]
    Source: 'crates/noble-contracts/src/companion/registry/mod.rs', lines 47:0-47:31
    Visibility: public -/
@[reducible]
def companion.registry.EvidenceId := Std.U32

/-- [noble_contracts::companion::registry::ContractId]
    Source: 'crates/noble-contracts/src/companion/registry/mod.rs', lines 43:0-43:31
    Visibility: public -/
@[reducible]
def companion.registry.ContractId := Std.U32

/-- [noble_contracts::companion::CaptureBinding]
    Source: 'crates/noble-contracts/src/companion/mod.rs', lines 222:0-225:1
    Visibility: public -/
structure companion.CaptureBinding where
  slot : Std.U32
  value : Std.U64

/-- [noble_contracts::companion::Subject]
    Source: 'crates/noble-contracts/src/companion/mod.rs', lines 234:0-244:1
    Visibility: public -/
structure companion.Subject where
  identity : companion.SubjectDigest
  input_signature : Std.U64
  output_signature : Std.U64
  captures : alloc.vec.Vec companion.CaptureBinding
  events : alloc.vec.Vec (Std.U32 × Std.U64)

/-- [noble_contracts::companion::admit::Outcome]
    Source: 'crates/noble-contracts/src/companion/admit/mod.rs', lines 81:0-89:1
    Visibility: public -/
@[discriminant isize]
inductive companion.admit.Outcome where
| Proved : companion.admit.Outcome
| Disproved : companion.admit.Outcome
| Unknown : companion.admit.Outcome
| Timeout : companion.admit.Outcome
| Unsupported : companion.admit.Outcome
| Error : companion.admit.Outcome
| NotRun : companion.admit.Outcome

/-- [noble_contracts::companion::GuardTemplate]
    Source: 'crates/noble-contracts/src/companion/mod.rs', lines 211:0-218:1
    Visibility: public -/
@[discriminant isize]
inductive companion.GuardTemplate where
| LtI64Max : companion.GuardTemplate
| NeI64Min : companion.GuardTemplate
| EqI64Literal : Std.I64 → companion.GuardTemplate

/-- [noble_contracts::companion::admit::ClaimTemplate]
    Source: 'crates/noble-contracts/src/companion/admit/mod.rs', lines 27:0-37:1
    Visibility: public -/
@[discriminant isize]
inductive companion.admit.ClaimTemplate where
| IncrementBy : Std.I64 → companion.admit.ClaimTemplate
| IncrementByCapture : companion.admit.ClaimTemplate
| GuardCorrespondence :
  companion.GuardTemplate →
  companion.admit.ClaimTemplate
| Admitted : Std.U64 → companion.admit.ClaimTemplate

/-- [noble_contracts::companion::registry::EvidenceEntry]
    Source: 'crates/noble-contracts/src/companion/registry/mod.rs', lines 81:0-92:1 -/
structure companion.registry.EvidenceEntry where
  contract : companion.registry.ContractId
  statement : Std.U64
  template : companion.admit.ClaimTemplate
  subject : companion.Subject
  «class» : companion.registry.EvidenceClass
  outcome : companion.admit.Outcome
  policy : Std.U32
  revision : Std.U32
  premises : alloc.vec.Vec companion.registry.EvidenceId
  rule : Option companion.rules.RuleId

/-- [noble_contracts::companion::registry::ContractEntry]
    Source: 'crates/noble-contracts/src/companion/registry/mod.rs', lines 60:0-77:1 -/
structure companion.registry.ContractEntry where
  statement : Std.U64
  exact_statement : String
  claim : companion.admit.ClaimTemplate
  policy : Std.U32
  revision : Std.U32
  guards : alloc.vec.Vec companion.GuardTemplate
  program : alloc.vec.Vec (Std.U32 × Std.U64)
  input_signature : Std.U64
  output_signature : Std.U64
  input : alloc.vec.Vec noble_kernel.types.Ty
  output : alloc.vec.Vec noble_kernel.types.Ty

/-- [noble_contracts::companion::registry::Registry]
    Source: 'crates/noble-contracts/src/companion/registry/mod.rs', lines 102:0-109:1 -/
structure companion.registry.Registry where
  contracts : alloc.vec.Vec companion.registry.ContractEntry
  evidence : alloc.vec.Vec companion.registry.EvidenceEntry
  observations : alloc.vec.Vec companion.registry.Observation
  contract_cap : Option Std.Usize
  evidence_cap : Option Std.Usize
  observation_cap : Option Std.Usize

/-- [noble_contracts::companion::Core]
    Source: 'crates/noble-contracts/src/companion/mod.rs', lines 195:0-206:1
    Visibility: public -/
structure companion.Core where
  limits : Limits
  registry : companion.registry.Registry
  policy : Std.U32
  revision : Std.U32
  semantic_revision : Std.U32
  host_contract : Std.U64
  environment_fact : Std.U64

/-- [noble_contracts::companion::Budget]
    Source: 'crates/noble-contracts/src/companion/mod.rs', lines 170:0-172:1 -/
structure companion.Budget where
  work : Std.U32

/-- [noble_contracts::companion::Refusal]
    Source: 'crates/noble-contracts/src/companion/mod.rs', lines 139:0-166:1
    Visibility: public -/
@[discriminant isize]
inductive companion.Refusal where
| UnknownRule : companion.Refusal
| UnsupportedRuleset : companion.Refusal
| UnsupportedSemanticRevision : companion.Refusal
| CyclicDerivation : companion.Refusal
| DuplicatePremise : companion.Refusal
| MissingPremise : companion.Refusal
| WrongPremiseClass : companion.Refusal
| MismatchedSubject : companion.Refusal
| MismatchedClaim : companion.Refusal
| MismatchedContext : companion.Refusal
| StaleContext : companion.Refusal
| UnresolvedImplication : companion.Refusal
| WrongInstantiation : companion.Refusal
| UnsupportedEvidenceClass : companion.Refusal
| ForgedStatus : companion.Refusal
| UnknownContract : companion.Refusal
| UnknownEvidence : companion.Refusal
| UnsupportedGuardTemplate : companion.Refusal
| IneligibleGhost : companion.Refusal
| LiveCapabilityInEvidence : companion.Refusal
| InvalidEvidenceEncoding : companion.Refusal
| CorrespondenceMismatch : companion.Refusal
| ExhaustedReplay : companion.Refusal
| ExhaustedRegistry : companion.Refusal
| DuplicateEntry : companion.Refusal
| Internal : companion.Refusal

/-- [noble_contracts::wire::ProjectionError]
    Source: 'crates/noble-contracts/src/wire.rs', lines 19:0-23:1
    Visibility: public -/
@[discriminant isize]
inductive wire.ProjectionError where
| Revision : wire.ProjectionError
| PayloadlessText : wire.ProjectionError
| HostWord : wire.ProjectionError

/-- [noble_contracts::wire::SemanticNode]
    Source: 'crates/noble-contracts/src/wire.rs', lines 9:0-15:1
    Visibility: public -/
@[discriminant isize]
inductive wire.SemanticNode where
| I64 : Std.I64 → wire.SemanticNode
| Boolean : Bool → wire.SemanticNode
| UnitValue : wire.SemanticNode
| Word : Std.U32 → wire.SemanticNode
| Quotation : alloc.vec.Vec Std.U32 → wire.SemanticNode

/-- [noble_contracts::wire::SemanticSubject]
    Source: 'crates/noble-contracts/src/wire.rs', lines 26:0-29:1
    Visibility: public -/
structure wire.SemanticSubject where
  nodes : alloc.vec.Vec wire.SemanticNode
  body : alloc.vec.Vec Std.U32

/-- [noble_contracts::companion::digest::Fold]
    Source: 'crates/noble-contracts/src/companion/digest.rs', lines 31:0-33:1 -/
structure companion.digest.Fold where
  state : Std.U64

/-- [noble_contracts::companion::admit::program::Pending]
    Source: 'crates/noble-contracts/src/companion/admit/program.rs', lines 8:0-11:1 -/
@[discriminant isize]
inductive companion.admit.program.Pending where
| Node : Std.U32 → companion.admit.program.Pending
| CloseQuotation : companion.admit.program.Pending

/-- [noble_contracts::companion::admit::Admission]
    Source: 'crates/noble-contracts/src/companion/admit/mod.rs', lines 152:0-158:1
    Visibility: public -/
structure companion.admit.Admission where
  outcome : companion.admit.Outcome
  contract : Option companion.registry.ContractId
  evidence : Option companion.registry.EvidenceId
  statement_digest : Std.U64
  refusals : alloc.vec.Vec companion.Refusal

/-- [noble_contracts::companion::admit::AdmissionRequest]
    Source: 'crates/noble-contracts/src/companion/admit/mod.rs', lines 127:0-134:1
    Visibility: public -/
structure companion.admit.AdmissionRequest where
  expected : Prepared
  offer : companion.admit.EvidenceOffer
  contract : companion.registry.ContractId
  statement : Std.U64
  policy : Std.U32
  revision : Std.U32

/-- [noble_contracts::companion::admit::CheckObservation]
    Source: 'crates/noble-contracts/src/companion/admit/mod.rs', lines 144:0-148:1
    Visibility: public -/
structure companion.admit.CheckObservation where
  checked_statement : String
  checked_source : alloc.vec.Vec Std.U8
  result : core.result.Result companion.registry.EvidenceClass
    companion.Refusal

/-- [noble_contracts::companion::registry::ContextSnapshot]
    Source: 'crates/noble-contracts/src/companion/registry/mod.rs', lines 51:0-54:1 -/
structure companion.registry.ContextSnapshot where
  policy : Std.U32
  revision : Std.U32

/-- [noble_contracts::companion::rules::premises::step::SeedBounds]
    Source: 'crates/noble-contracts/src/companion/rules/premises/step.rs', lines 5:0-9:1 -/
structure companion.rules.premises.step.SeedBounds where
  next : Std.U32
  entry_bound : Std.Usize
  should_reject_duplicates : Bool

/-- [noble_contracts::companion::rules::Derivation]
    Source: 'crates/noble-contracts/src/companion/rules/mod.rs', lines 55:0-61:1
    Visibility: public -/
structure companion.rules.Derivation where
  rule : companion.rules.RuleId
  contract : companion.registry.ContractId
  statement : Std.U64
  subject : companion.Subject
  premises : alloc.vec.Vec companion.registry.EvidenceId

/-- [noble_contracts::companion::InterfaceSignatures]
    Source: 'crates/noble-contracts/src/companion/mod.rs', lines 23:0-26:1
    Visibility: public -/
structure companion.InterfaceSignatures where
  input : Std.U64
  output : Std.U64

/-- [noble_contracts::companion::rules::Derived]
    Source: 'crates/noble-contracts/src/companion/rules/mod.rs', lines 5:0-9:1
    Visibility: public -/
structure companion.rules.Derived where
  evidence : companion.registry.EvidenceId
  contract : companion.registry.ContractId
  statement_digest : Std.U64

/-- [noble_contracts::companion::Release]
    Source: 'crates/noble-contracts/src/companion/mod.rs', lines 250:0-257:1
    Visibility: public -/
structure companion.Release where
  contract : companion.registry.ContractId
  evidence : companion.registry.EvidenceId
  statement : Std.U64
  subject : companion.SubjectDigest
  policy : Std.U32
  ruleset : Std.U32

/-- [noble_contracts::companion::EncodedRule]
    Source: 'crates/noble-contracts/src/companion/mod.rs', lines 30:0-33:1
    Visibility: public -/
structure companion.EncodedRule where
  ruleset : Std.U32
  code : Std.U32

/-- [noble_contracts::DiagnosticKind]
    Source: 'crates/noble-contracts/src/lib.rs', lines 60:0-65:1
    Visibility: public -/
@[discriminant isize]
inductive DiagnosticKind where
| Invalid : DiagnosticKind
| Unsupported : DiagnosticKind
| Exhausted : DiagnosticKind
| Internal : DiagnosticKind

/-- [noble_contracts::Diagnostic]
    Source: 'crates/noble-contracts/src/lib.rs', lines 68:0-73:1
    Visibility: public -/
structure Diagnostic where
  kind : DiagnosticKind
  span : Span
  message : String
  ordinary_typing : Option noble_kernel.untrusted.Checked

/-- [noble_contracts::component::Stage]
    Source: 'crates/noble-contracts/src/component/mod.rs', lines 176:0-181:1
    Visibility: public -/
@[discriminant isize]
inductive component.Stage where
| Wit : component.Stage
| Binding : component.Stage
| Export : component.Stage
| Acceptance : component.Stage

/-- [noble_contracts::component::Error]
    Source: 'crates/noble-contracts/src/component/mod.rs', lines 184:0-187:1
    Visibility: public -/
structure component.Error where
  stage : component.Stage
  diagnostic : Diagnostic

/-- [noble_contracts::component::Bindings]
    Source: 'crates/noble-contracts/src/component/mod.rs', lines 167:0-173:1 -/
structure component.Bindings where
  environment : noble_kernel.contracts.Env
  words : alloc.vec.Vec (String × noble_kernel.contracts.Definition)
  resources : alloc.vec.Vec noble_kernel.types.ResourceKind
  effects : Std.U64
  key : alloc.vec.Vec Std.U8

/-- [noble_contracts::component::Type]
    Source: 'crates/noble-contracts/src/component/mod.rs', lines 16:0-24:1
    Visibility: public -/
@[discriminant isize]
inductive component.Type where
| Boolean : component.Type
| S64 : component.Type
| String : component.Type
| Bytes : component.Type
| ResultS64String : component.Type
| Own : noble_kernel.types.ResourceKind → component.Type
| Borrow : noble_kernel.types.ResourceKind → component.Type

/-- [noble_contracts::component::Operation]
    Source: 'crates/noble-contracts/src/component/mod.rs', lines 55:0-70:1
    Visibility: public -/
structure component.Operation where
  identity : String
  word : String
  core_module : String
  core_name : String
  export_name : String
  parameters : alloc.vec.Vec component.Type
  results : alloc.vec.Vec component.Type
  effect : Option noble_kernel.types.EffId
  definition : Option noble_kernel.contracts.Definition

/-- [noble_contracts::component::Resource]
    Source: 'crates/noble-contracts/src/component/mod.rs', lines 47:0-52:1
    Visibility: public -/
structure component.Resource where
  identity : String
  interface : String
  «name» : String
  kind : noble_kernel.types.ResourceKind

/-- [noble_contracts::component::World]
    Source: 'crates/noble-contracts/src/component/mod.rs', lines 105:0-113:1
    Visibility: public -/
structure component.World where
  identity : String
  «name» : String
  wit : alloc.vec.Vec Std.U8
  imports : alloc.vec.Vec component.Operation
  exports : alloc.vec.Vec component.Operation
  resources : alloc.vec.Vec component.Resource
  limits : Limits

/-- [noble_contracts::component::parser::Cursor]
    Source: 'crates/noble-contracts/src/component/parser.rs', lines 64:0-69:1 -/
structure component.parser.Cursor where
  source : Str
  tokens : alloc.vec.Vec (core.ops.range.Range Std.Usize)
  «at» : Std.Usize
  remaining : Std.U32

/-- [noble_contracts::component::parser::RawType]
    Source: 'crates/noble-contracts/src/component/parser.rs', lines 22:0-30:1 -/
@[discriminant isize]
inductive component.parser.RawType where
| Bool : component.parser.RawType
| S64 : component.parser.RawType
| String : component.parser.RawType
| Bytes : component.parser.RawType
| ResultS64String : component.parser.RawType
| Own : String → component.parser.RawType
| Borrow : String → component.parser.RawType

/-- [noble_contracts::component::parser::Function]
    Source: 'crates/noble-contracts/src/component/parser.rs', lines 32:0-37:1 -/
structure component.parser.Function where
  «name» : String
  method : Option String
  parameters : alloc.vec.Vec component.parser.RawType
  results : alloc.vec.Vec component.parser.RawType

/-- [noble_contracts::component::parser::Interface]
    Source: 'crates/noble-contracts/src/component/parser.rs', lines 38:0-42:1 -/
structure component.parser.Interface where
  «name» : String
  resources : alloc.vec.Vec String
  functions : alloc.vec.Vec component.parser.Function

/-- [noble_contracts::component::parser::Use]
    Source: 'crates/noble-contracts/src/component/parser.rs', lines 43:0-46:1 -/
structure component.parser.Use where
  interface : String
  «name» : String

/-- [noble_contracts::component::parser::Item]
    Source: 'crates/noble-contracts/src/component/parser.rs', lines 48:0-52:1 -/
@[discriminant isize]
inductive component.parser.Item where
| Interface : Bool → String → component.parser.Item
| Function : Bool → component.parser.Function → component.parser.Item
| Use : component.parser.Use → component.parser.Item

/-- [noble_contracts::component::parser::RawWorld]
    Source: 'crates/noble-contracts/src/component/parser.rs', lines 53:0-56:1 -/
structure component.parser.RawWorld where
  «name» : String
  items : alloc.vec.Vec component.parser.Item

/-- [noble_contracts::component::parser::Package]
    Source: 'crates/noble-contracts/src/component/parser.rs', lines 57:0-63:1 -/
structure component.parser.Package where
  «namespace» : String
  «name» : String
  version : String
  interfaces : alloc.vec.Vec component.parser.Interface
  worlds : alloc.vec.Vec component.parser.RawWorld

/-- [noble_contracts::component::parser::cursor::{noble_contracts::component::parser::Cursor<'a>}::version_part::{closure}]
    Source: 'crates/noble-contracts/src/component/parser/cursor.rs', lines 74:34-74:62 -/
@[reducible]
def component.parser.cursor.Cursor.version_part.closure := Unit

/-- [noble_contracts::component::parser::resolve::{noble_contracts::component::parser::resolve::Context<'_0>}::install::{closure}]
    Source: 'crates/noble-contracts/src/component/parser/resolve.rs', lines 232:17-232:93 -/
def component.parser.resolve.Context.install.closure := String × String

/-- [noble_contracts::component::parser::resolve::Context]
    Source: 'crates/noble-contracts/src/component/parser/resolve.rs', lines 11:0-14:1 -/
structure component.parser.resolve.Context where
  package : component.parser.Package
  selected : component.parser.RawWorld

/-- [noble_contracts::component::parser::resolve::types::scoped_resource::{closure}]
    Source: 'crates/noble-contracts/src/component/parser/resolve/types.rs', lines 64:18-64:85 -/
def component.parser.resolve.types.scoped_resource.closure := Str × Str

/-- [noble_contracts::component::parser::resolve::signature::{noble_contracts::component::parser::resolve::Context<'_0>}::signature::{closure}]
    Source: 'crates/noble-contracts/src/component/parser/resolve/signature.rs', lines 44:56-53:9 -/
@[reducible]
def component.parser.resolve.signature.Context.signature.closure := Unit

/-- [noble_contracts::component::parser::resolve::{noble_contracts::component::parser::resolve::Context<'_0>}::item::{closure}]
    Source: 'crates/noble-contracts/src/component/parser/resolve.rs', lines 154:30-154:65 -/
@[reducible]
def component.parser.resolve.Context.item.closure := String

/-- [noble_contracts::component::parser::resolve::declarations::interface_world_collision::{closure}]
    Source: 'crates/noble-contracts/src/component/parser/resolve/declarations.rs', lines 135:13-135:66 -/
def component.parser.resolve.declarations.interface_world_collision.closure :=
  component.parser.Package × Std.Usize

/-- [noble_contracts::source::Target]
    Source: 'crates/noble-contracts/src/source.rs', lines 43:0-46:1 -/
@[discriminant isize]
inductive source.Target where
| Builtin : Std.U32 → source.Target
| Named : Std.U32 → source.Target

/-- [noble_contracts::source::Kind]
    Source: 'crates/noble-contracts/src/source.rs', lines 49:0-55:1 -/
@[discriminant isize]
inductive source.Kind where
| Literal : noble_kernel.untrusted.Lit → source.Kind
| Text : alloc.vec.Vec Std.U8 → source.Kind
| Word : alloc.vec.Vec Std.U8 → source.Kind
| Call : source.Target → source.Kind
| Quotation : alloc.vec.Vec Std.U32 → source.Kind

/-- [noble_contracts::source::Node]
    Source: 'crates/noble-contracts/src/source.rs', lines 58:0-61:1 -/
structure source.Node where
  kind : source.Kind
  span : Span

/-- [noble_contracts::source::Tree]
    Source: 'crates/noble-contracts/src/source.rs', lines 64:0-68:1 -/
structure source.Tree where
  nodes : alloc.vec.Vec source.Node
  body : alloc.vec.Vec Std.U32
  span : Span

/-- [noble_contracts::source::Named]
    Source: 'crates/noble-contracts/src/source.rs', lines 84:0-88:1 -/
structure source.Named where
  «name» : String
  identity : Std.U64
  tree : source.Tree

/-- [noble_contracts::source::Session]
    Source: 'crates/noble-contracts/src/source.rs', lines 119:0-125:1
    Visibility: public -/
structure source.Session where
  definitions : alloc.vec.Vec source.Named
  history : alloc.vec.Vec Std.U8
  generation : Std.U64
  hosts : Bool
  bindings : Option component.Bindings

/-- [noble_contracts::source::Prepared]
    Source: 'crates/noble-contracts/src/source.rs', lines 92:0-101:1
    Visibility: public -/
structure source.Prepared where
  generation : Std.U64
  history : alloc.vec.Vec Std.U8
  hosts : Bool
  boundary : Option (alloc.vec.Vec Std.U8)
  definition : Option source.Named
  addition : alloc.vec.Vec Std.U8
  submission : Option noble_kernel.execution.Submission
  output : alloc.vec.Vec noble_kernel.types.Ty

/-- [noble_contracts::component::CheckedExport]
    Source: 'crates/noble-contracts/src/component/mod.rs', lines 210:0-215:1
    Visibility: public -/
structure component.CheckedExport where
  world : alloc.vec.Vec Std.U8
  index : Std.Usize
  source_bytes : alloc.vec.Vec Std.U8
  prepared : source.Prepared

/-- [noble_contracts::source::Stage]
    Source: 'crates/noble-contracts/src/source.rs', lines 17:0-22:1
    Visibility: public -/
@[discriminant isize]
inductive source.Stage where
| Parse : source.Stage
| Resolve : source.Stage
| Check : source.Stage
| Acceptance : source.Stage

/-- [noble_contracts::source::Error]
    Source: 'crates/noble-contracts/src/source.rs', lines 25:0-28:1
    Visibility: public -/
structure source.Error where
  stage : source.Stage
  diagnostic : Diagnostic

/-- [noble_contracts::Meter]
    Source: 'crates/noble-contracts/src/lib.rs', lines 222:0-226:1 -/
structure Meter where
  limits : Limits
  work : Std.U32
  nodes : Std.U32

/-- [noble_contracts::source::resolution::comparison::Body]
    Source: 'crates/noble-contracts/src/source/resolution/comparison.rs', lines 2:0-5:1 -/
@[discriminant isize]
inductive source.resolution.comparison.Body where
| Root : source.resolution.comparison.Body
| Quotation : Std.U32 → source.resolution.comparison.Body

/-- [noble_contracts::source::resolution::comparison::Context]
    Source: 'crates/noble-contracts/src/source/resolution/comparison.rs', lines 15:0-19:1 -/
structure source.resolution.comparison.Context where
  left : source.Tree
  right : source.Tree
  session : source.Session

/-- [noble_contracts::source::resolution::comparison::Entry]
    Source: 'crates/noble-contracts/src/source/resolution/comparison.rs', lines 8:0-13:1 -/
structure source.resolution.comparison.Entry where
  left : source.resolution.comparison.Body
  right : source.resolution.comparison.Body
  «at» : Std.Usize
  depth : Std.Usize

/-- [noble_contracts::source::resolution::identity::{closure}]
    Source: 'crates/noble-contracts/src/source/resolution.rs', lines 218:18-218:40 -/
@[reducible]
def source.resolution.identity.closure := Unit

/-- [noble_contracts::source::preparation::{noble_contracts::source::Session}::prepare::{closure}]
    Source: 'crates/noble-contracts/src/source/preparation.rs', lines 75:49-75:80 -/
@[reducible]
def source.preparation.Session.prepare.closure := Unit

/-- [noble_contracts::source::preflight::PathStep]
    Source: 'crates/noble-contracts/src/source/preflight.rs', lines 33:0-40:1 -/
@[discriminant isize]
inductive source.preflight.PathStep where
| Root : source.preflight.PathStep
| Left : source.preflight.PathStep
| Right : source.preflight.PathStep
| Item : source.preflight.PathStep
| Input : Std.Usize → source.preflight.PathStep
| Output : Std.Usize → source.preflight.PathStep

/-- [noble_contracts::source::preflight::Visit]
    Source: 'crates/noble-contracts/src/source/preflight.rs', lines 42:0-45:1 -/
structure source.preflight.Visit where
  step : source.preflight.PathStep
  depth : Std.U32

/-- [noble_contracts::source::preflight::Traversal]
    Source: 'crates/noble-contracts/src/source/preflight.rs', lines 47:0-51:1 -/
structure source.preflight.Traversal where
  pending : alloc.vec.Vec source.preflight.Visit
  path : alloc.vec.Vec source.preflight.PathStep
  type_nodes : Std.Usize

/-- [noble_contracts::source::parsing::Frame]
    Source: 'crates/noble-contracts/src/source/parsing.rs', lines 6:0-9:1 -/
structure source.parsing.Frame where
  body : alloc.vec.Vec Std.U32
  start : Std.U32

/-- [noble_contracts::source::lexer::Scanner]
    Source: 'crates/noble-contracts/src/source/lexer.rs', lines 23:0-27:1 -/
structure source.lexer.Scanner where
  source : Slice Std.U8
  «at» : Std.Usize
  full : Span

/-- [noble_contracts::source::lexer::TokenKind]
    Source: 'crates/noble-contracts/src/source/lexer.rs', lines 9:0-16:1 -/
@[discriminant isize]
inductive source.lexer.TokenKind where
| Open : source.lexer.TokenKind
| Close : source.lexer.TokenKind
| Def : source.lexer.TokenKind
| Literal : noble_kernel.untrusted.Lit → source.lexer.TokenKind
| Text : alloc.vec.Vec Std.U8 → source.lexer.TokenKind
| Word : alloc.vec.Vec Std.U8 → source.lexer.TokenKind

/-- [noble_contracts::syntax::integer::Accumulator]
    Source: 'crates/noble-contracts/src/syntax/integer.rs', lines 1:0-4:1 -/
structure syntax.integer.Accumulator where
  value : Std.I64
  is_negative : Bool

/-- [noble_contracts::source::lexer::Token]
    Source: 'crates/noble-contracts/src/source/lexer.rs', lines 18:0-21:1 -/
structure source.lexer.Token where
  kind : source.lexer.TokenKind
  span : Span

/-- [noble_contracts::source::parsing::State]
    Source: 'crates/noble-contracts/src/source/parsing.rs', lines 11:0-14:1 -/
structure source.parsing.State where
  frames : alloc.vec.Vec source.parsing.Frame
  nodes : alloc.vec.Vec source.Node

/-- [noble_contracts::source::inference::validation::Visit]
    Source: 'crates/noble-contracts/src/source/inference/validation.rs', lines 88:0-93:1 -/
structure source.inference.validation.Visit where
  id : Std.U32
  depth : Std.U32
  height : Std.U32
  group : Option Std.Usize

/-- [noble_contracts::source::inference::validation::Traversal]
    Source: 'crates/noble-contracts/src/source/inference/validation.rs', lines 95:0-98:1 -/
structure source.inference.validation.Traversal where
  pending : alloc.vec.Vec source.inference.validation.Visit
  sizes : alloc.vec.Vec Std.U32

/-- [noble_contracts::inference::Sort]
    Source: 'crates/noble-contracts/src/inference/mod.rs', lines 14:0-17:1 -/
@[discriminant isize]
inductive inference.Sort where
| Value : inference.Sort
| Stack : inference.Sort

/-- [noble_contracts::inference::Term]
    Source: 'crates/noble-contracts/src/inference/mod.rs', lines 22:0-40:1 -/
@[discriminant isize]
inductive inference.Term where
| HoleTerm : inference.Sort → inference.Term
| LinkTerm : Std.U32 → inference.Term
| UnitTerm : inference.Term
| BoolTerm : inference.Term
| I64Term : inference.Term
| TextTerm : inference.Term
| SyntaxTerm : inference.Term
| ContractTerm : inference.Term
| EvidenceTerm : inference.Term
| CertifiedTerm : inference.Term
| ResourceTerm : noble_kernel.types.ResourceKind → inference.Term
| PairTerm : Std.U32 → Std.U32 → inference.Term
| SumTerm : Std.U32 → Std.U32 → inference.Term
| ListTerm : Std.U32 → inference.Term
| ProgramTerm : Std.U32 → Std.U32 → inference.Term
| EmptyTerm : inference.Term
| PushTerm : Std.U32 → Std.U32 → inference.Term

/-- [noble_contracts::inference::effects::Effect]
    Source: 'crates/noble-contracts/src/inference/effects.rs', lines 8:0-12:1 -/
@[discriminant isize]
inductive inference.effects.Effect where
| Hole : inference.effects.Effect
| Constant : Std.U64 → inference.effects.Effect
| Union : Std.U32 → Std.U32 → inference.effects.Effect

/-- [noble_contracts::inference::Arena]
    Source: 'crates/noble-contracts/src/inference/mod.rs', lines 56:0-65:1 -/
structure inference.Arena where
  terms : alloc.vec.Vec inference.Term
  effectful : Bool
  effect_universe : Std.U64
  resources : Bool
  effects : alloc.vec.Vec inference.effects.Effect
  effect_bounds : alloc.vec.Vec Std.U64
  effect_equations : alloc.vec.Vec (Std.U32 × Std.U32)
  program_effects : alloc.vec.Vec (Std.U32 × Std.U32)

/-- [noble_contracts::inference::Variable]
    Source: 'crates/noble-contracts/src/inference/mod.rs', lines 43:0-48:1 -/
@[discriminant isize]
inductive inference.Variable where
| Value : Std.U32 → inference.Variable
| Stack : Std.U32 → inference.Variable
| Effect : inference.Variable
| EffectValue : Std.U32 → inference.Variable

/-- [noble_contracts::source::inference::DraftKind]
    Source: 'crates/noble-contracts/src/source/inference/mod.rs', lines 11:0-15:1 -/
@[discriminant isize]
inductive source.inference.DraftKind where
| Literal : noble_kernel.untrusted.Lit → source.inference.DraftKind
| Invocation : noble_kernel.contracts.Definition → source.inference.DraftKind
| Quotation :
  alloc.vec.Vec noble_kernel.untrusted.NodeId →
  source.inference.DraftKind

/-- [noble_contracts::source::inference::Draft]
    Source: 'crates/noble-contracts/src/source/inference/mod.rs', lines 17:0-22:1 -/
structure source.inference.Draft where
  kind : source.inference.DraftKind
  «variables» : alloc.vec.Vec inference.Variable
  text : Option (alloc.vec.Vec Std.U8)
  span : Span

/-- [noble_contracts::source::inference::Body]
    Source: 'crates/noble-contracts/src/source/inference/mod.rs', lines 24:0-32:1 -/
structure source.inference.Body where
  nodes : alloc.vec.Vec source.inference.Draft
  root : alloc.vec.Vec noble_kernel.untrusted.NodeId
  input : Std.U32
  output : Std.U32
  effect : Std.U32
  identity : Option Std.U64
  span : Span

/-- [noble_contracts::source::inference::State]
    Source: 'crates/noble-contracts/src/source/inference/mod.rs', lines 34:0-40:1 -/
structure source.inference.State where
  arena : inference.Arena
  bodies : alloc.vec.Vec source.inference.Body
  span : Span
  text_bytes : Std.U32
  definition_base : Std.Usize

/-- [noble_contracts::source::inference::BodyKey]
    Source: 'crates/noble-contracts/src/source/inference/mod.rs', lines 56:0-59:1 -/
@[discriminant isize]
inductive source.inference.BodyKey where
| Root : source.inference.BodyKey
| Quotation : Std.U32 → source.inference.BodyKey

/-- [noble_contracts::source::inference::TreeKey]
    Source: 'crates/noble-contracts/src/source/inference/mod.rs', lines 50:0-53:1 -/
@[discriminant isize]
inductive source.inference.TreeKey where
| Root : source.inference.TreeKey
| Named : Std.U32 → source.inference.TreeKey

/-- [noble_contracts::source::inference::Origin]
    Source: 'crates/noble-contracts/src/source/inference/mod.rs', lines 43:0-47:1 -/
@[discriminant isize]
inductive source.inference.Origin where
| Root : source.inference.Origin
| Quotation : Std.U32 → source.inference.Origin
| Named : source.inference.Origin

/-- [noble_contracts::source::inference::Frame]
    Source: 'crates/noble-contracts/src/source/inference/mod.rs', lines 66:0-78:1 -/
structure source.inference.Frame where
  tree : source.inference.TreeKey
  items : source.inference.BodyKey
  «at» : Std.Usize
  input : Std.U32
  stack : Std.U32
  effect : Std.U32
  body : Std.Usize
  sequence : alloc.vec.Vec noble_kernel.untrusted.NodeId
  origin : source.inference.Origin
  span : Span
  caller : Option Span

/-- [noble_contracts::source::inference::operations::Call]
    Source: 'crates/noble-contracts/src/source/inference/operations.rs', lines 1:0-4:1 -/
structure source.inference.operations.Call where
  id : Std.U32
  span : Span

/-- [noble_contracts::source::inference::Scope]
    Source: 'crates/noble-contracts/src/source/inference/mod.rs', lines 80:0-84:1 -/
structure source.inference.Scope where
  root : source.Tree
  session : source.Session
  environment : noble_kernel.contracts.Env

/-- [noble_contracts::inference::materialize::rendering::Part]
    Source: 'crates/noble-contracts/src/inference/materialize/rendering.rs', lines 1:0-7:1 -/
@[discriminant isize]
inductive inference.materialize.rendering.Part where
| Term : Std.U32 → inference.materialize.rendering.Part
| Space : inference.materialize.rendering.Part
| Close : inference.materialize.rendering.Part
| Comma : inference.materialize.rendering.Part
| Arrow : inference.materialize.rendering.Part

/-- [noble_contracts::inference::materialize::rendering::Traversal]
    Source: 'crates/noble-contracts/src/inference/materialize/rendering.rs', lines 9:0-12:1 -/
structure inference.materialize.rendering.Traversal where
  pending : alloc.vec.Vec inference.materialize.rendering.Part
  text : String

/-- [noble_contracts::inference::Program]
    Source: 'crates/noble-contracts/src/inference/mod.rs', lines 50:0-54:1 -/
structure inference.Program where
  input : Std.U32
  output : Std.U32
  effect : Std.U32

/-- [noble_contracts::inference::build::Step]
    Source: 'crates/noble-contracts/src/inference/build.rs', lines 2:0-14:1 -/
@[discriminant isize]
inductive inference.build.Step where
| Ty : noble_kernel.types.Ty → inference.build.Step
| Pattern : noble_kernel.shapes.Pattern → inference.build.Step
| StackTy : Slice noble_kernel.types.Ty → inference.build.Step
| StackPattern : Slice noble_kernel.shapes.Pattern → inference.build.Step
| StackTyParts :
  Slice noble_kernel.types.Ty →
  Std.Usize →
  inference.build.Step
| StackPatternParts :
  Slice noble_kernel.shapes.Pattern →
  Std.Usize →
  Std.Usize →
  inference.build.Step
| Pair : inference.build.Step
| Sum : inference.build.Step
| List : inference.build.Step
| Program : Option Std.U32 → inference.build.Step
| Push : inference.build.Step

/-- [noble_contracts::inference::build::State]
    Source: 'crates/noble-contracts/src/inference/build.rs', lines 16:0-19:1 -/
structure inference.build.State where
  steps : alloc.vec.Vec inference.build.Step
  values : alloc.vec.Vec Std.U32

/-- [noble_contracts::source::inference::Mode]
    Source: 'crates/noble-contracts/src/source/inference/mod.rs', lines 61:0-64:1 -/
@[discriminant isize]
inductive source.inference.Mode where
| Declaration : source.inference.Mode
| Submission : source.inference.Mode

/-- [noble_contracts::source::emission::CheckedBody]
    Source: 'crates/noble-contracts/src/source/emission/mod.rs', lines 25:0-30:1 -/
structure source.emission.CheckedBody where
  body : noble_kernel.execution.Body
  request : noble_kernel.untrusted.Request
  identity : Option Std.U64
  span : Span

/-- [noble_contracts::source::emission::Admission]
    Source: 'crates/noble-contracts/src/source/emission/mod.rs', lines 10:0-14:1 -/
structure source.emission.Admission where
  input_bytes : Std.U32
  limits : noble_kernel.untrusted.Limits
  environment : noble_kernel.contracts.Env

/-- [noble_contracts::source::emission::materialization::Nodes]
    Source: 'crates/noble-contracts/src/source/emission/materialization.rs', lines 69:0-73:1 -/
structure source.emission.materialization.Nodes where
  nodes : alloc.vec.Vec noble_kernel.untrusted.Node
  texts : alloc.vec.Vec noble_kernel.execution.TextLiteral
  spans : alloc.vec.Vec Span

/-- [noble_contracts::inference::materialize::Material]
    Source: 'crates/noble-contracts/src/inference/materialize.rs', lines 10:0-13:1 -/
@[discriminant isize]
inductive inference.materialize.Material where
| Value : noble_kernel.types.Ty → Std.U32 → inference.materialize.Material
| Stack :
  alloc.vec.Vec noble_kernel.types.Ty →
  Std.U32 →
  inference.materialize.Material

/-- [noble_contracts::inference::materialize::Step]
    Source: 'crates/noble-contracts/src/inference/materialize.rs', lines 4:0-7:1 -/
@[discriminant isize]
inductive inference.materialize.Step where
| Visit : Std.U32 → inference.materialize.Step
| Finish :
  inference.Term →
  noble_kernel.types.EffSet →
  inference.materialize.Step

/-- [noble_contracts::inference::materialize::State]
    Source: 'crates/noble-contracts/src/inference/materialize.rs', lines 15:0-18:1 -/
structure inference.materialize.State where
  steps : alloc.vec.Vec inference.materialize.Step
  values : alloc.vec.Vec inference.materialize.Material

/-- [noble_contracts::source::emission::allowance::{closure}]
    Source: 'crates/noble-contracts/src/source/emission/mod.rs', lines 229:18-229:55 -/
@[reducible]
def source.emission.allowance.closure := Meter

/-- [noble_contracts::source::emission::Assembly]
    Source: 'crates/noble-contracts/src/source/emission/mod.rs', lines 16:0-23:1 -/
structure source.emission.Assembly where
  definition_base : Std.Usize
  definitions : alloc.vec.Vec noble_kernel.execution.Definition
  root : Option (noble_kernel.execution.Body × noble_kernel.untrusted.Request)

/-- [noble_contracts::source::emission::contracts::patterns::Step]
    Source: 'crates/noble-contracts/src/source/emission/contracts/patterns.rs', lines 1:0-7:1 -/
@[discriminant isize]
inductive source.emission.contracts.patterns.Step where
| Visit :
  source.preflight.PathStep →
  Std.Usize →
  source.emission.contracts.patterns.Step
| Pair : source.emission.contracts.patterns.Step
| Sum : source.emission.contracts.patterns.Step
| List : source.emission.contracts.patterns.Step
| Program : Std.Usize → source.emission.contracts.patterns.Step

/-- [noble_contracts::source::emission::contracts::patterns::Traversal]
    Source: 'crates/noble-contracts/src/source/emission/contracts/patterns.rs', lines 9:0-13:1 -/
structure source.emission.contracts.patterns.Traversal where
  pending : alloc.vec.Vec source.emission.contracts.patterns.Step
  path : alloc.vec.Vec source.preflight.PathStep
  values : alloc.vec.Vec noble_kernel.shapes.Pattern

/-- [noble_contracts::component::preparation::{noble_contracts::component::World}::prepare_export::{closure}]
    Source: 'crates/noble-contracts/src/component/preparation.rs', lines 14:22-14:63 -/
@[reducible]
def component.preparation.World.prepare_export.closure := Str

/-- [noble_contracts::component::preparation::{noble_contracts::component::World}::check_import_effect::{closure#1}]
    Source: 'crates/noble-contracts/src/component/preparation.rs', lines 90:17-90:59 -/
@[reducible]
def component.preparation.World.check_import_effect.closure_1 :=
  component.Operation

/-- [noble_contracts::component::preparation::{noble_contracts::component::World}::check_import_effect::{closure}]
    Source: 'crates/noble-contracts/src/component/preparation.rs', lines 67:22-67:56 -/
@[reducible]
def component.preparation.World.check_import_effect.closure := Str

/-- [noble_contracts::syntax::Form]
    Source: 'crates/noble-contracts/src/syntax/mod.rs', lines 12:0-16:1 -/
@[discriminant isize]
inductive syntax.Form where
| Atom : syntax.Form
| Round : alloc.vec.Vec Std.U32 → syntax.Form
| Square : alloc.vec.Vec Std.U32 → syntax.Form

/-- [noble_contracts::syntax::Node]
    Source: 'crates/noble-contracts/src/syntax/mod.rs', lines 18:0-21:1 -/
structure syntax.Node where
  form : syntax.Form
  span : Span

/-- [noble_contracts::syntax::Tree]
    Source: 'crates/noble-contracts/src/syntax/mod.rs', lines 23:0-26:1 -/
structure syntax.Tree where
  nodes : alloc.vec.Vec syntax.Node
  root : Std.U32

/-- [noble_contracts::frontend::Container]
    Source: 'crates/noble-contracts/src/frontend.rs', lines 11:0-16:1 -/
structure frontend.Container where
  source : Slice Std.U8
  tree : syntax.Tree
  children : Slice Std.U32
  span : Span

/-- [noble_contracts::syntax::typing::Step]
    Source: 'crates/noble-contracts/src/syntax/typing.rs', lines 8:0-14:1 -/
@[discriminant isize]
inductive syntax.typing.Step where
| Visit : Std.U32 → syntax.typing.Step
| Pair : syntax.typing.Step
| Sum : syntax.typing.Step
| List : syntax.typing.Step
| Program : Std.Usize → Std.Usize → syntax.typing.Step

/-- [noble_contracts::syntax::typing::State]
    Source: 'crates/noble-contracts/src/syntax/typing.rs', lines 16:0-20:1 -/
structure syntax.typing.State where
  steps : alloc.vec.Vec syntax.typing.Step
  values : alloc.vec.Vec noble_kernel.types.Ty
  constructors : Std.U32

/-- [noble_contracts::syntax::typing::Context]
    Source: 'crates/noble-contracts/src/syntax/typing.rs', lines 2:0-5:1 -/
structure syntax.typing.Context where
  source : Slice Std.U8
  tree : syntax.Tree

/-- [noble_contracts::frontend::fields::Parts]
    Source: 'crates/noble-contracts/src/frontend/fields.rs', lines 1:0-11:1 -/
structure frontend.fields.Parts where
  input : Option Std.U32
  output : Option Std.U32
  params : Option Std.U32
  program : Option Std.U32
  requires : Option Std.U32
  ensures : Option Std.U32
  kind : Option Std.U32
  definitions : alloc.vec.Vec Std.U32
  failure : Option Diagnostic

/-- [noble_contracts::frontend::fields::Field]
    Source: 'crates/noble-contracts/src/frontend/fields.rs', lines 15:0-26:1 -/
@[discriminant isize]
inductive frontend.fields.Field where
| Input : frontend.fields.Field
| Output : frontend.fields.Field
| Program : frontend.fields.Field
| Params : frontend.fields.Field
| Requires : frontend.fields.Field
| Ensures : frontend.fields.Field
| Kind : frontend.fields.Field
| Definition : frontend.fields.Field
| Unsupported : frontend.fields.Field
| Unknown : frontend.fields.Field

/-- [noble_contracts::frontend::logic::Resolved]
    Source: 'crates/noble-contracts/src/frontend/logic.rs', lines 1:0-7:1 -/
structure frontend.logic.Resolved where
  params : alloc.vec.Vec NamedType
  definitions : alloc.vec.Vec LogicDef
  expressions : alloc.vec.Vec Expr
  requires : Std.U32
  ensures : Std.U32

/-- [noble_contracts::frontend::logic::Declarations]
    Source: 'crates/noble-contracts/src/frontend/logic.rs', lines 10:0-13:1 -/
structure frontend.logic.Declarations where
  ids : Slice Std.U32
  span : Span

/-- [noble_contracts::predicate::Arena]
    Source: 'crates/noble-contracts/src/predicate.rs', lines 24:0-26:1 -/
structure predicate.Arena where
  expressions : alloc.vec.Vec Expr

/-- [noble_contracts::predicate::Context]
    Source: 'crates/noble-contracts/src/predicate.rs', lines 15:0-22:1 -/
structure predicate.Context where
  source : Slice Std.U8
  tree : syntax.Tree
  inputs : Slice NamedType
  outputs : Slice NamedType
  params : Slice NamedType
  definitions : Slice LogicDef

/-- [noble_contracts::predicate::Op]
    Source: 'crates/noble-contracts/src/predicate.rs', lines 71:0-97:1 -/
@[discriminant isize]
inductive predicate.Op where
| Not : predicate.Op
| And : predicate.Op
| Or : predicate.Op
| Implies : predicate.Op
| Eq : predicate.Op
| Lt : predicate.Op
| Le : predicate.Op
| Add : predicate.Op
| Sub : predicate.Op
| Mul : predicate.Op
| Pair : predicate.Op
| First : predicate.Op
| Second : predicate.Op
| Inl : predicate.Op
| Inr : predicate.Op
| IsLeft : predicate.Op
| Left : predicate.Op
| Right : predicate.Op
| Nil : predicate.Op
| Cons : predicate.Op
| IsNil : predicate.Op
| Head : predicate.Op
| Tail : predicate.Op
| Length : predicate.Op
| Maps : predicate.Op

/-- [noble_contracts::predicate::resolving::Round]
    Source: 'crates/noble-contracts/src/predicate/resolving.rs', lines 14:0-17:1 -/
structure predicate.resolving.Round where
  children : Slice Std.U32
  span : Span

/-- [noble_contracts::predicate::application::Form]
    Source: 'crates/noble-contracts/src/predicate/application.rs', lines 1:0-5:1 -/
structure predicate.application.Form where
  op : predicate.Op
  annotation : Option noble_kernel.types.Ty
  span : Span

/-- [noble_contracts::predicate::resolving::Step]
    Source: 'crates/noble-contracts/src/predicate/resolving.rs', lines 2:0-5:1 -/
@[discriminant isize]
inductive predicate.resolving.Step where
| Visit : Std.U32 → predicate.resolving.Step
| Finish : predicate.application.Form → predicate.resolving.Step

/-- [noble_contracts::predicate::resolving::State]
    Source: 'crates/noble-contracts/src/predicate/resolving.rs', lines 7:0-11:1 -/
structure predicate.resolving.State where
  span : Span
  steps : alloc.vec.Vec predicate.resolving.Step
  values : alloc.vec.Vec Std.U32

/-- [noble_contracts::predicate::references::Namespace]
    Source: 'crates/noble-contracts/src/predicate/references.rs', lines 15:0-19:1 -/
@[discriminant isize]
inductive predicate.references.Namespace where
| Input : predicate.references.Namespace
| Output : predicate.references.Namespace
| Param : predicate.references.Namespace

/-- [noble_contracts::predicate::references::Search]
    Source: 'crates/noble-contracts/src/predicate/references.rs', lines 8:0-11:1 -/
structure predicate.references.Search where
  «name» : Slice Std.U8
  span : Span

/-- [noble_contracts::predicate::references::Reference]
    Source: 'crates/noble-contracts/src/predicate/references.rs', lines 1:0-5:1 -/
structure predicate.references.Reference where
  operator : Slice Std.U8
  «name» : Slice Std.U8
  span : Span

/-- [noble_contracts::predicate::application::Operand]
    Source: 'crates/noble-contracts/src/predicate/application.rs', lines 8:0-11:1 -/
structure predicate.application.Operand where
  id : Std.U32
  expr : Expr

/-- [noble_contracts::predicate::structural::Traversal]
    Source: 'crates/noble-contracts/src/predicate/structural.rs', lines 1:0-3:1 -/
structure predicate.structural.Traversal where
  pending : alloc.vec.Vec noble_kernel.types.Ty

/-- [noble_contracts::syntax::parsing::Frame]
    Source: 'crates/noble-contracts/src/syntax/parsing.rs', lines 1:0-5:1 -/
structure syntax.parsing.Frame where
  start : Std.U32
  is_square : Bool
  children : alloc.vec.Vec Std.U32

/-- [noble_contracts::syntax::parsing::State]
    Source: 'crates/noble-contracts/src/syntax/parsing.rs', lines 7:0-12:1 -/
structure syntax.parsing.State where
  tree : syntax.Tree
  frames : alloc.vec.Vec syntax.parsing.Frame
  root : Option Std.U32
  position : Std.Usize

/-- [noble_contracts::program::DraftKind]
    Source: 'crates/noble-contracts/src/program.rs', lines 50:0-54:1 -/
@[discriminant isize]
inductive program.DraftKind where
| Literal : noble_kernel.untrusted.Lit → program.DraftKind
| Invocation : noble_kernel.contracts.Definition → program.DraftKind
| Quotation : alloc.vec.Vec noble_kernel.untrusted.NodeId → program.DraftKind

/-- [noble_contracts::program::Draft]
    Source: 'crates/noble-contracts/src/program.rs', lines 56:0-61:1 -/
structure program.Draft where
  kind : program.DraftKind
  «variables» : alloc.vec.Vec inference.Variable
  explicit : Option noble_kernel.words.Inst
  span : Span

/-- [noble_contracts::program::Frame]
    Source: 'crates/noble-contracts/src/program.rs', lines 40:0-47:1 -/
structure program.Frame where
  «syntax» : Std.U32
  position : Std.Usize
  stack : Std.U32
  expected : Std.U32
  body : alloc.vec.Vec noble_kernel.untrusted.NodeId
  origin : Option (Std.U32 × Std.U32 × Std.U32 × Span)

/-- [noble_contracts::program::Resolution]
    Source: 'crates/noble-contracts/src/program.rs', lines 63:0-69:1 -/
structure program.Resolution where
  span : Span
  arena : inference.Arena
  frames : alloc.vec.Vec program.Frame
  drafts : alloc.vec.Vec (Option program.Draft)
  body : alloc.vec.Vec noble_kernel.untrusted.NodeId

/-- [noble_contracts::program::Context]
    Source: 'crates/noble-contracts/src/program.rs', lines 28:0-32:1 -/
structure program.Context where
  source : Slice Std.U8
  tree : syntax.Tree
  env : noble_kernel.contracts.Env

/-- [noble_contracts::program::Form]
    Source: 'crates/noble-contracts/src/program.rs', lines 35:0-38:1 -/
structure program.Form where
  children : Slice Std.U32
  span : Span

/-- [noble_contracts::program::words::Call]
    Source: 'crates/noble-contracts/src/program/words.rs', lines 1:0-6:1 -/
structure program.words.Call where
  «def» : noble_kernel.contracts.Definition
  current : Std.U32
  explicit : Option noble_kernel.words.Inst
  span : Span

/-- [noble_contracts::program::witness::Bindings]
    Source: 'crates/noble-contracts/src/program/witness.rs', lines 9:0-13:1 -/
structure program.witness.Bindings where
  values : Slice noble_kernel.words.Binding
  «variables» : Slice inference.Variable
  span : Span

/-- [noble_contracts::program::witness::Explicit]
    Source: 'crates/noble-contracts/src/program/witness.rs', lines 1:0-6:1 -/
structure program.witness.Explicit where
  inst : noble_kernel.words.Inst
  kinds : Slice noble_kernel.words.VariableKind
  «variables» : Slice inference.Variable
  span : Span

end noble_contracts
