-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [noble_contracts]: type definitions
import Aeneas
import NobleContractImpl.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace noble_contracts

/-- [noble_kernel::untrusted::NodeId]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 18:0-18:17
    Name pattern: [noble_kernel::untrusted::NodeId]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::untrusted::NodeId"]
def noble_kernel.untrusted.NodeId := Std.U32

/-- [noble_kernel::types::ResourceKind]
    Source: 'crates/noble-kernel/src/types.rs', lines 15:0-15:23
    Name pattern: [noble_kernel::types::ResourceKind]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::types::ResourceKind"]
def noble_kernel.types.ResourceKind := Std.U32

/-- [noble_kernel::types::Ty]
    Source: 'crates/noble-kernel/src/types.rs', lines 157:0-157:11
    Name pattern: [noble_kernel::types::Ty]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::types::Ty"]
inductive noble_kernel.types.Ty where
| UnitType : noble_kernel.types.Ty
| BoolType : noble_kernel.types.Ty
| I64Type : noble_kernel.types.Ty
| TextType : noble_kernel.types.Ty
| SyntaxType : noble_kernel.types.Ty
| PairType :
  noble_kernel.types.Ty →
  noble_kernel.types.Ty →
  noble_kernel.types.Ty
| SumType :
  noble_kernel.types.Ty →
  noble_kernel.types.Ty →
  noble_kernel.types.Ty
| ListType : noble_kernel.types.Ty → noble_kernel.types.Ty
| ProgramType :
  alloc.vec.Vec noble_kernel.types.Ty →
  alloc.vec.Vec noble_kernel.types.Ty →
  noble_kernel.types.EffSet →
  noble_kernel.types.Ty
| ResourceType : noble_kernel.types.ResourceKind → noble_kernel.types.Ty

/-- [noble_kernel::types::EffId]
    Source: 'crates/noble-kernel/src/types.rs', lines 26:0-26:16
    Name pattern: [noble_kernel::types::EffId]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::types::EffId"]
def noble_kernel.types.EffId := Std.U32

/-- [noble_kernel::contracts::Definition]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 11:0-11:21
    Name pattern: [noble_kernel::contracts::Definition]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::contracts::Definition"]
def noble_kernel.contracts.Definition := Std.U32

/-- [noble_kernel::untrusted::Constraint]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 206:0-206:19
    Name pattern: [noble_kernel::untrusted::Constraint]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Constraint"]
inductive noble_kernel.untrusted.Constraint where
| StackJoin : noble_kernel.untrusted.Constraint
| StackOrder : noble_kernel.untrusted.Constraint
| EffectInclusion :
  noble_kernel.types.EffId →
  noble_kernel.untrusted.Constraint
| Eligibility : noble_kernel.types.Ty → noble_kernel.untrusted.Constraint
| UnknownEffect :
  noble_kernel.types.EffId →
  noble_kernel.untrusted.Constraint
| InstantiationKind : noble_kernel.untrusted.Constraint
| InstantiationArity : noble_kernel.untrusted.Constraint
| MalformedReference :
  noble_kernel.untrusted.NodeId →
  noble_kernel.untrusted.Constraint
| UnknownDefinition :
  noble_kernel.contracts.Definition →
  noble_kernel.untrusted.Constraint
| CyclicWitness : noble_kernel.untrusted.Constraint

/-- [noble_kernel::untrusted::Diagnostic]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 232:0-232:21
    Name pattern: [noble_kernel::untrusted::Diagnostic]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Diagnostic"]
structure noble_kernel.untrusted.Diagnostic where
  node : Option noble_kernel.untrusted.NodeId
  «def» : Option noble_kernel.contracts.Definition
  expected : alloc.vec.Vec noble_kernel.types.Ty
  actual : alloc.vec.Vec noble_kernel.types.Ty
  constraint : noble_kernel.untrusted.Constraint
  provenance_available : Bool
  truncated : Bool

/-- [noble_kernel::contracts::SchemaId]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 21:0-21:19
    Name pattern: [noble_kernel::contracts::SchemaId]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::contracts::SchemaId"]
def noble_kernel.contracts.SchemaId := Std.U32

/-- [noble_kernel::untrusted::UnsupportedKind]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 187:0-187:24
    Name pattern: [noble_kernel::untrusted::UnsupportedKind]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::UnsupportedKind"]
inductive noble_kernel.untrusted.UnsupportedKind where
| FormatRevision : noble_kernel.untrusted.UnsupportedKind
| NodeForm : noble_kernel.untrusted.UnsupportedKind
| SchemeForm : noble_kernel.untrusted.UnsupportedKind
| RecursiveDependency :
  noble_kernel.contracts.Definition →
  noble_kernel.untrusted.UnsupportedKind
| RecursiveSchema :
  noble_kernel.contracts.SchemaId →
  noble_kernel.untrusted.UnsupportedKind

/-- [noble_kernel::untrusted::LimitKind]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 168:0-168:18
    Name pattern: [noble_kernel::untrusted::LimitKind]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::LimitKind"]
inductive noble_kernel.untrusted.LimitKind where
| Bytes : noble_kernel.untrusted.LimitKind
| Nodes : noble_kernel.untrusted.LimitKind
| Depth : noble_kernel.untrusted.LimitKind
| TypeSize : noble_kernel.untrusted.LimitKind
| StackHeight : noble_kernel.untrusted.LimitKind
| Work : noble_kernel.untrusted.LimitKind
| Diagnostics : noble_kernel.untrusted.LimitKind

/-- [noble_kernel::untrusted::Interface]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 139:0-139:20
    Name pattern: [noble_kernel::untrusted::Interface]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Interface"]
structure noble_kernel.untrusted.Interface where
  stack_in : alloc.vec.Vec noble_kernel.types.Ty
  stack_out : alloc.vec.Vec noble_kernel.types.Ty
  effects : noble_kernel.types.EffSet

/-- [noble_kernel::untrusted::Derivation]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 150:0-150:21
    Name pattern: [noble_kernel::untrusted::Derivation]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Derivation"]
structure noble_kernel.untrusted.Derivation where
  node : noble_kernel.untrusted.NodeId
  interface : noble_kernel.untrusted.Interface

/-- [noble_kernel::untrusted::Checked]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 159:0-159:18
    Name pattern: [noble_kernel::untrusted::Checked]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Checked"]
structure noble_kernel.untrusted.Checked where
  interface : noble_kernel.untrusted.Interface
  derivations : alloc.vec.Vec noble_kernel.untrusted.Derivation

/-- [noble_kernel::untrusted::Outcome]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 251:0-251:16
    Name pattern: [noble_kernel::untrusted::Outcome]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Outcome"]
inductive noble_kernel.untrusted.Outcome where
| Accepted : noble_kernel.untrusted.Checked → noble_kernel.untrusted.Outcome
| Invalid :
  noble_kernel.untrusted.Diagnostic →
  noble_kernel.untrusted.Outcome
| Unsupported :
  noble_kernel.untrusted.UnsupportedKind →
  noble_kernel.untrusted.Outcome
| Exhausted :
  noble_kernel.untrusted.LimitKind →
  noble_kernel.untrusted.Outcome
| InternalFailure : noble_kernel.untrusted.Outcome

/-- [noble_kernel::untrusted::Limits]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 104:0-104:17
    Name pattern: [noble_kernel::untrusted::Limits]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Limits"]
structure noble_kernel.untrusted.Limits where
  bytes : Std.U32
  nodes : Std.U32
  depth : Std.U32
  type_size : Std.U32
  stack_height : Std.U32
  work : Std.U32
  diagnostics : Std.U32

/-- [noble_kernel::untrusted::Expected]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 93:0-93:19
    Name pattern: [noble_kernel::untrusted::Expected]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Expected"]
structure noble_kernel.untrusted.Expected where
  stack_in : alloc.vec.Vec noble_kernel.types.Ty
  stack_out : alloc.vec.Vec noble_kernel.types.Ty
  allowed_effects : noble_kernel.types.EffSet

/-- [noble_kernel::untrusted::Request]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 127:0-127:18
    Name pattern: [noble_kernel::untrusted::Request]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Request"]
structure noble_kernel.untrusted.Request where
  input_bytes : Std.U32
  expected : noble_kernel.untrusted.Expected
  limits : noble_kernel.untrusted.Limits

/-- [noble_kernel::words::Variable]
    Source: 'crates/noble-kernel/src/words.rs', lines 18:0-18:19
    Name pattern: [noble_kernel::words::Variable]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::words::Variable"]
def noble_kernel.words.Variable := Std.U32

/-- [noble_kernel::words::Binding]
    Source: 'crates/noble-kernel/src/words.rs', lines 48:0-48:16
    Name pattern: [noble_kernel::words::Binding]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::words::Binding"]
inductive noble_kernel.words.Binding where
| Stack : alloc.vec.Vec noble_kernel.types.Ty → noble_kernel.words.Binding
| Value : noble_kernel.types.Ty → noble_kernel.words.Binding
| Effect : noble_kernel.types.EffSet → noble_kernel.words.Binding
| Ref : noble_kernel.words.Variable → noble_kernel.words.Binding

/-- [noble_kernel::words::Inst]
    Source: 'crates/noble-kernel/src/words.rs', lines 64:0-64:15
    Name pattern: [noble_kernel::words::Inst]
    Visibility: public -/
@[rust_type "noble_kernel::words::Inst"]
structure noble_kernel.words.Inst where
  bindings : alloc.vec.Vec noble_kernel.words.Binding

/-- [noble_kernel::untrusted::Lit]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 27:0-27:12
    Name pattern: [noble_kernel::untrusted::Lit]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Lit"]
inductive noble_kernel.untrusted.Lit where
| I64Lit : Std.I64 → noble_kernel.untrusted.Lit
| BoolLit : Bool → noble_kernel.untrusted.Lit
| TextLit : noble_kernel.untrusted.Lit
| UnitLit : noble_kernel.untrusted.Lit

/-- [noble_kernel::untrusted::Node]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 53:0-53:13
    Name pattern: [noble_kernel::untrusted::Node]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Node"]
inductive noble_kernel.untrusted.Node where
| Literal :
  noble_kernel.untrusted.Lit →
  noble_kernel.words.Inst →
  noble_kernel.untrusted.Node
| Invocation :
  noble_kernel.contracts.Definition →
  noble_kernel.words.Inst →
  noble_kernel.untrusted.Node
| Quotation :
  alloc.vec.Vec noble_kernel.untrusted.NodeId →
  noble_kernel.words.Inst →
  noble_kernel.untrusted.Node

/-- [noble_kernel::untrusted::Candidate]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 80:0-80:20
    Name pattern: [noble_kernel::untrusted::Candidate]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Candidate"]
structure noble_kernel.untrusted.Candidate where
  format : Std.U32
  revision : Std.U32
  nodes : alloc.vec.Vec noble_kernel.untrusted.Node
  body : alloc.vec.Vec noble_kernel.untrusted.NodeId

/-- [noble_kernel::words::VariableKind]
    Source: 'crates/noble-kernel/src/words.rs', lines 22:0-22:21
    Name pattern: [noble_kernel::words::VariableKind]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::words::VariableKind"]
inductive noble_kernel.words.VariableKind where
| Stack : noble_kernel.words.VariableKind
| Value : noble_kernel.words.VariableKind
| Effect : noble_kernel.words.VariableKind

/-- [noble_kernel::shapes::EffectSlot]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 74:0-74:19
    Name pattern: [noble_kernel::shapes::EffectSlot]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::shapes::EffectSlot"]
inductive noble_kernel.shapes.EffectSlot where
| Effect : noble_kernel.types.EffId → noble_kernel.shapes.EffectSlot
| Var : noble_kernel.words.Variable → noble_kernel.shapes.EffectSlot

/-- [noble_kernel::shapes::Pattern]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 26:0-26:16
    Name pattern: [noble_kernel::shapes::Pattern]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::shapes::Pattern"]
inductive noble_kernel.shapes.Pattern where
| UnitPattern : noble_kernel.shapes.Pattern
| BoolPattern : noble_kernel.shapes.Pattern
| I64Pattern : noble_kernel.shapes.Pattern
| TextPattern : noble_kernel.shapes.Pattern
| SyntaxPattern : noble_kernel.shapes.Pattern
| PairPattern :
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern
| SumPattern :
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern
| ListPattern : noble_kernel.shapes.Pattern → noble_kernel.shapes.Pattern
| ProgramPattern :
  alloc.vec.Vec noble_kernel.shapes.Pattern →
  alloc.vec.Vec noble_kernel.shapes.Pattern →
  alloc.vec.Vec noble_kernel.shapes.EffectSlot →
  noble_kernel.shapes.Pattern
| ResourcePattern :
  noble_kernel.types.ResourceKind →
  noble_kernel.shapes.Pattern
| VarPattern : noble_kernel.words.Variable → noble_kernel.shapes.Pattern
| StackVarPattern : noble_kernel.words.Variable → noble_kernel.shapes.Pattern

/-- [noble_kernel::words::Scheme]
    Source: 'crates/noble-kernel/src/words.rs', lines 34:0-34:17
    Name pattern: [noble_kernel::words::Scheme]
    Visibility: public -/
@[rust_type "noble_kernel::words::Scheme"]
structure noble_kernel.words.Scheme where
  var_kinds : alloc.vec.Vec noble_kernel.words.VariableKind
  stack_in : alloc.vec.Vec noble_kernel.shapes.Pattern
  stack_out : alloc.vec.Vec noble_kernel.shapes.Pattern
  effects : alloc.vec.Vec noble_kernel.shapes.EffectSlot

/-- [noble_kernel::contracts::SchemaDecl]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 83:0-83:21
    Name pattern: [noble_kernel::contracts::SchemaDecl]
    Visibility: public -/
@[rust_type "noble_kernel::contracts::SchemaDecl"]
structure noble_kernel.contracts.SchemaDecl where
  id : noble_kernel.contracts.SchemaId
  scheme : noble_kernel.words.Scheme
  recursive : Bool

/-- [noble_kernel::contracts::Behavior]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 30:0-30:17
    Name pattern: [noble_kernel::contracts::Behavior]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::contracts::Behavior"]
inductive noble_kernel.contracts.Behavior where
| DupBehavior : noble_kernel.contracts.Behavior
| DropBehavior : noble_kernel.contracts.Behavior
| SwapBehavior : noble_kernel.contracts.Behavior
| DipBehavior : noble_kernel.contracts.Behavior
| ArithBehavior : noble_kernel.contracts.Behavior
| EqualsBehavior : noble_kernel.contracts.Behavior
| QuoteBehavior : noble_kernel.contracts.Behavior
| ComposeBehavior : noble_kernel.contracts.Behavior
| RunBehavior : noble_kernel.contracts.Behavior
| ReflectBehavior : noble_kernel.contracts.Behavior
| UnitBehavior : noble_kernel.contracts.Behavior
| PairBehavior : noble_kernel.contracts.Behavior
| UnpairBehavior : noble_kernel.contracts.Behavior
| InlBehavior : noble_kernel.contracts.Behavior
| InrBehavior : noble_kernel.contracts.Behavior
| CaseBehavior : noble_kernel.contracts.Behavior
| IfBehavior : noble_kernel.contracts.Behavior
| NilBehavior : noble_kernel.contracts.Behavior
| ConsBehavior : noble_kernel.contracts.Behavior
| ListCaseBehavior : noble_kernel.contracts.Behavior
| TestEmitBehavior : noble_kernel.contracts.Behavior
| NamedBehavior : noble_kernel.contracts.Behavior

/-- [noble_kernel::contracts::Env]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 94:0-94:14
    Name pattern: [noble_kernel::contracts::Env]
    Visibility: public -/
@[rust_type "noble_kernel::contracts::Env"]
structure noble_kernel.contracts.Env where
  defs : alloc.vec.Vec noble_kernel.words.Scheme
  kinds : alloc.vec.Vec noble_kernel.contracts.Behavior
  deps : alloc.vec.Vec (alloc.vec.Vec noble_kernel.contracts.Definition)
  schemas : alloc.vec.Vec noble_kernel.contracts.SchemaDecl
  effects : alloc.vec.Vec noble_kernel.types.EffId

/-- [noble_kernel::shapes::Defect]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 83:0-83:15
    Name pattern: [noble_kernel::shapes::Defect]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::shapes::Defect"]
inductive noble_kernel.shapes.Defect where
| UnknownVariable : noble_kernel.shapes.Defect
| KindMismatch : noble_kernel.shapes.Defect

/-- [noble_kernel::words::InstError]
    Source: 'crates/noble-kernel/src/words.rs', lines 71:0-71:18
    Name pattern: [noble_kernel::words::InstError]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::words::InstError"]
inductive noble_kernel.words.InstError where
| KindMismatch : noble_kernel.words.InstError
| UnknownVariable : noble_kernel.words.InstError
| ArityMismatch : noble_kernel.words.InstError
| OversizedStack : noble_kernel.words.InstError
| OversizedType : noble_kernel.words.InstError
| OversizedEffects : noble_kernel.words.InstError
| CyclicWitness : noble_kernel.words.InstError
| WalkExhausted : noble_kernel.words.InstError

/-- [noble_contracts::Limits]
    Source: 'crates/noble-contracts/src/lib.rs', lines 26:0-31:1
    Visibility: public -/
structure Limits where
  bytes : Std.U32
  nodes : Std.U32
  depth : Std.U32
  work : Std.U32

/-- [noble_contracts::Meter]
    Source: 'crates/noble-contracts/src/lib.rs', lines 213:0-217:1 -/
structure Meter where
  limits : Limits
  work : Std.U32
  nodes : Std.U32

/-- [noble_contracts::NamedType]
    Source: 'crates/noble-contracts/src/lib.rs', lines 87:0-90:1
    Visibility: public -/
structure NamedType where
  «name» : String
  ty : noble_kernel.types.Ty

/-- [noble_contracts::DiagnosticKind]
    Source: 'crates/noble-contracts/src/lib.rs', lines 51:0-56:1
    Visibility: public -/
@[discriminant isize]
inductive DiagnosticKind where
| Invalid : DiagnosticKind
| Unsupported : DiagnosticKind
| Exhausted : DiagnosticKind
| Internal : DiagnosticKind

/-- [noble_contracts::Span]
    Source: 'crates/noble-contracts/src/lib.rs', lines 45:0-48:1
    Visibility: public -/
structure Span where
  start : Std.U32
  «end» : Std.U32

/-- [noble_contracts::Diagnostic]
    Source: 'crates/noble-contracts/src/lib.rs', lines 59:0-64:1
    Visibility: public -/
structure Diagnostic where
  kind : DiagnosticKind
  span : Span
  message : String
  ordinary_typing : Option noble_kernel.untrusted.Checked

/-- [noble_contracts::syntax::Form]
    Source: 'crates/noble-contracts/src/syntax/mod.rs', lines 7:0-11:1 -/
@[discriminant isize]
inductive syntax.Form where
| Atom : syntax.Form
| Round : alloc.vec.Vec Std.U32 → syntax.Form
| Square : alloc.vec.Vec Std.U32 → syntax.Form

/-- [noble_contracts::syntax::Node]
    Source: 'crates/noble-contracts/src/syntax/mod.rs', lines 13:0-16:1 -/
structure syntax.Node where
  form : syntax.Form
  span : Span

/-- [noble_contracts::syntax::Tree]
    Source: 'crates/noble-contracts/src/syntax/mod.rs', lines 18:0-21:1 -/
structure syntax.Tree where
  nodes : alloc.vec.Vec syntax.Node
  root : Std.U32

/-- [noble_contracts::frontend::Container]
    Source: 'crates/noble-contracts/src/frontend.rs', lines 6:0-11:1 -/
structure frontend.Container where
  source : Slice Std.U8
  tree : syntax.Tree
  children : Slice Std.U32
  span : Span

/-- [noble_contracts::syntax::typing::Step]
    Source: 'crates/noble-contracts/src/syntax/typing.rs', lines 8:0-14:1 -/
@[discriminant isize]
inductive syntax.typing.Step where
| Visit : Std.U32 → syntax.typing.Step
| Pair : syntax.typing.Step
| Sum : syntax.typing.Step
| List : syntax.typing.Step
| Program : Std.Usize → Std.Usize → syntax.typing.Step

/-- [noble_contracts::syntax::typing::State]
    Source: 'crates/noble-contracts/src/syntax/typing.rs', lines 16:0-20:1 -/
structure syntax.typing.State where
  steps : alloc.vec.Vec syntax.typing.Step
  values : alloc.vec.Vec noble_kernel.types.Ty
  constructors : Std.U32

/-- [noble_contracts::syntax::typing::Context]
    Source: 'crates/noble-contracts/src/syntax/typing.rs', lines 2:0-5:1 -/
structure syntax.typing.Context where
  source : Slice Std.U8
  tree : syntax.Tree

/-- [noble_contracts::frontend::fields::Parts]
    Source: 'crates/noble-contracts/src/frontend/fields.rs', lines 1:0-11:1 -/
structure frontend.fields.Parts where
  input : Option Std.U32
  output : Option Std.U32
  params : Option Std.U32
  program : Option Std.U32
  requires : Option Std.U32
  ensures : Option Std.U32
  kind : Option Std.U32
  definitions : alloc.vec.Vec Std.U32
  failure : Option Diagnostic

/-- [noble_contracts::frontend::fields::Field]
    Source: 'crates/noble-contracts/src/frontend/fields.rs', lines 15:0-26:1 -/
@[discriminant isize]
inductive frontend.fields.Field where
| Input : frontend.fields.Field
| Output : frontend.fields.Field
| Program : frontend.fields.Field
| Params : frontend.fields.Field
| Requires : frontend.fields.Field
| Ensures : frontend.fields.Field
| Kind : frontend.fields.Field
| Definition : frontend.fields.Field
| Unsupported : frontend.fields.Field
| Unknown : frontend.fields.Field

/-- [noble_contracts::ExprKind]
    Source: 'crates/noble-contracts/src/lib.rs', lines 122:0-155:1
    Visibility: public -/
@[discriminant isize]
inductive ExprKind where
| I64Expr : Std.I64 → ExprKind
| BoolExpr : Bool → ExprKind
| UnitExpr : ExprKind
| InputExpr : Std.U32 → ExprKind
| OutputExpr : Std.U32 → ExprKind
| ParamExpr : Std.U32 → ExprKind
| DefinitionExpr : Std.U32 → ExprKind
| NotExpr : Std.U32 → ExprKind
| AndExpr : Std.U32 → Std.U32 → ExprKind
| OrExpr : Std.U32 → Std.U32 → ExprKind
| ImpliesExpr : Std.U32 → Std.U32 → ExprKind
| EqExpr : Std.U32 → Std.U32 → ExprKind
| LtExpr : Std.U32 → Std.U32 → ExprKind
| LeExpr : Std.U32 → Std.U32 → ExprKind
| AddExpr : Std.U32 → Std.U32 → ExprKind
| SubExpr : Std.U32 → Std.U32 → ExprKind
| MulExpr : Std.U32 → Std.U32 → ExprKind
| PairExpr : Std.U32 → Std.U32 → ExprKind
| FirstExpr : Std.U32 → ExprKind
| SecondExpr : Std.U32 → ExprKind
| InlExpr : Std.U32 → ExprKind
| InrExpr : Std.U32 → ExprKind
| IsLeftExpr : Std.U32 → ExprKind
| LeftExpr : Std.U32 → ExprKind
| RightExpr : Std.U32 → ExprKind
| NilExpr : ExprKind
| ConsExpr : Std.U32 → Std.U32 → ExprKind
| IsNilExpr : Std.U32 → ExprKind
| HeadExpr : Std.U32 → ExprKind
| TailExpr : Std.U32 → ExprKind
| LengthExpr : Std.U32 → ExprKind
| MapsExpr : Std.U32 → Std.U32 → Std.U32 → ExprKind

/-- [noble_contracts::Expr]
    Source: 'crates/noble-contracts/src/lib.rs', lines 100:0-106:1
    Visibility: public -/
structure Expr where
  kind : ExprKind
  ty : noble_kernel.types.Ty
  span : Span
  total : Bool
  uses_output : Bool

/-- [noble_contracts::LogicDef]
    Source: 'crates/noble-contracts/src/lib.rs', lines 93:0-97:1
    Visibility: public -/
structure LogicDef where
  «name» : String
  ty : noble_kernel.types.Ty
  body : Std.U32

/-- [noble_contracts::frontend::logic::Resolved]
    Source: 'crates/noble-contracts/src/frontend/logic.rs', lines 1:0-7:1 -/
structure frontend.logic.Resolved where
  params : alloc.vec.Vec NamedType
  definitions : alloc.vec.Vec LogicDef
  expressions : alloc.vec.Vec Expr
  requires : Std.U32
  ensures : Std.U32

/-- [noble_contracts::frontend::logic::Declarations]
    Source: 'crates/noble-contracts/src/frontend/logic.rs', lines 10:0-13:1 -/
structure frontend.logic.Declarations where
  ids : Slice Std.U32
  span : Span

/-- [noble_contracts::predicate::Arena]
    Source: 'crates/noble-contracts/src/predicate.rs', lines 19:0-21:1 -/
structure predicate.Arena where
  expressions : alloc.vec.Vec Expr

/-- [noble_contracts::predicate::Context]
    Source: 'crates/noble-contracts/src/predicate.rs', lines 10:0-17:1 -/
structure predicate.Context where
  source : Slice Std.U8
  tree : syntax.Tree
  inputs : Slice NamedType
  outputs : Slice NamedType
  params : Slice NamedType
  definitions : Slice LogicDef

/-- [noble_contracts::predicate::Op]
    Source: 'crates/noble-contracts/src/predicate.rs', lines 66:0-92:1 -/
@[discriminant isize]
inductive predicate.Op where
| Not : predicate.Op
| And : predicate.Op
| Or : predicate.Op
| Implies : predicate.Op
| Eq : predicate.Op
| Lt : predicate.Op
| Le : predicate.Op
| Add : predicate.Op
| Sub : predicate.Op
| Mul : predicate.Op
| Pair : predicate.Op
| First : predicate.Op
| Second : predicate.Op
| Inl : predicate.Op
| Inr : predicate.Op
| IsLeft : predicate.Op
| Left : predicate.Op
| Right : predicate.Op
| Nil : predicate.Op
| Cons : predicate.Op
| IsNil : predicate.Op
| Head : predicate.Op
| Tail : predicate.Op
| Length : predicate.Op
| Maps : predicate.Op

/-- [noble_contracts::predicate::resolving::Round]
    Source: 'crates/noble-contracts/src/predicate/resolving.rs', lines 14:0-17:1 -/
structure predicate.resolving.Round where
  children : Slice Std.U32
  span : Span

/-- [noble_contracts::predicate::application::Form]
    Source: 'crates/noble-contracts/src/predicate/application.rs', lines 1:0-5:1 -/
structure predicate.application.Form where
  op : predicate.Op
  annotation : Option noble_kernel.types.Ty
  span : Span

/-- [noble_contracts::predicate::resolving::Step]
    Source: 'crates/noble-contracts/src/predicate/resolving.rs', lines 2:0-5:1 -/
@[discriminant isize]
inductive predicate.resolving.Step where
| Visit : Std.U32 → predicate.resolving.Step
| Finish : predicate.application.Form → predicate.resolving.Step

/-- [noble_contracts::predicate::resolving::State]
    Source: 'crates/noble-contracts/src/predicate/resolving.rs', lines 7:0-11:1 -/
structure predicate.resolving.State where
  span : Span
  steps : alloc.vec.Vec predicate.resolving.Step
  values : alloc.vec.Vec Std.U32

/-- [noble_contracts::predicate::references::Namespace]
    Source: 'crates/noble-contracts/src/predicate/references.rs', lines 15:0-19:1 -/
@[discriminant isize]
inductive predicate.references.Namespace where
| Input : predicate.references.Namespace
| Output : predicate.references.Namespace
| Param : predicate.references.Namespace

/-- [noble_contracts::predicate::references::Search]
    Source: 'crates/noble-contracts/src/predicate/references.rs', lines 8:0-11:1 -/
structure predicate.references.Search where
  «name» : Slice Std.U8
  span : Span

/-- [noble_contracts::predicate::references::Reference]
    Source: 'crates/noble-contracts/src/predicate/references.rs', lines 1:0-5:1 -/
structure predicate.references.Reference where
  operator : Slice Std.U8
  «name» : Slice Std.U8
  span : Span

/-- [noble_contracts::syntax::integer::Accumulator]
    Source: 'crates/noble-contracts/src/syntax/integer.rs', lines 1:0-4:1 -/
structure syntax.integer.Accumulator where
  value : Std.I64
  is_negative : Bool

/-- [noble_contracts::predicate::application::Operand]
    Source: 'crates/noble-contracts/src/predicate/application.rs', lines 8:0-11:1 -/
structure predicate.application.Operand where
  id : Std.U32
  expr : Expr

/-- [noble_contracts::predicate::structural::Traversal]
    Source: 'crates/noble-contracts/src/predicate/structural.rs', lines 1:0-3:1 -/
structure predicate.structural.Traversal where
  pending : alloc.vec.Vec noble_kernel.types.Ty

/-- [noble_contracts::syntax::parsing::Frame]
    Source: 'crates/noble-contracts/src/syntax/parsing.rs', lines 1:0-5:1 -/
structure syntax.parsing.Frame where
  start : Std.U32
  is_square : Bool
  children : alloc.vec.Vec Std.U32

/-- [noble_contracts::syntax::parsing::State]
    Source: 'crates/noble-contracts/src/syntax/parsing.rs', lines 7:0-12:1 -/
structure syntax.parsing.State where
  tree : syntax.Tree
  frames : alloc.vec.Vec syntax.parsing.Frame
  root : Option Std.U32
  position : Std.Usize

/-- [noble_contracts::Prepared]
    Source: 'crates/noble-contracts/src/lib.rs', lines 159:0-171:1
    Visibility: public -/
structure Prepared where
  «name» : String
  inputs : alloc.vec.Vec NamedType
  outputs : alloc.vec.Vec NamedType
  params : alloc.vec.Vec NamedType
  definitions : alloc.vec.Vec LogicDef
  expressions : alloc.vec.Vec Expr
  requires : Std.U32
  ensures : Std.U32
  candidate : noble_kernel.untrusted.Candidate
  request : noble_kernel.untrusted.Request
  checked : noble_kernel.untrusted.Checked

/-- [noble_contracts::program::DraftKind]
    Source: 'crates/noble-contracts/src/program.rs', lines 30:0-34:1 -/
@[discriminant isize]
inductive program.DraftKind where
| Literal : noble_kernel.untrusted.Lit → program.DraftKind
| Invocation : noble_kernel.contracts.Definition → program.DraftKind
| Quotation : alloc.vec.Vec noble_kernel.untrusted.NodeId → program.DraftKind

/-- [noble_contracts::inference::Variable]
    Source: 'crates/noble-contracts/src/inference/mod.rs', lines 33:0-37:1 -/
@[discriminant isize]
inductive inference.Variable where
| Value : Std.U32 → inference.Variable
| Stack : Std.U32 → inference.Variable
| Effect : inference.Variable

/-- [noble_contracts::program::Draft]
    Source: 'crates/noble-contracts/src/program.rs', lines 36:0-41:1 -/
structure program.Draft where
  kind : program.DraftKind
  «variables» : alloc.vec.Vec inference.Variable
  explicit : Option noble_kernel.words.Inst
  span : Span

/-- [noble_contracts::inference::Sort]
    Source: 'crates/noble-contracts/src/inference/mod.rs', lines 8:0-11:1 -/
@[discriminant isize]
inductive inference.Sort where
| Value : inference.Sort
| Stack : inference.Sort

/-- [noble_contracts::inference::Term]
    Source: 'crates/noble-contracts/src/inference/mod.rs', lines 16:0-30:1 -/
@[discriminant isize]
inductive inference.Term where
| HoleTerm : inference.Sort → inference.Term
| LinkTerm : Std.U32 → inference.Term
| UnitTerm : inference.Term
| BoolTerm : inference.Term
| I64Term : inference.Term
| TextTerm : inference.Term
| SyntaxTerm : inference.Term
| PairTerm : Std.U32 → Std.U32 → inference.Term
| SumTerm : Std.U32 → Std.U32 → inference.Term
| ListTerm : Std.U32 → inference.Term
| ProgramTerm : Std.U32 → Std.U32 → inference.Term
| EmptyTerm : inference.Term
| PushTerm : Std.U32 → Std.U32 → inference.Term

/-- [noble_contracts::inference::Arena]
    Source: 'crates/noble-contracts/src/inference/mod.rs', lines 39:0-41:1 -/
structure inference.Arena where
  terms : alloc.vec.Vec inference.Term

/-- [noble_contracts::inference::materialize::Material]
    Source: 'crates/noble-contracts/src/inference/materialize.rs', lines 8:0-11:1 -/
@[discriminant isize]
inductive inference.materialize.Material where
| Value : noble_kernel.types.Ty → Std.U32 → inference.materialize.Material
| Stack :
  alloc.vec.Vec noble_kernel.types.Ty →
  Std.U32 →
  inference.materialize.Material

/-- [noble_contracts::inference::materialize::Step]
    Source: 'crates/noble-contracts/src/inference/materialize.rs', lines 2:0-5:1 -/
@[discriminant isize]
inductive inference.materialize.Step where
| Visit : Std.U32 → inference.materialize.Step
| Finish : inference.Term → inference.materialize.Step

/-- [noble_contracts::inference::materialize::State]
    Source: 'crates/noble-contracts/src/inference/materialize.rs', lines 13:0-16:1 -/
structure inference.materialize.State where
  steps : alloc.vec.Vec inference.materialize.Step
  values : alloc.vec.Vec inference.materialize.Material

/-- [noble_contracts::program::Frame]
    Source: 'crates/noble-contracts/src/program.rs', lines 20:0-27:1 -/
structure program.Frame where
  «syntax» : Std.U32
  position : Std.Usize
  stack : Std.U32
  expected : Std.U32
  body : alloc.vec.Vec noble_kernel.untrusted.NodeId
  origin : Option (Std.U32 × Std.U32 × Std.U32 × Span)

/-- [noble_contracts::program::Resolution]
    Source: 'crates/noble-contracts/src/program.rs', lines 43:0-49:1 -/
structure program.Resolution where
  span : Span
  arena : inference.Arena
  frames : alloc.vec.Vec program.Frame
  drafts : alloc.vec.Vec (Option program.Draft)
  body : alloc.vec.Vec noble_kernel.untrusted.NodeId

/-- [noble_contracts::program::Context]
    Source: 'crates/noble-contracts/src/program.rs', lines 8:0-12:1 -/
structure program.Context where
  source : Slice Std.U8
  tree : syntax.Tree
  env : noble_kernel.contracts.Env

/-- [noble_contracts::program::Form]
    Source: 'crates/noble-contracts/src/program.rs', lines 15:0-18:1 -/
structure program.Form where
  children : Slice Std.U32
  span : Span

/-- [noble_contracts::program::words::Call]
    Source: 'crates/noble-contracts/src/program/words.rs', lines 1:0-6:1 -/
structure program.words.Call where
  «def» : noble_kernel.contracts.Definition
  current : Std.U32
  explicit : Option noble_kernel.words.Inst
  span : Span

/-- [noble_contracts::program::witness::Bindings]
    Source: 'crates/noble-contracts/src/program/witness.rs', lines 9:0-13:1 -/
structure program.witness.Bindings where
  values : Slice noble_kernel.words.Binding
  «variables» : Slice inference.Variable
  span : Span

/-- [noble_contracts::inference::build::Step]
    Source: 'crates/noble-contracts/src/inference/build.rs', lines 2:0-14:1 -/
@[discriminant isize]
inductive inference.build.Step where
| Ty : noble_kernel.types.Ty → inference.build.Step
| Pattern : noble_kernel.shapes.Pattern → inference.build.Step
| StackTy : Slice noble_kernel.types.Ty → inference.build.Step
| StackPattern : Slice noble_kernel.shapes.Pattern → inference.build.Step
| StackTyParts :
  Slice noble_kernel.types.Ty →
  Std.Usize →
  inference.build.Step
| StackPatternParts :
  Slice noble_kernel.shapes.Pattern →
  Std.Usize →
  Std.Usize →
  inference.build.Step
| Pair : inference.build.Step
| Sum : inference.build.Step
| List : inference.build.Step
| Program : inference.build.Step
| Push : inference.build.Step

/-- [noble_contracts::inference::build::State]
    Source: 'crates/noble-contracts/src/inference/build.rs', lines 16:0-19:1 -/
structure inference.build.State where
  steps : alloc.vec.Vec inference.build.Step
  values : alloc.vec.Vec Std.U32

/-- [noble_contracts::program::witness::Explicit]
    Source: 'crates/noble-contracts/src/program/witness.rs', lines 1:0-6:1 -/
structure program.witness.Explicit where
  inst : noble_kernel.words.Inst
  kinds : Slice noble_kernel.words.VariableKind
  «variables» : Slice inference.Variable
  span : Span

/-- [noble_contracts::wire::ProjectionError]
    Source: 'crates/noble-contracts/src/wire.rs', lines 19:0-23:1
    Visibility: public -/
@[discriminant isize]
inductive wire.ProjectionError where
| Revision : wire.ProjectionError
| PayloadlessText : wire.ProjectionError
| HostWord : wire.ProjectionError

/-- [noble_contracts::wire::SemanticNode]
    Source: 'crates/noble-contracts/src/wire.rs', lines 9:0-15:1
    Visibility: public -/
@[discriminant isize]
inductive wire.SemanticNode where
| I64 : Std.I64 → wire.SemanticNode
| Boolean : Bool → wire.SemanticNode
| UnitValue : wire.SemanticNode
| Word : Std.U32 → wire.SemanticNode
| Quotation : alloc.vec.Vec Std.U32 → wire.SemanticNode

/-- [noble_contracts::wire::SemanticSubject]
    Source: 'crates/noble-contracts/src/wire.rs', lines 26:0-29:1
    Visibility: public -/
structure wire.SemanticSubject where
  nodes : alloc.vec.Vec wire.SemanticNode
  body : alloc.vec.Vec Std.U32

end noble_contracts
