-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [noble_kernel]: external types.
-- This is the template file "TypesExternal_Template.lean" generated by Aeneas
-- (with `-split-files`), renamed to "TypesExternal.lean", in which we replaced
-- the axiom with a definition.
--
-- `core::mem::maybe_uninit::MaybeUninit` is not referenced by any of the
-- extracted type or function definitions of this crate (the extraction of the
-- reachable code never mentions it); we still give it a faithful model: a
-- value which is either uninitialized or holds a `T`.
--
-- `TryReserveError` records element-capacity overflow in the existing
-- layout-free Aeneas vector model. Allocator exhaustion and byte-layout
-- limits are outside that model; no physical allocation guarantee follows.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace noble_kernel

/-- [core::mem::maybe_uninit::MaybeUninit]:
    Source: '/rustc/library/core/src/mem/maybe_uninit.rs', lines 355:0-355:24
    Name pattern: [core::mem::maybe_uninit::MaybeUninit]
    Visibility: public -/
@[rust_type "core::mem::maybe_uninit::MaybeUninit"]
def core.mem.maybe_uninit.MaybeUninit (T : Type) : Type := Option T

/-- The dataspace decoder discards UTF-8 diagnostic position and length
    immediately, retaining only success versus failure. This value-only
    external model therefore has one observable error constructor. -/
@[rust_type "core::str::error::Utf8Error"]
inductive core.str.error.Utf8Error where
  | Invalid

/-- The observable reservation rejection represented by the value-only
    vector abstraction. Rust's allocator/layout error payload is not modeled. -/
@[rust_type "alloc::collections::TryReserveError"]
inductive alloc.collections.TryReserveError where
  | CapacityOverflow

end noble_kernel
