-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [noble_kernel]: type definitions
import Aeneas
import NobleKernel.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace noble_kernel

/-- [noble_kernel::types::EffId]
    Source: 'crates/noble-kernel/src/types.rs', lines 26:0-26:26
    Visibility: public -/
@[reducible]
def types.EffId := Std.U32

/-- [noble_kernel::types::EffSet]
    Source: 'crates/noble-kernel/src/types.rs', lines 30:0-30:42
    Visibility: public -/
@[reducible]
def types.EffSet := alloc.vec.Vec types.EffId

/-- [noble_kernel::types::ResourceKind]
    Source: 'crates/noble-kernel/src/types.rs', lines 15:0-15:33
    Visibility: public -/
@[reducible]
def types.ResourceKind := Std.U32

/-- [noble_kernel::types::Ty]
    Source: 'crates/noble-kernel/src/types.rs', lines 157:0-182:1
    Visibility: public -/
@[discriminant isize]
inductive types.Ty where
| UnitType : types.Ty
| BoolType : types.Ty
| I64Type : types.Ty
| TextType : types.Ty
| SyntaxType : types.Ty
| PairType : types.Ty → types.Ty → types.Ty
| SumType : types.Ty → types.Ty → types.Ty
| ListType : types.Ty → types.Ty
| ProgramType :
  alloc.vec.Vec types.Ty →
  alloc.vec.Vec types.Ty →
  types.EffSet →
  types.Ty
| ResourceType : types.ResourceKind → types.Ty

/-- [noble_kernel::untrusted::Interface]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 139:0-146:1
    Visibility: public -/
structure untrusted.Interface where
  stack_in : alloc.vec.Vec types.Ty
  stack_out : alloc.vec.Vec types.Ty
  effects : types.EffSet

/-- [noble_kernel::untrusted::NodeId]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 18:0-18:27
    Visibility: public -/
@[reducible]
def untrusted.NodeId := Std.U32

/-- [noble_kernel::acceptance::Frame]
    Source: 'crates/noble-kernel/src/acceptance/mod.rs', lines 21:0-30:1 -/
structure acceptance.Frame where
  depth : Std.U32
  origin : Option untrusted.NodeId
  body : alloc.vec.Vec untrusted.NodeId
  index : Std.Usize
  stack : alloc.vec.Vec types.Ty
  effects : types.EffSet
  claimed_out : alloc.vec.Vec types.Ty
  claimed_effects : types.EffSet

/-- [noble_kernel::acceptance::frames::Completion]
    Source: 'crates/noble-kernel/src/acceptance/frames.rs', lines 4:0-18:1 -/
@[discriminant isize]
inductive acceptance.frames.Completion where
| Entry : types.EffSet → acceptance.frames.Completion
| Step :
  Std.U32 →
  untrusted.NodeId →
  untrusted.Interface →
  acceptance.Frame →
  acceptance.frames.Completion

/-- [noble_kernel::untrusted::Limits]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 104:0-123:1
    Visibility: public -/
structure untrusted.Limits where
  bytes : Std.U32
  nodes : Std.U32
  depth : Std.U32
  type_size : Std.U32
  stack_height : Std.U32
  work : Std.U32
  diagnostics : Std.U32

/-- [noble_kernel::untrusted::Expected]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 93:0-100:1
    Visibility: public -/
structure untrusted.Expected where
  stack_in : alloc.vec.Vec types.Ty
  stack_out : alloc.vec.Vec types.Ty
  allowed_effects : types.EffSet

/-- [noble_kernel::untrusted::Request]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 127:0-134:1
    Visibility: public -/
structure untrusted.Request where
  input_bytes : Std.U32
  expected : untrusted.Expected
  limits : untrusted.Limits

/-- [noble_kernel::words::Variable]
    Source: 'crates/noble-kernel/src/words.rs', lines 18:0-18:29
    Visibility: public -/
@[reducible]
def words.Variable := Std.U32

/-- [noble_kernel::words::Binding]
    Source: 'crates/noble-kernel/src/words.rs', lines 48:0-59:1
    Visibility: public -/
@[discriminant isize]
inductive words.Binding where
| Stack : alloc.vec.Vec types.Ty → words.Binding
| Value : types.Ty → words.Binding
| Effect : types.EffSet → words.Binding
| Ref : words.Variable → words.Binding

/-- [noble_kernel::words::Inst]
    Source: 'crates/noble-kernel/src/words.rs', lines 64:0-67:1
    Visibility: public -/
structure words.Inst where
  bindings : alloc.vec.Vec words.Binding

/-- [noble_kernel::untrusted::Lit]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 27:0-36:1
    Visibility: public -/
@[discriminant isize]
inductive untrusted.Lit where
| I64Lit : Std.I64 → untrusted.Lit
| BoolLit : Bool → untrusted.Lit
| TextLit : untrusted.Lit
| UnitLit : untrusted.Lit

/-- [noble_kernel::contracts::Definition]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 11:0-11:31
    Visibility: public -/
@[reducible]
def contracts.Definition := Std.U32

/-- [noble_kernel::untrusted::Node]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 53:0-76:1
    Visibility: public -/
@[discriminant isize]
inductive untrusted.Node where
| Literal : untrusted.Lit → words.Inst → untrusted.Node
| Invocation : contracts.Definition → words.Inst → untrusted.Node
| Quotation : alloc.vec.Vec untrusted.NodeId → words.Inst → untrusted.Node

/-- [noble_kernel::untrusted::Candidate]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 80:0-89:1
    Visibility: public -/
structure untrusted.Candidate where
  format : Std.U32
  revision : Std.U32
  nodes : alloc.vec.Vec untrusted.Node
  body : alloc.vec.Vec untrusted.NodeId

/-- [noble_kernel::words::VariableKind]
    Source: 'crates/noble-kernel/src/words.rs', lines 22:0-29:1
    Visibility: public -/
@[discriminant isize]
inductive words.VariableKind where
| Stack : words.VariableKind
| Value : words.VariableKind
| Effect : words.VariableKind

/-- [noble_kernel::shapes::EffectSlot]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 74:0-79:1
    Visibility: public -/
@[discriminant isize]
inductive shapes.EffectSlot where
| Effect : types.EffId → shapes.EffectSlot
| Var : words.Variable → shapes.EffectSlot

/-- [noble_kernel::shapes::Pattern]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 26:0-55:1
    Visibility: public -/
@[discriminant isize]
inductive shapes.Pattern where
| UnitPattern : shapes.Pattern
| BoolPattern : shapes.Pattern
| I64Pattern : shapes.Pattern
| TextPattern : shapes.Pattern
| SyntaxPattern : shapes.Pattern
| PairPattern : shapes.Pattern → shapes.Pattern → shapes.Pattern
| SumPattern : shapes.Pattern → shapes.Pattern → shapes.Pattern
| ListPattern : shapes.Pattern → shapes.Pattern
| ProgramPattern :
  alloc.vec.Vec shapes.Pattern →
  alloc.vec.Vec shapes.Pattern →
  alloc.vec.Vec shapes.EffectSlot →
  shapes.Pattern
| ResourcePattern : types.ResourceKind → shapes.Pattern
| VarPattern : words.Variable → shapes.Pattern
| StackVarPattern : words.Variable → shapes.Pattern

/-- [noble_kernel::words::Scheme]
    Source: 'crates/noble-kernel/src/words.rs', lines 34:0-43:1
    Visibility: public -/
structure words.Scheme where
  var_kinds : alloc.vec.Vec words.VariableKind
  stack_in : alloc.vec.Vec shapes.Pattern
  stack_out : alloc.vec.Vec shapes.Pattern
  effects : alloc.vec.Vec shapes.EffectSlot

/-- [noble_kernel::untrusted::Constraint]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 206:0-228:1
    Visibility: public -/
@[discriminant isize]
inductive untrusted.Constraint where
| StackJoin : untrusted.Constraint
| StackOrder : untrusted.Constraint
| EffectInclusion : types.EffId → untrusted.Constraint
| Eligibility : types.Ty → untrusted.Constraint
| UnknownEffect : types.EffId → untrusted.Constraint
| InstantiationKind : untrusted.Constraint
| InstantiationArity : untrusted.Constraint
| MalformedReference : untrusted.NodeId → untrusted.Constraint
| UnknownDefinition : contracts.Definition → untrusted.Constraint
| CyclicWitness : untrusted.Constraint

/-- [noble_kernel::untrusted::Diagnostic]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 232:0-247:1
    Visibility: public -/
structure untrusted.Diagnostic where
  node : Option untrusted.NodeId
  «def» : Option contracts.Definition
  expected : alloc.vec.Vec types.Ty
  actual : alloc.vec.Vec types.Ty
  constraint : untrusted.Constraint
  provenance_available : Bool
  truncated : Bool

/-- [noble_kernel::acceptance::parts::Site]
    Source: 'crates/noble-kernel/src/acceptance/parts.rs', lines 14:0-17:1 -/
structure acceptance.parts.Site where
  node : Option untrusted.NodeId
  «def» : Option contracts.Definition

/-- [noble_kernel::contracts::SchemaId]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 21:0-21:29
    Visibility: public -/
@[reducible]
def contracts.SchemaId := Std.U32

/-- [noble_kernel::contracts::SchemaDecl]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 83:0-90:1
    Visibility: public -/
structure contracts.SchemaDecl where
  id : contracts.SchemaId
  scheme : words.Scheme
  recursive : Bool

/-- [noble_kernel::contracts::Behavior]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 30:0-75:1
    Visibility: public -/
@[discriminant isize]
inductive contracts.Behavior where
| DupBehavior : contracts.Behavior
| DropBehavior : contracts.Behavior
| SwapBehavior : contracts.Behavior
| DipBehavior : contracts.Behavior
| ArithBehavior : contracts.Behavior
| EqualsBehavior : contracts.Behavior
| QuoteBehavior : contracts.Behavior
| ComposeBehavior : contracts.Behavior
| RunBehavior : contracts.Behavior
| ReflectBehavior : contracts.Behavior
| UnitBehavior : contracts.Behavior
| PairBehavior : contracts.Behavior
| UnpairBehavior : contracts.Behavior
| InlBehavior : contracts.Behavior
| InrBehavior : contracts.Behavior
| CaseBehavior : contracts.Behavior
| IfBehavior : contracts.Behavior
| NilBehavior : contracts.Behavior
| ConsBehavior : contracts.Behavior
| ListCaseBehavior : contracts.Behavior
| TestEmitBehavior : contracts.Behavior
| NamedBehavior : contracts.Behavior

/-- [noble_kernel::contracts::Env]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 94:0-106:1
    Visibility: public -/
structure contracts.Env where
  defs : alloc.vec.Vec words.Scheme
  kinds : alloc.vec.Vec contracts.Behavior
  deps : alloc.vec.Vec (alloc.vec.Vec contracts.Definition)
  schemas : alloc.vec.Vec contracts.SchemaDecl
  effects : alloc.vec.Vec types.EffId

/-- [noble_kernel::acceptance::parts::Ctx]
    Source: 'crates/noble-kernel/src/acceptance/parts.rs', lines 7:0-10:1 -/
structure acceptance.parts.Ctx where
  request : untrusted.Request
  env : contracts.Env

/-- [noble_kernel::untrusted::UnsupportedKind]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 187:0-200:1
    Visibility: public -/
@[discriminant isize]
inductive untrusted.UnsupportedKind where
| FormatRevision : untrusted.UnsupportedKind
| NodeForm : untrusted.UnsupportedKind
| SchemeForm : untrusted.UnsupportedKind
| RecursiveDependency : contracts.Definition → untrusted.UnsupportedKind
| RecursiveSchema : contracts.SchemaId → untrusted.UnsupportedKind

/-- [noble_kernel::untrusted::LimitKind]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 168:0-183:1
    Visibility: public -/
@[discriminant isize]
inductive untrusted.LimitKind where
| Bytes : untrusted.LimitKind
| Nodes : untrusted.LimitKind
| Depth : untrusted.LimitKind
| TypeSize : untrusted.LimitKind
| StackHeight : untrusted.LimitKind
| Work : untrusted.LimitKind
| Diagnostics : untrusted.LimitKind

/-- [noble_kernel::acceptance::Fail]
    Source: 'crates/noble-kernel/src/acceptance/mod.rs', lines 13:0-18:1 -/
@[discriminant isize]
inductive acceptance.Fail where
| Invalid : untrusted.Diagnostic → acceptance.Fail
| Unsupported : untrusted.UnsupportedKind → acceptance.Fail
| Exhausted : untrusted.LimitKind → acceptance.Fail
| Internal : acceptance.Fail

/-- [noble_kernel::words::InstError]
    Source: 'crates/noble-kernel/src/words.rs', lines 71:0-89:1
    Visibility: public -/
@[discriminant isize]
inductive words.InstError where
| KindMismatch : words.InstError
| UnknownVariable : words.InstError
| ArityMismatch : words.InstError
| OversizedStack : words.InstError
| OversizedType : words.InstError
| OversizedEffects : words.InstError
| CyclicWitness : words.InstError
| WalkExhausted : words.InstError

/-- [noble_kernel::types::size::Step]
    Source: 'crates/noble-kernel/src/types/size.rs', lines 18:0-25:1 -/
@[discriminant isize]
inductive types.size.Step where
| Continue : types.size.Step
| Done : types.size.Step
| Failed : types.size.Step

/-- [noble_kernel::types::size::Walk]
    Source: 'crates/noble-kernel/src/types/size.rs', lines 10:0-15:1 -/
structure types.size.Walk where
  todo : alloc.vec.Vec (types.Ty × Bool)
  sizes : alloc.vec.Vec Std.U32

/-- [noble_kernel::words::{noble_kernel::words::Scheme}::subst_effects::{closure}]
    Source: 'crates/noble-kernel/src/words.rs', lines 256:46-256:75 -/
@[reducible]
def words.Scheme.subst_effects.closure := Unit

/-- [noble_kernel::words::{noble_kernel::words::Scheme}::subst_stack::{closure}]
    Source: 'crates/noble-kernel/src/words.rs', lines 203:44-203:66 -/
@[reducible]
def words.Scheme.subst_stack.closure := Unit

/-- [noble_kernel::words::subst::Task]
    Source: 'crates/noble-kernel/src/words/subst.rs', lines 18:0-23:1 -/
@[discriminant isize]
inductive words.subst.Task where
| Part : shapes.Pattern → words.subst.Task
| Finish : shapes.Pattern → words.subst.Task
| Expand : shapes.Pattern → words.subst.Task
| Emit : alloc.vec.Vec types.Ty → words.subst.Task

/-- [noble_kernel::words::subst::Walk]
    Source: 'crates/noble-kernel/src/words/subst.rs', lines 26:0-31:1 -/
structure words.subst.Walk where
  work : alloc.vec.Vec words.subst.Task
  segments : alloc.vec.Vec (alloc.vec.Vec types.Ty)

/-- [noble_kernel::words::subst::StepResult]
    Source: 'crates/noble-kernel/src/words/subst.rs', lines 34:0-41:1 -/
@[discriminant isize]
inductive words.subst.StepResult where
| Continue : words.subst.StepResult
| Done : words.subst.StepResult
| Failed : words.InstError → words.subst.StepResult

/-- [noble_kernel::words::resolve::Walk]
    Source: 'crates/noble-kernel/src/words/resolve.rs', lines 12:0-17:1 -/
structure words.resolve.Walk where
  out : alloc.vec.Vec words.Binding
  spent : Std.U32

/-- [noble_kernel::untrusted::Derivation]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 150:0-155:1
    Visibility: public -/
structure untrusted.Derivation where
  node : untrusted.NodeId
  interface : untrusted.Interface

/-- [noble_kernel::acceptance::State]
    Source: 'crates/noble-kernel/src/acceptance/mod.rs', lines 32:0-35:1 -/
structure acceptance.State where
  work : Std.U32
  derivations : alloc.vec.Vec untrusted.Derivation

/-- [noble_kernel::acceptance::Machine]
    Source: 'crates/noble-kernel/src/acceptance/mod.rs', lines 39:0-43:1 -/
structure acceptance.Machine where
  state : acceptance.State
  frames : alloc.vec.Vec acceptance.Frame
  outcome : Option (core.result.Result untrusted.Interface acceptance.Fail)

/-- [noble_kernel::untrusted::Checked]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 159:0-164:1
    Visibility: public -/
structure untrusted.Checked where
  interface : untrusted.Interface
  derivations : alloc.vec.Vec untrusted.Derivation

/-- [noble_kernel::untrusted::Outcome]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 251:0-262:1
    Visibility: public -/
@[discriminant isize]
inductive untrusted.Outcome where
| Accepted : untrusted.Checked → untrusted.Outcome
| Invalid : untrusted.Diagnostic → untrusted.Outcome
| Unsupported : untrusted.UnsupportedKind → untrusted.Outcome
| Exhausted : untrusted.LimitKind → untrusted.Outcome
| InternalFailure : untrusted.Outcome

/-- [noble_kernel::shapes::Defect]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 83:0-88:1
    Visibility: public -/
@[discriminant isize]
inductive shapes.Defect where
| UnknownVariable : shapes.Defect
| KindMismatch : shapes.Defect

/-- [noble_kernel::shapes::Step]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 94:0-98:1 -/
@[discriminant isize]
inductive shapes.Step where
| Pattern : shapes.Pattern → shapes.Step
| Parts : alloc.vec.Vec shapes.Pattern → shapes.Step
| Slots : alloc.vec.Vec shapes.EffectSlot → shapes.Step

/-- [noble_kernel::acceptance::validate::colored_slot::{closure}]
    Source: 'crates/noble-kernel/src/acceptance/validate.rs', lines 41:43-41:66 -/
@[reducible]
def acceptance.validate.colored_slot.closure := Std.Usize

/-- [noble_kernel::acceptance::validate::DepWalk]
    Source: 'crates/noble-kernel/src/acceptance/validate.rs', lines 11:0-18:1 -/
structure acceptance.validate.DepWalk where
  colors : alloc.vec.Vec Std.U8
  stack : alloc.vec.Vec contracts.Definition
  spent : Std.U32

/-- [noble_kernel::BudgetOutcome]
    Source: 'crates/noble-kernel/src/lib.rs', lines 38:0-41:1
    Visibility: public -/
@[discriminant isize]
inductive BudgetOutcome where
| Remaining : Std.U32 → BudgetOutcome
| Exhausted : BudgetOutcome

end noble_kernel
