-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [noble_wasm]: type definitions
import Aeneas
import NobleWasmImpl.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace noble_wasm

/-- [noble_kernel::types::ResourceKind]
    Source: 'crates/noble-kernel/src/types.rs', lines 15:0-15:23
    Name pattern: [noble_kernel::types::ResourceKind]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::types::ResourceKind"]
def noble_kernel.types.ResourceKind := Std.U32

/-- [noble_contracts::component::Type]
    Source: 'crates/noble-contracts/src/component/mod.rs', lines 47:0-47:13
    Name pattern: [noble_contracts::component::Type]
    Visibility: public -/
@[discriminant isize, rust_type "noble_contracts::component::Type"]
inductive noble_contracts.component.Type where
| Boolean : noble_contracts.component.Type
| S64 : noble_contracts.component.Type
| String : noble_contracts.component.Type
| Bytes : noble_contracts.component.Type
| ResultS64String : noble_contracts.component.Type
| ResultBytesString : noble_contracts.component.Type
| StreamU8 : noble_contracts.component.Type
| FutureS64 : noble_contracts.component.Type
| FutureResultS64String : noble_contracts.component.Type
| Own : noble_kernel.types.ResourceKind → noble_contracts.component.Type
| Borrow : noble_kernel.types.ResourceKind → noble_contracts.component.Type

/-- [noble_kernel::types::Ty]
    Source: 'crates/noble-kernel/src/types.rs', lines 157:0-157:11
    Name pattern: [noble_kernel::types::Ty]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::types::Ty"]
inductive noble_kernel.types.Ty where
| UnitType : noble_kernel.types.Ty
| BoolType : noble_kernel.types.Ty
| I64Type : noble_kernel.types.Ty
| TextType : noble_kernel.types.Ty
| SyntaxType : noble_kernel.types.Ty
| ContractType : noble_kernel.types.Ty
| EvidenceType : noble_kernel.types.Ty
| CertifiedType : noble_kernel.types.Ty
| PairType :
  noble_kernel.types.Ty →
  noble_kernel.types.Ty →
  noble_kernel.types.Ty
| SumType :
  noble_kernel.types.Ty →
  noble_kernel.types.Ty →
  noble_kernel.types.Ty
| ListType : noble_kernel.types.Ty → noble_kernel.types.Ty
| ProgramType :
  alloc.vec.Vec noble_kernel.types.Ty →
  alloc.vec.Vec noble_kernel.types.Ty →
  noble_kernel.types.EffSet →
  noble_kernel.types.Ty
| ResourceType : noble_kernel.types.ResourceKind → noble_kernel.types.Ty

/-- [noble_kernel::types::EffId]
    Source: 'crates/noble-kernel/src/types.rs', lines 26:0-26:16
    Name pattern: [noble_kernel::types::EffId]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::types::EffId"]
def noble_kernel.types.EffId := Std.U32

/-- [noble_kernel::contracts::Definition]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 11:0-11:21
    Name pattern: [noble_kernel::contracts::Definition]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::contracts::Definition"]
def noble_kernel.contracts.Definition := Std.U32

/-- [noble_contracts::component::Operation]
    Source: 'crates/noble-contracts/src/component/mod.rs', lines 118:0-118:20
    Name pattern: [noble_contracts::component::Operation]
    Visibility: public -/
@[rust_type "noble_contracts::component::Operation"]
structure noble_contracts.component.Operation where
  identity : String
  word : String
  core_module : String
  core_name : String
  export_name : String
  parameters : alloc.vec.Vec noble_contracts.component.Type
  results : alloc.vec.Vec noble_contracts.component.Type
  asynchronous : Bool
  effect : Option noble_kernel.types.EffId
  definition : Option noble_kernel.contracts.Definition

/-- [noble_kernel::words::VariableKind]
    Source: 'crates/noble-kernel/src/words.rs', lines 22:0-22:21
    Name pattern: [noble_kernel::words::VariableKind]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::words::VariableKind"]
inductive noble_kernel.words.VariableKind where
| Stack : noble_kernel.words.VariableKind
| Value : noble_kernel.words.VariableKind
| Effect : noble_kernel.words.VariableKind

/-- [noble_kernel::words::Variable]
    Source: 'crates/noble-kernel/src/words.rs', lines 18:0-18:19
    Name pattern: [noble_kernel::words::Variable]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::words::Variable"]
def noble_kernel.words.Variable := Std.U32

/-- [noble_kernel::shapes::EffectSlot]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 80:0-80:19
    Name pattern: [noble_kernel::shapes::EffectSlot]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::shapes::EffectSlot"]
inductive noble_kernel.shapes.EffectSlot where
| Effect : noble_kernel.types.EffId → noble_kernel.shapes.EffectSlot
| Var : noble_kernel.words.Variable → noble_kernel.shapes.EffectSlot

/-- [noble_kernel::shapes::Pattern]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 26:0-26:16
    Name pattern: [noble_kernel::shapes::Pattern]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::shapes::Pattern"]
inductive noble_kernel.shapes.Pattern where
| UnitPattern : noble_kernel.shapes.Pattern
| BoolPattern : noble_kernel.shapes.Pattern
| I64Pattern : noble_kernel.shapes.Pattern
| TextPattern : noble_kernel.shapes.Pattern
| SyntaxPattern : noble_kernel.shapes.Pattern
| ContractPattern : noble_kernel.shapes.Pattern
| EvidencePattern : noble_kernel.shapes.Pattern
| CertifiedPattern : noble_kernel.shapes.Pattern
| PairPattern :
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern
| SumPattern :
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern
| ListPattern : noble_kernel.shapes.Pattern → noble_kernel.shapes.Pattern
| ProgramPattern :
  alloc.vec.Vec noble_kernel.shapes.Pattern →
  alloc.vec.Vec noble_kernel.shapes.Pattern →
  alloc.vec.Vec noble_kernel.shapes.EffectSlot →
  noble_kernel.shapes.Pattern
| ResourcePattern :
  noble_kernel.types.ResourceKind →
  noble_kernel.shapes.Pattern
| VarPattern : noble_kernel.words.Variable → noble_kernel.shapes.Pattern
| StackVarPattern : noble_kernel.words.Variable → noble_kernel.shapes.Pattern

/-- [noble_kernel::words::Scheme]
    Source: 'crates/noble-kernel/src/words.rs', lines 34:0-34:17
    Name pattern: [noble_kernel::words::Scheme]
    Visibility: public -/
@[rust_type "noble_kernel::words::Scheme"]
structure noble_kernel.words.Scheme where
  var_kinds : alloc.vec.Vec noble_kernel.words.VariableKind
  stack_in : alloc.vec.Vec noble_kernel.shapes.Pattern
  stack_out : alloc.vec.Vec noble_kernel.shapes.Pattern
  effects : alloc.vec.Vec noble_kernel.shapes.EffectSlot

/-- [noble_kernel::contracts::SchemaId]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 21:0-21:19
    Name pattern: [noble_kernel::contracts::SchemaId]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::contracts::SchemaId"]
def noble_kernel.contracts.SchemaId := Std.U32

/-- [noble_kernel::contracts::SchemaDecl]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 83:0-83:21
    Name pattern: [noble_kernel::contracts::SchemaDecl]
    Visibility: public -/
@[rust_type "noble_kernel::contracts::SchemaDecl"]
structure noble_kernel.contracts.SchemaDecl where
  id : noble_kernel.contracts.SchemaId
  scheme : noble_kernel.words.Scheme
  recursive : Bool

/-- [noble_kernel::contracts::Behavior]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 30:0-30:17
    Name pattern: [noble_kernel::contracts::Behavior]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::contracts::Behavior"]
inductive noble_kernel.contracts.Behavior where
| DupBehavior : noble_kernel.contracts.Behavior
| DropBehavior : noble_kernel.contracts.Behavior
| SwapBehavior : noble_kernel.contracts.Behavior
| DipBehavior : noble_kernel.contracts.Behavior
| ArithBehavior : noble_kernel.contracts.Behavior
| EqualsBehavior : noble_kernel.contracts.Behavior
| QuoteBehavior : noble_kernel.contracts.Behavior
| ComposeBehavior : noble_kernel.contracts.Behavior
| RunBehavior : noble_kernel.contracts.Behavior
| ReflectBehavior : noble_kernel.contracts.Behavior
| UnitBehavior : noble_kernel.contracts.Behavior
| PairBehavior : noble_kernel.contracts.Behavior
| UnpairBehavior : noble_kernel.contracts.Behavior
| InlBehavior : noble_kernel.contracts.Behavior
| InrBehavior : noble_kernel.contracts.Behavior
| CaseBehavior : noble_kernel.contracts.Behavior
| IfBehavior : noble_kernel.contracts.Behavior
| NilBehavior : noble_kernel.contracts.Behavior
| ConsBehavior : noble_kernel.contracts.Behavior
| ListCaseBehavior : noble_kernel.contracts.Behavior
| TestEmitBehavior : noble_kernel.contracts.Behavior
| NamedBehavior : noble_kernel.contracts.Behavior

/-- [noble_kernel::contracts::Env]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 94:0-94:14
    Name pattern: [noble_kernel::contracts::Env]
    Visibility: public -/
@[rust_type "noble_kernel::contracts::Env"]
structure noble_kernel.contracts.Env where
  defs : alloc.vec.Vec noble_kernel.words.Scheme
  kinds : alloc.vec.Vec noble_kernel.contracts.Behavior
  deps : alloc.vec.Vec (alloc.vec.Vec noble_kernel.contracts.Definition)
  schemas : alloc.vec.Vec noble_kernel.contracts.SchemaDecl
  effects : alloc.vec.Vec noble_kernel.types.EffId

/-- [noble_contracts::component::Stage]
    Source: 'crates/noble-contracts/src/component/mod.rs', lines 238:0-238:14
    Name pattern: [noble_contracts::component::Stage]
    Visibility: public -/
@[discriminant isize, rust_type "noble_contracts::component::Stage"]
inductive noble_contracts.component.Stage where
| Wit : noble_contracts.component.Stage
| Binding : noble_contracts.component.Stage
| Export : noble_contracts.component.Stage
| Acceptance : noble_contracts.component.Stage

/-- [noble_contracts::component::Error]
    Source: 'crates/noble-contracts/src/component/mod.rs', lines 246:0-246:16
    Name pattern: [noble_contracts::component::Error]
    Visibility: public -/
@[rust_type "noble_contracts::component::Error"]
structure noble_contracts.component.Error where
  stage : noble_contracts.component.Stage
  diagnostic : noble_contracts.Diagnostic

/-- [noble_kernel::untrusted::Limits]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 104:0-104:17
    Name pattern: [noble_kernel::untrusted::Limits]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Limits"]
structure noble_kernel.untrusted.Limits where
  bytes : Std.U32
  nodes : Std.U32
  depth : Std.U32
  type_size : Std.U32
  stack_height : Std.U32
  work : Std.U32
  diagnostics : Std.U32

/-- [noble_kernel::untrusted::Expected]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 93:0-93:19
    Name pattern: [noble_kernel::untrusted::Expected]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Expected"]
structure noble_kernel.untrusted.Expected where
  stack_in : alloc.vec.Vec noble_kernel.types.Ty
  stack_out : alloc.vec.Vec noble_kernel.types.Ty
  allowed_effects : noble_kernel.types.EffSet

/-- [noble_kernel::untrusted::Request]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 127:0-127:18
    Name pattern: [noble_kernel::untrusted::Request]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Request"]
structure noble_kernel.untrusted.Request where
  input_bytes : Std.U32
  expected : noble_kernel.untrusted.Expected
  limits : noble_kernel.untrusted.Limits

/-- [noble_kernel::words::Binding]
    Source: 'crates/noble-kernel/src/words.rs', lines 48:0-48:16
    Name pattern: [noble_kernel::words::Binding]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::words::Binding"]
inductive noble_kernel.words.Binding where
| Stack : alloc.vec.Vec noble_kernel.types.Ty → noble_kernel.words.Binding
| Value : noble_kernel.types.Ty → noble_kernel.words.Binding
| Effect : noble_kernel.types.EffSet → noble_kernel.words.Binding
| Ref : noble_kernel.words.Variable → noble_kernel.words.Binding

/-- [noble_kernel::words::Inst]
    Source: 'crates/noble-kernel/src/words.rs', lines 64:0-64:15
    Name pattern: [noble_kernel::words::Inst]
    Visibility: public -/
@[rust_type "noble_kernel::words::Inst"]
structure noble_kernel.words.Inst where
  bindings : alloc.vec.Vec noble_kernel.words.Binding

/-- [noble_kernel::untrusted::Lit]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 27:0-27:12
    Name pattern: [noble_kernel::untrusted::Lit]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Lit"]
inductive noble_kernel.untrusted.Lit where
| I64Lit : Std.I64 → noble_kernel.untrusted.Lit
| BoolLit : Bool → noble_kernel.untrusted.Lit
| TextLit : noble_kernel.untrusted.Lit
| UnitLit : noble_kernel.untrusted.Lit

/-- [noble_kernel::untrusted::NodeId]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 18:0-18:17
    Name pattern: [noble_kernel::untrusted::NodeId]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::untrusted::NodeId"]
def noble_kernel.untrusted.NodeId := Std.U32

/-- [noble_kernel::untrusted::Node]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 53:0-53:13
    Name pattern: [noble_kernel::untrusted::Node]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Node"]
inductive noble_kernel.untrusted.Node where
| Literal :
  noble_kernel.untrusted.Lit →
  noble_kernel.words.Inst →
  noble_kernel.untrusted.Node
| Invocation :
  noble_kernel.contracts.Definition →
  noble_kernel.words.Inst →
  noble_kernel.untrusted.Node
| Quotation :
  alloc.vec.Vec noble_kernel.untrusted.NodeId →
  noble_kernel.words.Inst →
  noble_kernel.untrusted.Node

/-- [noble_kernel::untrusted::Candidate]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 80:0-80:20
    Name pattern: [noble_kernel::untrusted::Candidate]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Candidate"]
structure noble_kernel.untrusted.Candidate where
  format : Std.U32
  revision : Std.U32
  nodes : alloc.vec.Vec noble_kernel.untrusted.Node
  body : alloc.vec.Vec noble_kernel.untrusted.NodeId

/-- [noble_kernel::execution::TextLiteral]
    Source: 'crates/noble-kernel/src/execution/mod.rs', lines 9:0-9:22
    Name pattern: [noble_kernel::execution::TextLiteral]
    Visibility: public -/
@[rust_type "noble_kernel::execution::TextLiteral"]
structure noble_kernel.execution.TextLiteral where
  node : noble_kernel.untrusted.NodeId
  bytes : alloc.vec.Vec Std.U8

/-- [noble_kernel::execution::Body]
    Source: 'crates/noble-kernel/src/execution/mod.rs', lines 16:0-16:15
    Name pattern: [noble_kernel::execution::Body]
    Visibility: public -/
@[rust_type "noble_kernel::execution::Body"]
structure noble_kernel.execution.Body where
  candidate : noble_kernel.untrusted.Candidate
  texts : alloc.vec.Vec noble_kernel.execution.TextLiteral

/-- [noble_kernel::execution::Definition]
    Source: 'crates/noble-kernel/src/execution/mod.rs', lines 23:0-23:21
    Name pattern: [noble_kernel::execution::Definition]
    Visibility: public -/
@[rust_type "noble_kernel::execution::Definition"]
structure noble_kernel.execution.Definition where
  definition : noble_kernel.contracts.Definition
  identity : Std.U64
  body : noble_kernel.execution.Body
  expected : noble_kernel.untrusted.Expected

/-- [noble_kernel::execution::Submission]
    Source: 'crates/noble-kernel/src/execution/mod.rs', lines 37:0-37:21
    Name pattern: [noble_kernel::execution::Submission]
    Visibility: public -/
@[rust_type "noble_kernel::execution::Submission"]
structure noble_kernel.execution.Submission where
  environment : noble_kernel.contracts.Env
  definitions : alloc.vec.Vec noble_kernel.execution.Definition
  body : noble_kernel.execution.Body
  request : noble_kernel.untrusted.Request

/-- [noble_kernel::untrusted::Constraint]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 206:0-206:19
    Name pattern: [noble_kernel::untrusted::Constraint]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Constraint"]
inductive noble_kernel.untrusted.Constraint where
| StackJoin : noble_kernel.untrusted.Constraint
| StackOrder : noble_kernel.untrusted.Constraint
| EffectInclusion :
  noble_kernel.types.EffId →
  noble_kernel.untrusted.Constraint
| Eligibility : noble_kernel.types.Ty → noble_kernel.untrusted.Constraint
| UnknownEffect :
  noble_kernel.types.EffId →
  noble_kernel.untrusted.Constraint
| InstantiationKind : noble_kernel.untrusted.Constraint
| InstantiationArity : noble_kernel.untrusted.Constraint
| MalformedReference :
  noble_kernel.untrusted.NodeId →
  noble_kernel.untrusted.Constraint
| UnknownDefinition :
  noble_kernel.contracts.Definition →
  noble_kernel.untrusted.Constraint
| CyclicWitness : noble_kernel.untrusted.Constraint

/-- [noble_kernel::untrusted::Diagnostic]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 232:0-232:21
    Name pattern: [noble_kernel::untrusted::Diagnostic]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Diagnostic"]
structure noble_kernel.untrusted.Diagnostic where
  node : Option noble_kernel.untrusted.NodeId
  «def» : Option noble_kernel.contracts.Definition
  expected : alloc.vec.Vec noble_kernel.types.Ty
  actual : alloc.vec.Vec noble_kernel.types.Ty
  constraint : noble_kernel.untrusted.Constraint
  provenance_available : Bool
  truncated : Bool

/-- [noble_kernel::untrusted::UnsupportedKind]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 187:0-187:24
    Name pattern: [noble_kernel::untrusted::UnsupportedKind]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::UnsupportedKind"]
inductive noble_kernel.untrusted.UnsupportedKind where
| FormatRevision : noble_kernel.untrusted.UnsupportedKind
| NodeForm : noble_kernel.untrusted.UnsupportedKind
| SchemeForm : noble_kernel.untrusted.UnsupportedKind
| RecursiveDependency :
  noble_kernel.contracts.Definition →
  noble_kernel.untrusted.UnsupportedKind
| RecursiveSchema :
  noble_kernel.contracts.SchemaId →
  noble_kernel.untrusted.UnsupportedKind

/-- [noble_kernel::untrusted::LimitKind]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 168:0-168:18
    Name pattern: [noble_kernel::untrusted::LimitKind]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::LimitKind"]
inductive noble_kernel.untrusted.LimitKind where
| Bytes : noble_kernel.untrusted.LimitKind
| Nodes : noble_kernel.untrusted.LimitKind
| Depth : noble_kernel.untrusted.LimitKind
| TypeSize : noble_kernel.untrusted.LimitKind
| StackHeight : noble_kernel.untrusted.LimitKind
| Work : noble_kernel.untrusted.LimitKind
| Diagnostics : noble_kernel.untrusted.LimitKind

/-- [noble_kernel::untrusted::Interface]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 139:0-139:20
    Name pattern: [noble_kernel::untrusted::Interface]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Interface"]
structure noble_kernel.untrusted.Interface where
  stack_in : alloc.vec.Vec noble_kernel.types.Ty
  stack_out : alloc.vec.Vec noble_kernel.types.Ty
  effects : noble_kernel.types.EffSet

/-- [noble_kernel::untrusted::Derivation]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 150:0-150:21
    Name pattern: [noble_kernel::untrusted::Derivation]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Derivation"]
structure noble_kernel.untrusted.Derivation where
  node : noble_kernel.untrusted.NodeId
  interface : noble_kernel.untrusted.Interface

/-- [noble_kernel::untrusted::Checked]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 159:0-159:18
    Name pattern: [noble_kernel::untrusted::Checked]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Checked"]
structure noble_kernel.untrusted.Checked where
  interface : noble_kernel.untrusted.Interface
  derivations : alloc.vec.Vec noble_kernel.untrusted.Derivation

/-- [noble_kernel::untrusted::Outcome]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 251:0-251:16
    Name pattern: [noble_kernel::untrusted::Outcome]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Outcome"]
inductive noble_kernel.untrusted.Outcome where
| Accepted : noble_kernel.untrusted.Checked → noble_kernel.untrusted.Outcome
| Invalid :
  noble_kernel.untrusted.Diagnostic →
  noble_kernel.untrusted.Outcome
| Unsupported :
  noble_kernel.untrusted.UnsupportedKind →
  noble_kernel.untrusted.Outcome
| Exhausted :
  noble_kernel.untrusted.LimitKind →
  noble_kernel.untrusted.Outcome
| InternalFailure : noble_kernel.untrusted.Outcome

/-- [noble_kernel::shapes::Defect]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 89:0-89:15
    Name pattern: [noble_kernel::shapes::Defect]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::shapes::Defect"]
inductive noble_kernel.shapes.Defect where
| UnknownVariable : noble_kernel.shapes.Defect
| KindMismatch : noble_kernel.shapes.Defect

/-- [noble_kernel::words::InstError]
    Source: 'crates/noble-kernel/src/words.rs', lines 71:0-71:18
    Name pattern: [noble_kernel::words::InstError]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::words::InstError"]
inductive noble_kernel.words.InstError where
| KindMismatch : noble_kernel.words.InstError
| UnknownVariable : noble_kernel.words.InstError
| ArityMismatch : noble_kernel.words.InstError
| OversizedStack : noble_kernel.words.InstError
| OversizedType : noble_kernel.words.InstError
| OversizedEffects : noble_kernel.words.InstError
| CyclicWitness : noble_kernel.words.InstError
| WalkExhausted : noble_kernel.words.InstError

/-- [noble_wasm::Diagnostic]
    Source: 'crates/noble-wasm/src/lib.rs', lines 45:0-50:1
    Visibility: public -/
@[discriminant isize]
inductive Diagnostic where
| Invalid : Diagnostic
| Exhausted : Diagnostic
| Unsupported : Diagnostic
| Defective : Diagnostic

/-- [noble_wasm::component::abi::Lane]
    Source: 'crates/noble-wasm/src/component/abi.rs', lines 9:0-12:1 -/
@[discriminant isize]
inductive component.abi.Lane where
| I32 : component.abi.Lane
| I64 : component.abi.Lane

/-- [noble_wasm::output::Buffer]
    Source: 'crates/noble-wasm/src/output.rs', lines 3:0-5:1 -/
structure output.Buffer where
  bytes : alloc.vec.Vec Std.U8

/-- [noble_wasm::component::abi::indirect_parameters::{closure}]
    Source: 'crates/noble-wasm/src/component/abi.rs', lines 124:26-124:75 -/
@[reducible]
def component.abi.indirect_parameters.closure := Unit

/-- [noble_wasm::component::admission::Context]
    Source: 'crates/noble-wasm/src/component/admission/mod.rs', lines 4:0-8:1 -/
structure component.admission.Context where
  world : noble_contracts.component.World
  world_context : Slice Std.U8
  environment : noble_kernel.contracts.Env

/-- [noble_wasm::component::lower::Plan]
    Source: 'crates/noble-wasm/src/component/lower.rs', lines 15:0-23:1 -/
structure component.lower.Plan where
  «name» : String
  ordinal : Std.U32
  asynchronous : Bool
  parameters : alloc.vec.Vec noble_contracts.component.Type
  result : Option noble_contracts.component.Type
  locals : alloc.vec.Vec component.abi.Lane
  code : alloc.vec.Vec Std.U8

/-- [noble_wasm::component::emit::task::write::{closure}]
    Source: 'crates/noble-wasm/src/component/emit/task.rs', lines 11:36-11:56 -/
@[reducible]
def component.emit.task.write.closure := Unit

/-- [noble_wasm::component::lower::Data]
    Source: 'crates/noble-wasm/src/component/lower.rs', lines 11:0-14:1 -/
structure component.lower.Data where
  segments : alloc.vec.Vec (Std.U32 × (alloc.vec.Vec Std.U8))
  «end» : Std.U32

/-- [noble_wasm::component::lower::Storage]
    Source: 'crates/noble-wasm/src/component/lower.rs', lines 28:0-31:1 -/
@[discriminant isize]
inductive component.lower.Storage where
| Flat : Array (Option Std.U32) 3#usize → component.lower.Storage
| Pair : Std.Usize → component.lower.Storage

/-- [noble_wasm::component::lower::Value]
    Source: 'crates/noble-wasm/src/component/lower.rs', lines 33:0-36:1 -/
structure component.lower.Value where
  ty : noble_kernel.types.Ty
  storage : component.lower.Storage

/-- [noble_wasm::component::lower::State]
    Source: 'crates/noble-wasm/src/component/lower.rs', lines 45:0-53:1 -/
structure component.lower.State where
  locals : alloc.vec.Vec component.abi.Lane
  parameters : Std.Usize
  stack : alloc.vec.Vec component.lower.Value
  pairs : alloc.vec.Vec (component.lower.Value × component.lower.Value)
  code : output.Buffer

/-- [noble_wasm::component::lower::calls::IndirectLocals]
    Source: 'crates/noble-wasm/src/component/lower/calls.rs', lines 73:0-76:1 -/
structure component.lower.calls.IndirectLocals where
  area : Std.U32
  field : Std.U32

/-- [noble_wasm::component::lower::operations::invoke::{closure}]
    Source: 'crates/noble-wasm/src/component/lower/operations.rs', lines 150:26-150:78 -/
@[reducible]
def component.lower.operations.invoke.closure :=
  noble_kernel.contracts.Definition

/-- [noble_wasm::component::lower::operations::text::{closure}]
    Source: 'crates/noble-wasm/src/component/lower/operations.rs', lines 80:46-80:68 -/
@[reducible]
def component.lower.operations.text.closure := noble_kernel.untrusted.NodeId

/-- [noble_wasm::component::Artifact]
    Source: 'crates/noble-wasm/src/component/mod.rs', lines 28:0-31:1
    Visibility: public -/
structure component.Artifact where
  wat : alloc.vec.Vec Std.U8
  build_context : alloc.vec.Vec Std.U8

/-- [noble_wasm::signatures::Pool]
    Source: 'crates/noble-wasm/src/signatures.rs', lines 8:0-12:1 -/
structure signatures.Pool where
  keys : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  bytes : Std.Usize
  extended : Bool

/-- [noble_wasm::signatures::Interface]
    Source: 'crates/noble-wasm/src/signatures.rs', lines 15:0-18:1 -/
structure signatures.Interface where
  input : Std.U32
  output : Std.U32

/-- [noble_wasm::lowering::Program]
    Source: 'crates/noble-wasm/src/lowering.rs', lines 14:0-18:1 -/
structure lowering.Program where
  owner : Option Std.U32
  entry : Std.U32
  interface : signatures.Interface

/-- [noble_wasm::lowering::Operation]
    Source: 'crates/noble-wasm/src/lowering.rs', lines 4:0-11:1 -/
@[discriminant isize]
inductive lowering.Operation where
| I64 : Std.I64 → lowering.Operation
| Bool : Bool → lowering.Operation
| Unit : lowering.Operation
| Program : signatures.Interface → lowering.Operation
| Word : Std.U32 → lowering.Operation
| Quote : signatures.Interface → lowering.Operation

/-- [noble_wasm::lowering::Plan]
    Source: 'crates/noble-wasm/src/lowering.rs', lines 20:0-27:1 -/
structure lowering.Plan where
  nodes : alloc.vec.Vec (Option lowering.Operation)
  programs : alloc.vec.Vec lowering.Program
  signatures : signatures.Pool
  host_signatures : Array Std.U32 3#usize
  functions : Std.U32
  registry_slots : Std.U32

/-- [noble_wasm::Representation]
    Source: 'crates/noble-wasm/src/lib.rs', lines 38:0-41:1
    Visibility: public -/
@[discriminant isize]
inductive Representation where
| WasmGc : Representation
| ManagedLinearMemory : Representation

/-- [noble_wasm::signatures::walk::Step]
    Source: 'crates/noble-wasm/src/signatures/walk.rs', lines 6:0-11:1 -/
@[discriminant isize]
inductive signatures.walk.Step where
| «Type» : noble_kernel.types.Ty → signatures.walk.Step
| Stack : alloc.vec.Vec noble_kernel.types.Ty → signatures.walk.Step
| Effects : noble_kernel.types.EffSet → signatures.walk.Step
| Byte : Std.U8 → signatures.walk.Step

/-- [noble_wasm::signatures::walk::State]
    Source: 'crates/noble-wasm/src/signatures/walk.rs', lines 13:0-18:1 -/
structure signatures.walk.State where
  work : alloc.vec.Vec signatures.walk.Step
  out : output.Buffer
  fuel : Std.Usize
  extended : Bool

/-- [noble_wasm::source::Work]
    Source: 'crates/noble-wasm/src/source/mod.rs', lines 22:0-24:1 -/
structure source.Work where
  remaining : Std.U64

/-- [noble_wasm::source::admission::identity::Encoding]
    Source: 'crates/noble-wasm/src/source/admission/identity.rs', lines 6:0-10:1 -/
structure source.admission.identity.Encoding where
  out : output.Buffer
  todo : alloc.vec.Vec (Option noble_kernel.untrusted.NodeId)
  fuel : Std.Usize

/-- [noble_wasm::source::Identity]
    Source: 'crates/noble-wasm/src/source/mod.rs', lines 62:0-65:1 -/
structure source.Identity where
  id : Std.U64
  recipe : alloc.vec.Vec Std.U8

/-- [noble_wasm::source::admission::metadata::Totals]
    Source: 'crates/noble-wasm/src/source/admission/metadata.rs', lines 6:0-9:1 -/
structure source.admission.metadata.Totals where
  nodes : Std.Usize
  bytes : Std.Usize

/-- [noble_wasm::source::admission::Accepted]
    Source: 'crates/noble-wasm/src/source/admission.rs', lines 12:0-15:1 -/
structure source.admission.Accepted where
  definitions : alloc.vec.Vec noble_kernel.untrusted.Checked
  root : noble_kernel.untrusted.Checked

/-- [noble_wasm::source::plan::Action]
    Source: 'crates/noble-wasm/src/source/plan.rs', lines 11:0-20:1 -/
@[discriminant isize]
inductive source.plan.Action where
| I64 : Std.I64 → source.plan.Action
| Bool : Bool → source.plan.Action
| Unit : source.plan.Action
| Text : Std.U32 → Std.U32 → source.plan.Action
| Program : Std.Usize → source.plan.Action
| Word : Std.U32 → source.plan.Action
| Quote : Std.U32 → Std.U32 → Std.U32 → source.plan.Action
| Call : Std.Usize → Std.U64 → source.plan.Action

/-- [noble_wasm::source::plan::Operation]
    Source: 'crates/noble-wasm/src/source/plan.rs', lines 22:0-27:1 -/
structure source.plan.Operation where
  action : source.plan.Action
  input : Std.U32
  output : Std.U32
  effects : Std.U32

/-- [noble_wasm::source::plan::Program]
    Source: 'crates/noble-wasm/src/source/plan.rs', lines 29:0-37:1 -/
structure source.plan.Program where
  entry : Std.U32
  input : Std.U32
  output : Std.U32
  effects : Std.U32
  operations : alloc.vec.Vec source.plan.Operation
  depth : Std.U32
  leaves : Std.U32

/-- [noble_wasm::source::types::Shape]
    Source: 'crates/noble-wasm/src/source/types.rs', lines 9:0-20:1 -/
@[discriminant isize]
inductive source.types.Shape where
| Scalar : Std.U32 → source.types.Shape
| Pair : Std.U32 → Std.U32 → source.types.Shape
| Sum : Std.U32 → Std.U32 → source.types.Shape
| List : Std.U32 → source.types.Shape
| Program : Std.U32 → Std.U32 → Std.U32 → source.types.Shape
| Syntax : source.types.Shape
| Text : source.types.Shape
| Contract : source.types.Shape
| Evidence : source.types.Shape
| Certified : source.types.Shape

/-- [noble_wasm::source::types::Registry]
    Source: 'crates/noble-wasm/src/source/types.rs', lines 22:0-25:1 -/
structure source.types.Registry where
  keys : alloc.vec.Vec noble_kernel.types.Ty
  shapes : alloc.vec.Vec source.types.Shape

/-- [noble_wasm::source::plan::Layout]
    Source: 'crates/noble-wasm/src/source/plan.rs', lines 39:0-51:1 -/
structure source.plan.Layout where
  programs : alloc.vec.Vec source.plan.Program
  order : alloc.vec.Vec Std.Usize
  first_function : Std.U32
  functions : Std.U32
  root : Std.Usize
  data : alloc.vec.Vec (Std.U32 × (alloc.vec.Vec Std.U8))
  descriptors : alloc.vec.Vec (Std.U32 × Std.U32)
  types : source.types.Registry
  input_types : alloc.vec.Vec Std.U32
  output_types : alloc.vec.Vec Std.U32
  text_witness : Std.U32

/-- [noble_wasm::source::Compiler]
    Source: 'crates/noble-wasm/src/source/mod.rs', lines 52:0-59:1
    Visibility: public -/
structure source.Compiler where
  generation : Std.U32
  functions : Std.U32
  text_end : Std.U32
  signatures : signatures.Pool
  descriptors : alloc.vec.Vec (Std.U32 × Std.U32)
  identities : alloc.vec.Vec source.Identity

/-- [noble_wasm::source::transaction::Base]
    Source: 'crates/noble-wasm/src/source/transaction.rs', lines 4:0-11:1 -/
structure source.transaction.Base where
  generation : Std.U32
  functions : Std.U32
  text_end_bytes : Std.U32
  signature_count : Std.Usize
  descriptor_count : Std.Usize
  identity_count : Std.Usize

/-- [noble_wasm::source::Prepared]
    Source: 'crates/noble-wasm/src/source/mod.rs', lines 68:0-72:1
    Visibility: public -/
structure source.Prepared where
  base : source.transaction.Base
  next : source.Compiler
  wat : alloc.vec.Vec Std.U8

/-- [noble_wasm::source::plan::Arena]
    Source: 'crates/noble-wasm/src/source/plan.rs', lines 53:0-56:1 -/
structure source.plan.Arena where
  root : Std.Usize
  quotes : alloc.vec.Vec (Option Std.Usize)

/-- [noble_wasm::source::plan::operations::Input]
    Source: 'crates/noble-wasm/src/source/plan/operations.rs', lines 7:0-13:1 -/
structure source.plan.operations.Input where
  submission : noble_kernel.execution.Submission
  body : noble_kernel.execution.Body
  checked : noble_kernel.untrusted.Checked
  arena : source.plan.Arena
  arenas : Slice source.plan.Arena

end noble_wasm
