-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [noble_wasm]: type definitions
import Aeneas
import NobleWasmImpl.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace noble_wasm

/-- [noble_kernel::untrusted::NodeId]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 18:0-18:17
    Name pattern: [noble_kernel::untrusted::NodeId]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::untrusted::NodeId"]
def noble_kernel.untrusted.NodeId := Std.U32

/-- [noble_kernel::types::ResourceKind]
    Source: 'crates/noble-kernel/src/types.rs', lines 15:0-15:23
    Name pattern: [noble_kernel::types::ResourceKind]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::types::ResourceKind"]
def noble_kernel.types.ResourceKind := Std.U32

/-- [noble_kernel::types::Ty]
    Source: 'crates/noble-kernel/src/types.rs', lines 157:0-157:11
    Name pattern: [noble_kernel::types::Ty]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::types::Ty"]
inductive noble_kernel.types.Ty where
| UnitType : noble_kernel.types.Ty
| BoolType : noble_kernel.types.Ty
| I64Type : noble_kernel.types.Ty
| TextType : noble_kernel.types.Ty
| SyntaxType : noble_kernel.types.Ty
| PairType :
  noble_kernel.types.Ty →
  noble_kernel.types.Ty →
  noble_kernel.types.Ty
| SumType :
  noble_kernel.types.Ty →
  noble_kernel.types.Ty →
  noble_kernel.types.Ty
| ListType : noble_kernel.types.Ty → noble_kernel.types.Ty
| ProgramType :
  alloc.vec.Vec noble_kernel.types.Ty →
  alloc.vec.Vec noble_kernel.types.Ty →
  noble_kernel.types.EffSet →
  noble_kernel.types.Ty
| ResourceType : noble_kernel.types.ResourceKind → noble_kernel.types.Ty

/-- [noble_kernel::types::EffId]
    Source: 'crates/noble-kernel/src/types.rs', lines 26:0-26:16
    Name pattern: [noble_kernel::types::EffId]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::types::EffId"]
def noble_kernel.types.EffId := Std.U32

/-- [noble_kernel::contracts::Definition]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 11:0-11:21
    Name pattern: [noble_kernel::contracts::Definition]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::contracts::Definition"]
def noble_kernel.contracts.Definition := Std.U32

/-- [noble_kernel::untrusted::Constraint]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 206:0-206:19
    Name pattern: [noble_kernel::untrusted::Constraint]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Constraint"]
inductive noble_kernel.untrusted.Constraint where
| StackJoin : noble_kernel.untrusted.Constraint
| StackOrder : noble_kernel.untrusted.Constraint
| EffectInclusion :
  noble_kernel.types.EffId →
  noble_kernel.untrusted.Constraint
| Eligibility : noble_kernel.types.Ty → noble_kernel.untrusted.Constraint
| UnknownEffect :
  noble_kernel.types.EffId →
  noble_kernel.untrusted.Constraint
| InstantiationKind : noble_kernel.untrusted.Constraint
| InstantiationArity : noble_kernel.untrusted.Constraint
| MalformedReference :
  noble_kernel.untrusted.NodeId →
  noble_kernel.untrusted.Constraint
| UnknownDefinition :
  noble_kernel.contracts.Definition →
  noble_kernel.untrusted.Constraint
| CyclicWitness : noble_kernel.untrusted.Constraint

/-- [noble_kernel::untrusted::Diagnostic]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 232:0-232:21
    Name pattern: [noble_kernel::untrusted::Diagnostic]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Diagnostic"]
structure noble_kernel.untrusted.Diagnostic where
  node : Option noble_kernel.untrusted.NodeId
  «def» : Option noble_kernel.contracts.Definition
  expected : alloc.vec.Vec noble_kernel.types.Ty
  actual : alloc.vec.Vec noble_kernel.types.Ty
  constraint : noble_kernel.untrusted.Constraint
  provenance_available : Bool
  truncated : Bool

/-- [noble_kernel::contracts::SchemaId]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 21:0-21:19
    Name pattern: [noble_kernel::contracts::SchemaId]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::contracts::SchemaId"]
def noble_kernel.contracts.SchemaId := Std.U32

/-- [noble_kernel::untrusted::UnsupportedKind]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 187:0-187:24
    Name pattern: [noble_kernel::untrusted::UnsupportedKind]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::UnsupportedKind"]
inductive noble_kernel.untrusted.UnsupportedKind where
| FormatRevision : noble_kernel.untrusted.UnsupportedKind
| NodeForm : noble_kernel.untrusted.UnsupportedKind
| SchemeForm : noble_kernel.untrusted.UnsupportedKind
| RecursiveDependency :
  noble_kernel.contracts.Definition →
  noble_kernel.untrusted.UnsupportedKind
| RecursiveSchema :
  noble_kernel.contracts.SchemaId →
  noble_kernel.untrusted.UnsupportedKind

/-- [noble_kernel::untrusted::LimitKind]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 168:0-168:18
    Name pattern: [noble_kernel::untrusted::LimitKind]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::LimitKind"]
inductive noble_kernel.untrusted.LimitKind where
| Bytes : noble_kernel.untrusted.LimitKind
| Nodes : noble_kernel.untrusted.LimitKind
| Depth : noble_kernel.untrusted.LimitKind
| TypeSize : noble_kernel.untrusted.LimitKind
| StackHeight : noble_kernel.untrusted.LimitKind
| Work : noble_kernel.untrusted.LimitKind
| Diagnostics : noble_kernel.untrusted.LimitKind

/-- [noble_kernel::untrusted::Interface]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 139:0-139:20
    Name pattern: [noble_kernel::untrusted::Interface]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Interface"]
structure noble_kernel.untrusted.Interface where
  stack_in : alloc.vec.Vec noble_kernel.types.Ty
  stack_out : alloc.vec.Vec noble_kernel.types.Ty
  effects : noble_kernel.types.EffSet

/-- [noble_kernel::untrusted::Derivation]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 150:0-150:21
    Name pattern: [noble_kernel::untrusted::Derivation]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Derivation"]
structure noble_kernel.untrusted.Derivation where
  node : noble_kernel.untrusted.NodeId
  interface : noble_kernel.untrusted.Interface

/-- [noble_kernel::untrusted::Checked]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 159:0-159:18
    Name pattern: [noble_kernel::untrusted::Checked]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Checked"]
structure noble_kernel.untrusted.Checked where
  interface : noble_kernel.untrusted.Interface
  derivations : alloc.vec.Vec noble_kernel.untrusted.Derivation

/-- [noble_kernel::untrusted::Outcome]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 251:0-251:16
    Name pattern: [noble_kernel::untrusted::Outcome]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Outcome"]
inductive noble_kernel.untrusted.Outcome where
| Accepted : noble_kernel.untrusted.Checked → noble_kernel.untrusted.Outcome
| Invalid :
  noble_kernel.untrusted.Diagnostic →
  noble_kernel.untrusted.Outcome
| Unsupported :
  noble_kernel.untrusted.UnsupportedKind →
  noble_kernel.untrusted.Outcome
| Exhausted :
  noble_kernel.untrusted.LimitKind →
  noble_kernel.untrusted.Outcome
| InternalFailure : noble_kernel.untrusted.Outcome

/-- [noble_kernel::untrusted::Limits]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 104:0-104:17
    Name pattern: [noble_kernel::untrusted::Limits]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Limits"]
structure noble_kernel.untrusted.Limits where
  bytes : Std.U32
  nodes : Std.U32
  depth : Std.U32
  type_size : Std.U32
  stack_height : Std.U32
  work : Std.U32
  diagnostics : Std.U32

/-- [noble_kernel::untrusted::Expected]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 93:0-93:19
    Name pattern: [noble_kernel::untrusted::Expected]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Expected"]
structure noble_kernel.untrusted.Expected where
  stack_in : alloc.vec.Vec noble_kernel.types.Ty
  stack_out : alloc.vec.Vec noble_kernel.types.Ty
  allowed_effects : noble_kernel.types.EffSet

/-- [noble_kernel::untrusted::Request]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 127:0-127:18
    Name pattern: [noble_kernel::untrusted::Request]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Request"]
structure noble_kernel.untrusted.Request where
  input_bytes : Std.U32
  expected : noble_kernel.untrusted.Expected
  limits : noble_kernel.untrusted.Limits

/-- [noble_kernel::words::Variable]
    Source: 'crates/noble-kernel/src/words.rs', lines 18:0-18:19
    Name pattern: [noble_kernel::words::Variable]
    Visibility: public -/
@[reducible, rust_type "noble_kernel::words::Variable"]
def noble_kernel.words.Variable := Std.U32

/-- [noble_kernel::words::Binding]
    Source: 'crates/noble-kernel/src/words.rs', lines 48:0-48:16
    Name pattern: [noble_kernel::words::Binding]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::words::Binding"]
inductive noble_kernel.words.Binding where
| Stack : alloc.vec.Vec noble_kernel.types.Ty → noble_kernel.words.Binding
| Value : noble_kernel.types.Ty → noble_kernel.words.Binding
| Effect : noble_kernel.types.EffSet → noble_kernel.words.Binding
| Ref : noble_kernel.words.Variable → noble_kernel.words.Binding

/-- [noble_kernel::words::Inst]
    Source: 'crates/noble-kernel/src/words.rs', lines 64:0-64:15
    Name pattern: [noble_kernel::words::Inst]
    Visibility: public -/
@[rust_type "noble_kernel::words::Inst"]
structure noble_kernel.words.Inst where
  bindings : alloc.vec.Vec noble_kernel.words.Binding

/-- [noble_kernel::untrusted::Lit]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 27:0-27:12
    Name pattern: [noble_kernel::untrusted::Lit]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Lit"]
inductive noble_kernel.untrusted.Lit where
| I64Lit : Std.I64 → noble_kernel.untrusted.Lit
| BoolLit : Bool → noble_kernel.untrusted.Lit
| TextLit : noble_kernel.untrusted.Lit
| UnitLit : noble_kernel.untrusted.Lit

/-- [noble_kernel::untrusted::Node]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 53:0-53:13
    Name pattern: [noble_kernel::untrusted::Node]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::untrusted::Node"]
inductive noble_kernel.untrusted.Node where
| Literal :
  noble_kernel.untrusted.Lit →
  noble_kernel.words.Inst →
  noble_kernel.untrusted.Node
| Invocation :
  noble_kernel.contracts.Definition →
  noble_kernel.words.Inst →
  noble_kernel.untrusted.Node
| Quotation :
  alloc.vec.Vec noble_kernel.untrusted.NodeId →
  noble_kernel.words.Inst →
  noble_kernel.untrusted.Node

/-- [noble_kernel::untrusted::Candidate]
    Source: 'crates/noble-kernel/src/untrusted.rs', lines 80:0-80:20
    Name pattern: [noble_kernel::untrusted::Candidate]
    Visibility: public -/
@[rust_type "noble_kernel::untrusted::Candidate"]
structure noble_kernel.untrusted.Candidate where
  format : Std.U32
  revision : Std.U32
  nodes : alloc.vec.Vec noble_kernel.untrusted.Node
  body : alloc.vec.Vec noble_kernel.untrusted.NodeId

/-- [noble_kernel::words::VariableKind]
    Source: 'crates/noble-kernel/src/words.rs', lines 22:0-22:21
    Name pattern: [noble_kernel::words::VariableKind]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::words::VariableKind"]
inductive noble_kernel.words.VariableKind where
| Stack : noble_kernel.words.VariableKind
| Value : noble_kernel.words.VariableKind
| Effect : noble_kernel.words.VariableKind

/-- [noble_kernel::shapes::EffectSlot]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 74:0-74:19
    Name pattern: [noble_kernel::shapes::EffectSlot]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::shapes::EffectSlot"]
inductive noble_kernel.shapes.EffectSlot where
| Effect : noble_kernel.types.EffId → noble_kernel.shapes.EffectSlot
| Var : noble_kernel.words.Variable → noble_kernel.shapes.EffectSlot

/-- [noble_kernel::shapes::Pattern]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 26:0-26:16
    Name pattern: [noble_kernel::shapes::Pattern]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::shapes::Pattern"]
inductive noble_kernel.shapes.Pattern where
| UnitPattern : noble_kernel.shapes.Pattern
| BoolPattern : noble_kernel.shapes.Pattern
| I64Pattern : noble_kernel.shapes.Pattern
| TextPattern : noble_kernel.shapes.Pattern
| SyntaxPattern : noble_kernel.shapes.Pattern
| PairPattern :
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern
| SumPattern :
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern →
  noble_kernel.shapes.Pattern
| ListPattern : noble_kernel.shapes.Pattern → noble_kernel.shapes.Pattern
| ProgramPattern :
  alloc.vec.Vec noble_kernel.shapes.Pattern →
  alloc.vec.Vec noble_kernel.shapes.Pattern →
  alloc.vec.Vec noble_kernel.shapes.EffectSlot →
  noble_kernel.shapes.Pattern
| ResourcePattern :
  noble_kernel.types.ResourceKind →
  noble_kernel.shapes.Pattern
| VarPattern : noble_kernel.words.Variable → noble_kernel.shapes.Pattern
| StackVarPattern : noble_kernel.words.Variable → noble_kernel.shapes.Pattern

/-- [noble_kernel::words::Scheme]
    Source: 'crates/noble-kernel/src/words.rs', lines 34:0-34:17
    Name pattern: [noble_kernel::words::Scheme]
    Visibility: public -/
@[rust_type "noble_kernel::words::Scheme"]
structure noble_kernel.words.Scheme where
  var_kinds : alloc.vec.Vec noble_kernel.words.VariableKind
  stack_in : alloc.vec.Vec noble_kernel.shapes.Pattern
  stack_out : alloc.vec.Vec noble_kernel.shapes.Pattern
  effects : alloc.vec.Vec noble_kernel.shapes.EffectSlot

/-- [noble_kernel::contracts::SchemaDecl]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 83:0-83:21
    Name pattern: [noble_kernel::contracts::SchemaDecl]
    Visibility: public -/
@[rust_type "noble_kernel::contracts::SchemaDecl"]
structure noble_kernel.contracts.SchemaDecl where
  id : noble_kernel.contracts.SchemaId
  scheme : noble_kernel.words.Scheme
  recursive : Bool

/-- [noble_kernel::contracts::Behavior]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 30:0-30:17
    Name pattern: [noble_kernel::contracts::Behavior]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::contracts::Behavior"]
inductive noble_kernel.contracts.Behavior where
| DupBehavior : noble_kernel.contracts.Behavior
| DropBehavior : noble_kernel.contracts.Behavior
| SwapBehavior : noble_kernel.contracts.Behavior
| DipBehavior : noble_kernel.contracts.Behavior
| ArithBehavior : noble_kernel.contracts.Behavior
| EqualsBehavior : noble_kernel.contracts.Behavior
| QuoteBehavior : noble_kernel.contracts.Behavior
| ComposeBehavior : noble_kernel.contracts.Behavior
| RunBehavior : noble_kernel.contracts.Behavior
| ReflectBehavior : noble_kernel.contracts.Behavior
| UnitBehavior : noble_kernel.contracts.Behavior
| PairBehavior : noble_kernel.contracts.Behavior
| UnpairBehavior : noble_kernel.contracts.Behavior
| InlBehavior : noble_kernel.contracts.Behavior
| InrBehavior : noble_kernel.contracts.Behavior
| CaseBehavior : noble_kernel.contracts.Behavior
| IfBehavior : noble_kernel.contracts.Behavior
| NilBehavior : noble_kernel.contracts.Behavior
| ConsBehavior : noble_kernel.contracts.Behavior
| ListCaseBehavior : noble_kernel.contracts.Behavior
| TestEmitBehavior : noble_kernel.contracts.Behavior
| NamedBehavior : noble_kernel.contracts.Behavior

/-- [noble_kernel::contracts::Env]
    Source: 'crates/noble-kernel/src/contracts.rs', lines 94:0-94:14
    Name pattern: [noble_kernel::contracts::Env]
    Visibility: public -/
@[rust_type "noble_kernel::contracts::Env"]
structure noble_kernel.contracts.Env where
  defs : alloc.vec.Vec noble_kernel.words.Scheme
  kinds : alloc.vec.Vec noble_kernel.contracts.Behavior
  deps : alloc.vec.Vec (alloc.vec.Vec noble_kernel.contracts.Definition)
  schemas : alloc.vec.Vec noble_kernel.contracts.SchemaDecl
  effects : alloc.vec.Vec noble_kernel.types.EffId

/-- [noble_kernel::shapes::Defect]
    Source: 'crates/noble-kernel/src/shapes.rs', lines 83:0-83:15
    Name pattern: [noble_kernel::shapes::Defect]
    Visibility: public -/
@[discriminant isize, rust_type "noble_kernel::shapes::Defect"]
inductive noble_kernel.shapes.Defect where
| UnknownVariable : noble_kernel.shapes.Defect
| KindMismatch : noble_kernel.shapes.Defect

/-- [noble_wasm::Diagnostic]
    Source: 'crates/noble-wasm/src/lib.rs', lines 43:0-48:1
    Visibility: public -/
@[discriminant isize]
inductive Diagnostic where
| Invalid : Diagnostic
| Exhausted : Diagnostic
| Unsupported : Diagnostic
| Defective : Diagnostic

/-- [noble_wasm::output::Buffer]
    Source: 'crates/noble-wasm/src/output.rs', lines 3:0-5:1 -/
structure output.Buffer where
  bytes : alloc.vec.Vec Std.U8

/-- [noble_wasm::signatures::Pool]
    Source: 'crates/noble-wasm/src/signatures.rs', lines 5:0-8:1 -/
structure signatures.Pool where
  keys : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  bytes : Std.Usize

/-- [noble_wasm::signatures::Interface]
    Source: 'crates/noble-wasm/src/signatures.rs', lines 11:0-14:1 -/
structure signatures.Interface where
  input : Std.U32
  output : Std.U32

/-- [noble_wasm::lowering::Program]
    Source: 'crates/noble-wasm/src/lowering.rs', lines 14:0-18:1 -/
structure lowering.Program where
  owner : Option Std.U32
  entry : Std.U32
  interface : signatures.Interface

/-- [noble_wasm::lowering::Operation]
    Source: 'crates/noble-wasm/src/lowering.rs', lines 4:0-11:1 -/
@[discriminant isize]
inductive lowering.Operation where
| I64 : Std.I64 → lowering.Operation
| Bool : Bool → lowering.Operation
| Unit : lowering.Operation
| Program : signatures.Interface → lowering.Operation
| Word : Std.U32 → lowering.Operation
| Quote : signatures.Interface → lowering.Operation

/-- [noble_wasm::lowering::Plan]
    Source: 'crates/noble-wasm/src/lowering.rs', lines 20:0-27:1 -/
structure lowering.Plan where
  nodes : alloc.vec.Vec (Option lowering.Operation)
  programs : alloc.vec.Vec lowering.Program
  signatures : signatures.Pool
  host_signatures : Array Std.U32 3#usize
  functions : Std.U32
  registry_slots : Std.U32

/-- [noble_wasm::Representation]
    Source: 'crates/noble-wasm/src/lib.rs', lines 36:0-39:1
    Visibility: public -/
@[discriminant isize]
inductive Representation where
| WasmGc : Representation
| ManagedLinearMemory : Representation

/-- [noble_wasm::signatures::walk::Step]
    Source: 'crates/noble-wasm/src/signatures/walk.rs', lines 6:0-10:1 -/
@[discriminant isize]
inductive signatures.walk.Step where
| «Type» : noble_kernel.types.Ty → signatures.walk.Step
| Stack : alloc.vec.Vec noble_kernel.types.Ty → signatures.walk.Step
| Byte : Std.U8 → signatures.walk.Step

/-- [noble_wasm::signatures::walk::State]
    Source: 'crates/noble-wasm/src/signatures/walk.rs', lines 12:0-16:1 -/
structure signatures.walk.State where
  work : alloc.vec.Vec signatures.walk.Step
  out : output.Buffer
  fuel : Std.Usize

end noble_wasm
